import legacyWorker from './_worker_legacy.js';
import {syncCanonicalRules,readCanonicalRules} from './lib/canonical_rules.js';
import {siteV2} from './lib/site_v2.js';
import {quoteDetailV3} from './lib/quote_detail_v3.js';
import {productionConsoleApi,readbackProductionStatus} from './lib/production_console_api.js';
import {ensureLegacyContentMigrated} from './lib/legacy_content_migration.js';
import {ensureWQ011SitePublished} from './lib/wq011_site_publish.js';
import {ensureWQ011PromptsSynced,readbackWQ011Prompts} from './lib/wq011_prompt_sync.js';
import {ensureWQ011CopySynced,readbackWQ011Copy} from './lib/wq011_copy_sync.js';
import {ensureWQ012SitePublished,readbackWQ012Site} from './lib/wq012_site_publish.js';
import {ensureWQ012ProductionSynced} from './lib/wq012_production_sync.js';
import {ensureWQ013SourceEvidence} from './lib/wq013_source_evidence.js';
import {ensureWQ013SitePublished,readbackWQ013Site} from './lib/wq013_site_publish.js';
import {finalizeWQ013Production} from './lib/wq013_production_finalize.js';
let rulesSynced=false,legacyMigrationChecked=false,wq011SitePublishChecked=false,wq011PromptSyncChecked=false,wq011CopySyncChecked=false,wq012SitePublishChecked=false,wq012ProductionSyncChecked=false,wq013EvidenceChecked=false,wq013SitePublishChecked=false,wq013ProductionFinalizeChecked=false,wq006PublishChecked=false;
const METRICOOL_HASHES={uk:'830c345454221aac5e51b0bd4a011207',ru:'59444f08c2a0238b2d40a21ae0aea0e0',pl:'c381513400756762969fc09f5b4fc98c',en:'8f23b8c0f14e3cfa6ff1eddf5ec69c02',sv:'f597d9425c80f6c53ffafa65f05dff2d',de:'8c66131b02cd287e4a0fc92b3ad5381c',es:'452cf36ec8ec1a188325f08c5eab21ff',fr:'ae56143c509d953161c3599111b6d55d'};
function metricoolScript(hash){return `<script>function loadScript(a){var b=document.getElementsByTagName("head")[0],c=document.createElement("script");c.type="text/javascript",c.src="https://tracker.metricool.com/resources/be.js",c.onreadystatechange=a,c.onload=a,b.appendChild(c)}loadScript(function(){beTracker.t({hash:"${hash}"})});</script>`}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function withLocaleTracking(response,url){if(!response)return response;const locale=url.pathname.match(/^\/(uk|ru|pl|en|sv|de|es|fr)(?:\/|$)/)?.[1],hash=locale&&METRICOOL_HASHES[locale];if(!hash)return response;const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;const html=await response.text();if(html.includes(hash))return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});const tracked=html.includes('</head>')?html.replace('</head>',`${metricoolScript(hash)}</head>`):html,headers=new Headers(response.headers);headers.delete('content-length');return new Response(tracked,{status:response.status,statusText:response.statusText,headers})}
async function publishExplicitWQ006(env){if(wq006PublishChecked||!env.DB)return;wq006PublishChecked=true;const approved=await env.DB.prepare(`SELECT 1 ok FROM content_approvals WHERE content_item_id='WQ006' AND approval_scope='content' AND language_code IS NULL AND status='approved' LIMIT 1`).first();if(!approved)return;const ready=await env.DB.prepare(`SELECT COUNT(*) n FROM quote_pages WHERE project_id='wisequotesworld' AND content_item_id='WQ006' AND language_code IN ('uk','ru','pl','en','sv','de','es','fr') AND status IN ('ready','published')`).first();if(Number(ready?.n||0)!==8)return;const ts=new Date().toISOString();await env.DB.prepare(`UPDATE quote_pages SET status='published',published_at=COALESCE(published_at,?),updated_at=? WHERE project_id='wisequotesworld' AND content_item_id='WQ006' AND status IN ('ready','published')`).bind(ts,ts).run()}
function mediaKindSql(kind){return kind==='video'?`(LOWER(COALESCE(m.asset_type,'')) LIKE '%video%' OR LOWER(COALESCE(m.mime_type,'')) LIKE 'video/%')`:`(LOWER(COALESCE(m.asset_type,'')) LIKE '%pinterest%' OR LOWER(COALESCE(m.asset_type,'')) LIKE '%image%' OR LOWER(COALESCE(m.mime_type,'')) LIKE 'image/%')`}
async function approvedMedia(request,env,id,lang,kind){if(!env.DB||!env.MEDIA)return json({ok:false,error:'media delivery unavailable'},503);const sql=`SELECT m.r2_key,m.mime_type,m.original_filename FROM media_inbox m JOIN media_reviews r ON r.media_inbox_id=m.id WHERE m.project_id='wisequotesworld' AND m.content_item_id=? AND m.language_code=? AND r.qa_status='approved' AND ${mediaKindSql(kind)} ORDER BY m.created_at DESC LIMIT 1`,row=await env.DB.prepare(sql).bind(id,lang).first();if(!row?.r2_key)return json({ok:false,error:'approved media not found'},404);const obj=await env.MEDIA.get(row.r2_key);if(!obj)return json({ok:false,error:'R2 object missing'},404);const headers=new Headers();obj.writeHttpMetadata(headers);headers.set('content-type',row.mime_type||headers.get('content-type')||'application/octet-stream');headers.set('cache-control','public, max-age=86400, immutable');return new Response(obj.body,{headers})}
async function ensureContentVersionUpdatedAt(env){if(!env.DB)return;try{await env.DB.exec(`ALTER TABLE content_versions ADD COLUMN updated_at TEXT`)}catch(e){if(!String(e?.message||e).includes('duplicate column name'))throw e}}
export default {async fetch(request,env,ctx){try{const url=new URL(request.url);if(env.DB&&!rulesSynced){await syncCanonicalRules(env);rulesSynced=true}if(env.DB&&!legacyMigrationChecked){await ensureLegacyContentMigrated(env);legacyMigrationChecked=true}if(env.DB&&!wq011SitePublishChecked){await ensureWQ011SitePublished(env);wq011SitePublishChecked=true}if(env.DB&&!wq011PromptSyncChecked){await ensureWQ011PromptsSynced(env);wq011PromptSyncChecked=true}if(env.DB&&!wq011CopySyncChecked){await ensureWQ011CopySynced(env);wq011CopySyncChecked=true}if(env.DB&&!wq012SitePublishChecked){await ensureWQ012SitePublished(env);wq012SitePublishChecked=true}if(env.DB&&!wq012ProductionSyncChecked){await ensureContentVersionUpdatedAt(env);await ensureWQ012ProductionSynced(env);wq012ProductionSyncChecked=true}if(env.DB&&!wq013EvidenceChecked){await ensureWQ013SourceEvidence(env);wq013EvidenceChecked=true}if(env.DB&&!wq013SitePublishChecked){await ensureWQ013SitePublished(env);wq013SitePublishChecked=true}if(env.DB&&!wq013ProductionFinalizeChecked){await finalizeWQ013Production(env);wq013ProductionFinalizeChecked=true}await publishExplicitWQ006(env);if(url.pathname==='/ops/readback/wq011-prompts.json'&&request.method==='GET')return json(await readbackWQ011Prompts(env));if(url.pathname==='/ops/readback/wq011-production.json'&&request.method==='GET')return json({production:await readbackProductionStatus(env,'WQ011'),copy:await readbackWQ011Copy(env),rules:await readCanonicalRules(env)});if(url.pathname==='/ops/readback/wq012-site.json'&&request.method==='GET')return json(await readbackWQ012Site(env));if(url.pathname==='/ops/readback/wq012-production.json'&&request.method==='GET')return json({production:await readbackProductionStatus(env,'WQ012'),rules:await readCanonicalRules(env)});if(url.pathname==='/ops/readback/wq013-site.json'&&request.method==='GET')return json(await readbackWQ013Site(env));if(url.pathname==='/ops/readback/wq013-production.json'&&request.method==='GET')return json({production:await readbackProductionStatus(env,'WQ013'),rules:await readCanonicalRules(env)});if(url.pathname==='/admin'||url.pathname==='/admin/')return Response.redirect(`${url.origin}/admin/console/`,302);const m=url.pathname.match(/^\/media\/approved\/([A-Za-z0-9_-]+)\/(uk|ru|pl|en|sv|de|es|fr)\/(video|pinterest)$/);if(m&&request.method==='GET')return approvedMedia(request,env,m[1],m[2],m[3]);const productionResponse=await productionConsoleApi(request,env);if(productionResponse)return productionResponse;const detailResponse=await quoteDetailV3(request,env);if(detailResponse)return withLocaleTracking(detailResponse,url);const publicResponse=await siteV2(request,env);if(publicResponse)return withLocaleTracking(publicResponse,url);return withLocaleTracking(await legacyWorker.fetch(request,env,ctx),url)}catch(e){return json({ok:false,error:String(e?.message||e)},500)}}};