const $=id=>document.getElementById(id);
const LANGS=['uk','ru','pl','en','sv','de','es','fr'];
const OUTS=['article_url','pinterest_prompt','facebook','instagram','threads','tiktok','youtube_title','youtube_description','pinterest_title','pinterest_description','website_reflection'];
const LABELS={article_url:'Localized article URL',pinterest_prompt:'Pinterest image prompt',facebook:'Facebook',instagram:'Instagram',threads:'Threads',tiktok:'TikTok',youtube_title:'YouTube title',youtube_description:'YouTube description',pinterest_title:'Pinterest title',pinterest_description:'Pinterest description',website_reflection:'Website reflection'};
let TOKEN=localStorage.getItem('wq_admin_token')||'';let ITEMS=[];let CURRENT=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,opt={}){opt.headers={...(opt.headers||{}),Authorization:'Bearer '+TOKEN};const r=await fetch(path,opt);let j;try{j=await r.json()}catch{j={ok:false,error:'non-json response'}}if(!r.ok)throw new Error(j.error||('HTTP '+r.status));return j}
function tab(name){document.querySelectorAll('[data-tab],.section').forEach(x=>x.classList.remove('on'));document.querySelector(`[data-tab="${name}"]`)?.classList.add('on');$(name)?.classList.add('on');if(name==='content'||name==='approval')loadContent();if(name==='media')loadMedia()}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));
function buildMatrix(){if(!$('matrix'))return;$('matrix').innerHTML=LANGS.map(l=>`<div class="matrixrow"><b>${l.toUpperCase()}</b><label>Video<input data-matrix="1" data-lang="${l}" data-kind="video" type="file" accept="video/*"></label><label>Pinterest<input data-matrix="1" data-lang="${l}" data-kind="pinterest" type="file" accept="image/*"></label></div>`).join('')}
function copyField(id){const el=$(id);if(!el)return;const text=el.value||'';navigator.clipboard?.writeText(text).then(()=>flash('Скопійовано')).catch(()=>{el.focus();el.select();document.execCommand('copy');flash('Скопійовано')})}
function flash(t){let n=$('toast');if(!n){n=document.createElement('div');n.id='toast';document.body.appendChild(n)}n.textContent=t;n.className='toast show';setTimeout(()=>n.className='toast',1200)}
function field(label,id,value,cls=''){return `<label>${label}<div class="fieldhead"><button type="button" class="copy tiny" onclick="copyField('${id}')">Копіювати</button></div><textarea id="${id}" class="${cls}">${esc(value||'')}</textarea></label>`}
async function connect(){TOKEN=$('token').value.trim();localStorage.setItem('wq_admin_token',TOKEN);try{const [h,s]=await Promise.all([fetch('/api/health').then(r=>r.json()),api('/api/admin/schema')]);$('health').textContent='● online';$('health').className='online';$('sys').className='status ok';$('sys').textContent=`D1 ${h.db?'✓':'✗'} · R2 ${h.r2?'✓':'✗'} · Admin ${h.admin_secret?'✓':'✗'} · schema ${s.schema?.ready?'ready':'check'}`;$('kDb').textContent=s.schema?.ready?'READY':'CHECK';await Promise.all([loadContent(),loadMedia()])}catch(e){$('health').textContent='● error';$('health').className='offline';$('sys').className='status bad';$('sys').textContent=e.message}}
async function loadContent(){try{const j=await api('/api/admin/content');ITEMS=j.items||[];$('kContent').textContent=ITEMS.length;$('contentList').innerHTML=ITEMS.map(x=>`<button class="rowbtn" onclick="openItem('${x.id}')"><b>${x.id}</b><span>${esc(x.canonical_title||'')}</span><span class="pill">${esc(x.quote_type||'')}</span><span>${x.approved_at?'✓ approved':esc(x.status||'')}</span></button>`).join('')||'<p>Немає контенту.</p>';$('approvalList').innerHTML=ITEMS.map(x=>`<div class="approvalrow"><div><b>${x.id}</b><div>${esc(x.canonical_title||'')}</div><small>${esc(x.quote_type||'')} · ${esc(x.attribution_status||'')}</small></div><div class="actions"><button class="secondary" onclick="openItem('${x.id}')">Review</button><button onclick="approve('${x.id}','approved')">Approve</button><button class="danger" onclick="approve('${x.id}','rejected')">Reject</button></div></div>`).join('');$('kApproved').textContent=ITEMS.filter(x=>x.approved_at||x.status==='approved').length}catch(e){$('contentList').innerHTML='<p>'+esc(e.message)+'</p>'}}
async function openItem(id){try{CURRENT=id;const [j,p]=await Promise.all([api('/api/admin/content/'+id),api('/api/admin/production/'+id)]),x=j.item,latest={},omap={};(x.versions||[]).forEach(v=>{if(!latest[v.language_code]||Number(v.version)>Number(latest[v.language_code].version))latest[v.language_code]=v});(p.outputs||[]).forEach(o=>omap[`${o.language_code}:${o.output_key}`]=o.output_text||'');const rmap={};(p.readiness?.languages||[]).forEach(r=>rmap[r.language]=r);$('detail').innerHTML=`<div class="detailhead"><div><h2>${id}</h2><p class="quotelead">${esc(x.original_quote||x.canonical_title||'')}</p><p class="muted">${esc(x.quote_type)} · ${x.author_name?esc(x.author_name):'NO AUTHOR'} · ${esc(x.attribution_status||'')} · category: ${esc(x.category_slug||x.category||'—')}</p><div class="status ${p.readiness?.ready_for_metricool?'ok':''}">Metricool readiness: <b>${p.readiness?.ready_for_metricool?'READY':'NOT READY'}</b> · source ${p.readiness?.source_ok?'✓':'✗'} · approval ${esc(p.readiness?.approval?.status||'pending')}</div><div class="jumpbar">${LANGS.map(l=>`<a href="#lang_${l}">${l.toUpperCase()}</a>`).join('')}</div></div><div class="actions"><button onclick="approve('${id}','approved')">Approve</button><button class="danger" onclick="approve('${id}','rejected')">Reject</button></div></div><div class="langgrid">${LANGS.map(l=>{const v=latest[l],rr=rmap[l]||{};return `<article class="lang" id="lang_${l}"><header><b>${l.toUpperCase()}</b><span class="pill ${rr.ready?'good':'warn'}">${rr.ready?'publication ready':'incomplete'}</span></header>${field('Localized quote',`q_${l}`,v?.adapted_text,'localized')}${field('Gemini production prompt',`gp_${l}`,v?.ai_prompt,'prompt')}${field('Voiceover',`vo_${l}`,v?.voiceover_text||v?.adapted_text)}${field('On-screen exact text',`os_${l}`,v?.on_screen_text||v?.adapted_text)}<button onclick="saveVersion('${id}','${l}',${Number(v?.version||1)})">Save language</button><hr>${OUTS.map(k=>field(LABELS[k],`out_${l}_${k}`,omap[`${l}:${k}`],k==='pinterest_prompt'?'prompt':'')).join('')}<button class="secondary" onclick="saveOutputs('${id}','${l}')">Save outputs</button><div class="checklist"><small>Version ${rr.version?'✓':'✗'} · Gemini ${rr.video_prompt?'✓':'✗'} · Pinterest prompt ${rr.pinterest_prompt?'✓':'✗'} · Article URL ${rr.article_url?'✓':'✗'} · copy ${rr.copy||0}/8 · video ${rr.video?'✓':'✗'} · image ${rr.pinterest?'✓':'✗'} · QA ${rr.media_qa?'✓':'✗'}</small></div><div class="links"><a target="_blank" href="/${l}/">Site</a>${(x.quote_pages||[]).find(pg=>pg.language_code===l)?.canonical_path?`<a target="_blank" href="${esc((x.quote_pages||[]).find(pg=>pg.language_code===l).canonical_path)}">Quote page</a>`:''}</div></article>`}).join('')}</div>`;tab('content')}catch(e){$('detail').innerHTML='<p>'+esc(e.message)+'</p>'}}
async function saveVersion(id,l,version){try{const payload={version,adapted_text:$(`q_${l}`).value,voiceover_text:$(`vo_${l}`).value,on_screen_text:$(`os_${l}`).value,ai_prompt:$(`gp_${l}`).value,status:'prompt_ready',language_check_status:'prepared'};await api(`/api/admin/content/${id}/versions/${l}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});flash(`${l.toUpperCase()}: saved`);await openItem(id)}catch(e){alert(e.message)}}
async function saveOutputs(id,l){try{for(const k of OUTS){await api(`/api/admin/production/${id}/outputs/${l}/${k}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({output_text:$(`out_${l}_${k}`).value,status:'ready'})})}flash(`${l.toUpperCase()}: outputs saved`);await openItem(id)}catch(e){alert(e.message)}}
async function approve(id,status){try{await api(`/api/admin/content/${id}/approval`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({status})});flash(`${id}: ${status}`);await loadContent();if(CURRENT===id)openItem(id)}catch(e){alert(e.message)}}
async function loadMedia(){try{const j=await api('/api/admin/media'),a=j.items||[];$('kMedia').textContent=a.length;$('mediaList').innerHTML=a.slice(0,120).map(m=>`<div class="mediarow"><b>${esc(m.content_item_id||'—')}</b><span>${esc(m.language_code||'—')}</span><span>${esc(m.asset_type||'media')}</span><span>${esc(m.original_filename||m.r2_key||'')}</span><span class="actions"><button class="secondary tiny" onclick="qa('${m.id}','approved')">QA ✓</button><button class="danger tiny" onclick="qa('${m.id}','rejected')">×</button></span></div>`).join('')||'<p>Немає медіа.</p>'}catch(e){$('mediaList').innerHTML='<p>'+esc(e.message)+'</p>'}}
async function uploadOne(cid,lang,kind,file){const fd=new FormData();fd.append('file',file);fd.append('content_item_id',cid);fd.append('language_code',lang);fd.append('asset_type',kind);return api('/api/admin/media',{method:'POST',body:fd})}
async function uploadMedia(){const f=$('mFile').files[0];if(!f){setUpload('Вибери файл.','bad');return}setUpload(`Завантаження ${f.name}…`,'');try{await uploadOne($('mCid').value.trim(),$('mLang').value,$('mKind').value,f);setUpload('Готово: R2 + D1.','ok');$('mFile').value='';await loadMedia()}catch(e){setUpload(e.message,'bad')}}
async function uploadMatrix(){const cid=$('matrixCid').value.trim(),inputs=[...document.querySelectorAll('[data-matrix="1"]')].filter(i=>i.files[0]);if(!inputs.length){$('matrixStatus').className='status bad';$('matrixStatus').textContent='Вибери хоча б один файл.';return}let done=0;for(const i of inputs){const f=i.files[0];$('matrixStatus').textContent=`${done+1}/${inputs.length}: ${i.dataset.lang.toUpperCase()} ${i.dataset.kind} — ${f.name}`;try{await uploadOne(cid,i.dataset.lang,i.dataset.kind,f);done++}catch(e){$('matrixStatus').className='status bad';$('matrixStatus').textContent=`Помилка ${i.dataset.lang} ${i.dataset.kind}: ${e.message}`;return}}$('matrixStatus').className='status ok';$('matrixStatus').textContent=`Готово: ${done} файл(ів) завантажено.`;inputs.forEach(i=>i.value='');await loadMedia();if(CURRENT===cid)openItem(cid)}
async function qa(id,status){try{await api(`/api/admin/production/media/${id}/qa`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({status})});await loadMedia();if(CURRENT)openItem(CURRENT)}catch(e){alert(e.message)}}
function setUpload(t,c){$('uploadStatus').className='status '+c;$('uploadStatus').textContent=t}
async function schema(){try{$('raw').textContent=JSON.stringify(await api('/api/admin/schema'),null,2)}catch(e){$('raw').textContent=e.message}}
$('token').value=TOKEN;buildMatrix();$('connectBtn').onclick=connect;$('uploadBtn').onclick=uploadMedia;$('matrixUploadBtn').onclick=uploadMatrix;$('schemaBtn').onclick=schema;$('refreshContent').onclick=loadContent;$('refreshMedia').onclick=loadMedia;if(TOKEN)connect();window.openItem=openItem;window.approve=approve;window.saveVersion=saveVersion;window.saveOutputs=saveOutputs;window.qa=qa;window.copyField=copyField;