const $=id=>document.getElementById(id);
const SOCIAL_LANGS=['uk','ru','pl','en','sv','de','es','fr'];
const OUTS=['article_url','pinterest_prompt','facebook','instagram','threads','tiktok','youtube_title','youtube_description','pinterest_title','pinterest_description','website_reflection'];
const LABELS={article_url:'Localized article URL',pinterest_prompt:'Pinterest image prompt',facebook:'Facebook',instagram:'Instagram',threads:'Threads ×3',tiktok:'TikTok',youtube_title:'YouTube title',youtube_description:'YouTube description',pinterest_title:'Pinterest title',pinterest_description:'Pinterest description',website_reflection:'Website reflection'};
const STATUS_LABEL={idea:'Майбутня',source_check:'Перевірка джерела',quote_ready:'Цитата готова',localized:'Локалізовано',native_language_qa:'Native QA',prompt_ready:'Prompts готові',copy_ready:'Posts готові',website_ready:'Статті готові',pinterest_ready:'Pinterest готовий',media_pending:'Чекає media',media_ready:'Media готові',approved:'Approved',scheduled:'Заплановано',published:'Опубліковано',skipped:'Пропущено'};
let TOKEN=localStorage.getItem('wq_admin_token')||'';
let ITEMS=[],TOPICS=[],CURRENT=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,opt={}){opt.headers={...(opt.headers||{}),Authorization:'Bearer '+TOKEN};const r=await fetch(path,opt);let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
function flash(text){let n=$('toast');if(!n){n=document.createElement('div');n.id='toast';n.className='toast';document.body.appendChild(n)}n.textContent=text;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),1500)}
function modalConfirm(title,text){return new Promise(resolve=>{const m=$('confirmModal');$('confirmTitle').textContent=title;$('confirmText').textContent=text;m.hidden=false;const done=v=>{m.hidden=true;$('confirmYes').onclick=null;$('confirmNo').onclick=null;resolve(v)};$('confirmYes').onclick=()=>done(true);$('confirmNo').onclick=()=>done(false)})}
function tab(name){document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('on',x.dataset.tab===name));document.querySelectorAll('.section').forEach(x=>x.classList.toggle('on',x.id===name));if(name==='media')loadMedia();if(name==='content'||name==='approval')loadContent();if(name==='metricool')fillScheduleTopics()}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
function setBusy(btn,busy,label){if(!btn)return;if(busy){btn.dataset.old=btn.textContent;btn.textContent=label||'Виконується…';btn.classList.add('busy');btn.disabled=true}else{btn.textContent=btn.dataset.old||btn.textContent;btn.classList.remove('busy');btn.disabled=false}}
function markDone(btn,label='Готово ✓'){if(!btn)return;const old=btn.textContent;btn.textContent=label;btn.classList.add('done');setTimeout(()=>{btn.textContent=old;btn.classList.remove('done')},1500)}
async function connect(){TOKEN=$('token').value.trim();localStorage.setItem('wq_admin_token',TOKEN);try{const h=await fetch('/api/health').then(r=>r.json());await Promise.all([loadTopics(),loadContent(),loadMedia()]);$('health').textContent='● online';$('health').className='online';$('sys').className='status ok';$('sys').textContent=`D1 ${h.db?'✓':'✗'} · R2 ${h.r2?'✓':'✗'} · Admin ${h.admin_secret?'✓':'✗'}`}catch(e){$('health').textContent='● error';$('health').className='offline';$('sys').className='status bad';$('sys').textContent=e.message}}
function statusPill(s){return `<span class="pill ${esc(s)}">${esc(STATUS_LABEL[s]||s||'—')}</span>`}
function statusSelect(x){const opts=['media_pending','media_ready','approved','scheduled','published','skipped'];return `<div class="statusbar"><select id="status_${x.id}">${opts.map(s=>`<option value="${s}" ${x.status===s?'selected':''}>${STATUS_LABEL[s]}</option>`).join('')}</select><button class="secondary" onclick="changeStatus('${x.id}')">Змінити статус</button></div>`}
function topicCard(x){const article=Number(x.published_pages||0),outputs=Number(x.outputs_count||0),media=Number(x.media_count||0),approved=Number(x.media_approved_count||0);return `<article class="topiccard status-${esc(x.status)}" data-search="${esc((x.id+' '+(x.canonical_title||'')+' '+(x.author_name||'')).toLowerCase())}" data-status="${esc(x.status)}"><div class="topicmain"><div class="topicid">${x.id}</div><div><h3>${esc(x.canonical_title||'Без назви')}</h3><div class="muted">${esc(x.author_name||'')} ${x.quote_type?'· '+esc(x.quote_type):''}</div></div>${statusPill(x.status)}</div><div class="progressline"><span>Статті ${article}/13</span><span>Outputs ${outputs}/88</span><span>Media ${media}</span><span>QA ${approved}</span></div><div class="actions"><button onclick="openItem('${x.id}')">Контент</button><button class="secondary" onclick="mediaTopic('${x.id}')">Додати media</button>${x.status==='scheduled'?`<button class="success" onclick="quickStatus('${x.id}','published')">✓ Опубліковано</button>`:''}${!['published','skipped'].includes(x.status)?`<button class="danger" onclick="quickStatus('${x.id}','skipped')">Пропустити</button>`:''}</div>${statusSelect(x)}</article>`}
async function loadTopics(){const j=await api('/api/admin/topics');TOPICS=j.items||[];renderTopics();$('kContent').textContent=TOPICS.length;$('kPending').textContent=TOPICS.filter(x=>x.status==='media_pending').length;$('kScheduled').textContent=TOPICS.filter(x=>x.status==='scheduled').length;$('kPublished').textContent=TOPICS.filter(x=>x.status==='published').length;fillMediaTopics();fillScheduleTopics()}
function renderTopics(){const q=($('topicSearch')?.value||'').trim().toLowerCase(),f=$('topicFilter')?.value||'';const rows=TOPICS.filter(x=>(!q||(`${x.id} ${x.canonical_title||''} ${x.author_name||''}`.toLowerCase().includes(q)))&&(!f||x.status===f));$('topicList').innerHTML=rows.map(topicCard).join('')||'<p class="muted">Нічого не знайдено.</p>'}
async function changeStatus(id){const s=$(`status_${id}`).value;await setTopicStatus(id,s)}
async function quickStatus(id,s){await setTopicStatus(id,s)}
async function setTopicStatus(id,status){const dangerous=['published','skipped','scheduled'].includes(status);if(dangerous){const ok=await modalConfirm(`Змінити ${id}?`,`${STATUS_LABEL[status]}. Цей статус буде записаний у D1 і залишиться в історії змін.`);if(!ok)return}try{await api(`/api/admin/topics/${id}/status`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({status,notes:'Manual status update from Admin dashboard'})});flash(`${id}: ${STATUS_LABEL[status]}`);await Promise.all([loadTopics(),loadContent()])}catch(e){alert(e.message)}}
function mediaTopic(id){tab('media');if($('matrixCid')){$('matrixCid').value=id;buildMatrix()}}
function fillMediaTopics(){if(!$('matrixCid'))return;const selected=$('matrixCid').value;$('matrixCid').innerHTML=TOPICS.filter(x=>!['published','skipped'].includes(x.status)).map(x=>`<option value="${x.id}" ${selected===x.id?'selected':''}>${x.id} — ${esc(x.canonical_title||'')}</option>`).join('')}
function buildMatrix(){const box=$('matrix');if(!box)return;box.innerHTML=SOCIAL_LANGS.map(l=>`<div class="matrixrow" id="row_${l}"><b>${l.toUpperCase()}</b>${fileBox(l,'video','Video')}${fileBox(l,'pinterest','Pinterest')}</div>`).join('');box.querySelectorAll('input[type=file]').forEach(inp=>inp.onchange=()=>fileChanged(inp));updateMatrixStatus()}
function fileBox(lang,kind,title){return `<label class="filebox" id="fb_${lang}_${kind}"><span class="filetitle">${title}</span><span class="filename">Натисни, щоб вибрати</span><input data-lang="${lang}" data-kind="${kind}" type="file" accept="${kind==='video'?'video/*':'image/*'}"></label>`}
function fileChanged(inp){const b=inp.closest('.filebox'),name=b.querySelector('.filename');if(inp.files?.[0]){b.classList.add('has-file');name.textContent=inp.files[0].name}else{b.classList.remove('has-file');name.textContent='Натисни, щоб вибрати'}const row=inp.closest('.matrixrow');row.classList.toggle('selected',!!row.querySelector('input[type=file][data-selected="1"]'));inp.dataset.selected=inp.files?.[0]?'1':'0';row.classList.toggle('selected',[...row.querySelectorAll('input')].some(x=>x.files?.[0]));updateMatrixStatus()}
function selectedFiles(){return [...document.querySelectorAll('#matrix input[type=file]')].filter(x=>x.files?.[0])}
function updateMatrixStatus(){const n=selectedFiles().length;$('matrixStatus').className='status '+(n?'ok':'');$('matrixStatus').textContent=n?`Вибрано ${n} файл(ів). Натисни «Завантажити вибрані файли».`:'Файли ще не вибрані.'}
async function uploadOne(cid,inp){const f=new FormData();f.append('file',inp.files[0]);f.append('content_item_id',cid);f.append('language_code',inp.dataset.lang);f.append('asset_type',inp.dataset.kind);return api('/api/admin/media',{method:'POST',body:f})}
async function uploadMatrix(){const cid=$('matrixCid').value,files=selectedFiles();if(!files.length)return flash('Спочатку вибери файли');const ok=await modalConfirm('Завантажити media?',`${cid}: буде завантажено ${files.length} файл(ів) у R2 та записано в D1.`);if(!ok)return;const btn=$('matrixUploadBtn');setBusy(btn,true,`Завантаження 0/${files.length}…`);let done=0;try{for(const inp of files){await uploadOne(cid,inp);done++;btn.textContent=`Завантаження ${done}/${files.length}…`;const b=inp.closest('.filebox');b.classList.remove('has-file');b.classList.add('uploaded');b.querySelector('.filename').textContent='Завантажено ✓';inp.value=''}$('matrixStatus').className='status ok';$('matrixStatus').textContent=`${cid}: ${done}/${files.length} файлів успішно завантажено.`;setBusy(btn,false);markDone(btn);await Promise.all([loadMedia(),loadTopics()])}catch(e){setBusy(btn,false);$('matrixStatus').className='status bad';$('matrixStatus').textContent=`Після ${done}/${files.length}: ${e.message}`}}
async function loadContent(){try{const j=await api('/api/admin/content');ITEMS=j.items||[];$('contentList').innerHTML=ITEMS.map(x=>`<button class="rowbtn" onclick="openItem('${x.id}')"><b>${x.id}</b><span>${esc(x.canonical_title||'')}</span><span>${statusPill(x.status)}</span><span>${x.approved_at?'✓ approved':esc(x.attribution_status||'')}</span></button>`).join('');$('approvalList').innerHTML=ITEMS.filter(x=>!['published','skipped'].includes(x.status)).map(x=>`<div class="approvalrow"><div><b>${x.id}</b><div>${esc(x.canonical_title||'')}</div><small>${esc(x.status||'')} · ${esc(x.attribution_status||'')}</small></div><div class="actions"><button class="secondary" onclick="openItem('${x.id}')">Review</button><button onclick="approve('${x.id}','approved')">Approve</button><button class="danger" onclick="approve('${x.id}','rejected')">Reject</button></div></div>`).join('')}catch(e){$('contentList').innerHTML=`<p>${esc(e.message)}</p>`}}
function field(label,id,value,cls=''){return `<label>${label}<div class="fieldhead"><button type="button" class="copy" onclick="copyField('${id}',this)">Копіювати</button></div><textarea id="${id}" class="${cls}">${esc(value||'')}</textarea></label>`}
async function copyField(id,btn){const el=$(id);if(!el)return;try{await navigator.clipboard.writeText(el.value||'')}catch{el.focus();el.select();document.execCommand('copy')}btn?.classList.add('copied');if(btn)btn.textContent='Скопійовано ✓';setTimeout(()=>{if(btn){btn.classList.remove('copied');btn.textContent='Копіювати'}},1200)}
async function openItem(id){CURRENT=id;try{const [j,p]=await Promise.all([api('/api/admin/content/'+id),api('/api/admin/production/'+id)]),x=j.item,latest={},omap={};(x.versions||[]).forEach(v=>{if(!latest[v.language_code]||Number(v.version)>Number(latest[v.language_code].version))latest[v.language_code]=v});(p.outputs||[]).forEach(o=>omap[`${o.language_code}:${o.output_key}`]=o.output_text||'');const rmap={};(p.readiness?.languages||[]).forEach(r=>rmap[r.language]=r);$('detail').innerHTML=`<div class="detailhead"><div><h2>${id}</h2><p class="quotelead">${esc(x.original_quote||x.canonical_title||'')}</p><p class="muted">${esc(x.author_name||'NO AUTHOR')} · ${esc(x.source_work||'')} · ${esc(x.attribution_status||'')}</p><div class="status ${p.readiness?.ready_for_metricool?'ok':'warn'}">Статус: <b>${esc(x.status)}</b> · Metricool: <b>${p.readiness?.ready_for_metricool?'READY':'ще не READY'}</b></div><div class="jumpbar">${SOCIAL_LANGS.map(l=>`<a href="#lang_${l}">${l.toUpperCase()}</a>`).join('')}</div></div><div class="actions"><button class="secondary" onclick="mediaTopic('${id}')">Додати media</button></div></div><div class="langgrid">${SOCIAL_LANGS.map(l=>{const v=latest[l]||{},r=rmap[l]||{};return `<article class="lang" id="lang_${l}"><header><b>${l.toUpperCase()}</b>${statusPill(v.status||'—')}</header>${field('Localized quote',`q_${l}`,v.adapted_text,'localized')}${field('Gemini / Veo prompt',`gp_${l}`,v.ai_prompt,'prompt')}${field('Voiceover',`vo_${l}`,v.voiceover_text||v.adapted_text)}${field('On-screen exact text',`os_${l}`,v.on_screen_text||v.adapted_text)}<hr>${OUTS.map(k=>field(LABELS[k],`out_${l}_${k}`,omap[`${l}:${k}`],k==='pinterest_prompt'?'prompt':'')).join('')}<div class="checklist"><small>Quote ${r.version?'✓':'✗'} · Video prompt ${r.video_prompt?'✓':'✗'} · Pinterest ${r.pinterest_prompt?'✓':'✗'} · URL ${r.article_url?'✓':'✗'} · copy ${r.copy||0}/8 · video ${r.video?'✓':'✗'} · image ${r.pinterest?'✓':'✗'} · QA ${r.media_qa?'✓':'✗'}</small></div></article>`}).join('')}</div>`;tab('content')}catch(e){$('detail').innerHTML=`<p>${esc(e.message)}</p>`}}
async function approve(id,status){if(status==='rejected'&&!await modalConfirm('Відхилити тему?',`${id}: approval буде змінено на rejected.`))return;try{await api(`/api/admin/content/${id}/approval`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({status})});flash(`${id}: ${status}`);await Promise.all([loadContent(),loadTopics()])}catch(e){alert(e.message)}}
function mediaKind(m){const t=String(m.asset_type||'').toLowerCase(),mime=String(m.mime_type||'').toLowerCase();if(t.includes('video')||mime.startsWith('video/'))return'video';if(t.includes('pinterest')||t.includes('image')||mime.startsWith('image/'))return'pinterest';return'other'}
async function loadMedia(){try{const j=await api('/api/admin/media'),a=j.items||[];$('mediaList').innerHTML=a.slice(0,180).map(m=>`<div class="mediarow"><b>${esc(m.content_item_id||'—')}</b><span>${esc(m.language_code||'—')}</span><span>${esc(mediaKind(m))}</span><span>${esc(m.original_filename||m.r2_key||'')}</span><span class="actions"><button class="secondary" onclick="qa('${m.id}','approved')">QA ✓</button><button class="danger" onclick="qa('${m.id}','rejected')">×</button></span></div>`).join('')||'<p class="muted">Media ще немає.</p>'}catch(e){$('mediaList').innerHTML=`<p>${esc(e.message)}</p>`}}
async function qa(id,status){if(status==='rejected'&&!await modalConfirm('Відхилити media?',`Файл ${id} буде позначено rejected.`))return;try{await api(`/api/admin/production/media/${id}/qa`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({status,notes:'Admin media QA'})});flash(`Media: ${status}`);await loadMedia()}catch(e){alert(e.message)}}
async function bulkQa(){const cid=$('matrixCid').value,box=$('bulkQaStatus');try{const p=await api('/api/admin/production/'+cid),latest={};for(const m of p.media||[]){const k=mediaKind(m);if(k==='other'||!SOCIAL_LANGS.includes(m.language_code))continue;const key=`${m.language_code}:${k}`;if(!latest[key]||String(m.created_at||'')>String(latest[key].created_at||''))latest[key]=m}const required=[];for(const l of SOCIAL_LANGS)required.push(`${l}:video`,`${l}:pinterest`);const missing=required.filter(k=>!latest[k]);if(missing.length)throw new Error('Бракує: '+missing.join(', '));if(!await modalConfirm('Підтвердити media QA?',`${cid}: підтвердити 16 актуальних файлів після твоєї перевірки?`))return;for(const k of required){const m=latest[k];if(m.qa_status!=='approved')await api(`/api/admin/production/media/${m.id}/qa`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({status:'approved',notes:'Bulk QA approved in Admin'})})}box.className='status ok';box.textContent=`${cid}: 16/16 media QA approved.`;await Promise.all([loadMedia(),loadTopics()])}catch(e){box.className='status bad';box.textContent=e.message}}
function fillScheduleTopics(){if(!$('scheduleTopic'))return;const selected=$('scheduleTopic').value;$('scheduleTopic').innerHTML=TOPICS.filter(x=>!['published','skipped'].includes(x.status)).map(x=>`<option value="${x.id}" ${selected===x.id?'selected':''}>${x.id} — ${esc(x.canonical_title||'')}</option>`).join('')}
async function checkSchedule(){const id=$('scheduleTopic').value;if(!id)return;try{const p=await api('/api/admin/production/'+id),r=p.readiness,issues=[];if(!r.source_ok)issues.push('source');if(r.approval?.status!=='approved')issues.push('approval');for(const l of r.languages||[]){if(!l.ready)issues.push(l.language.toUpperCase())}$('scheduleStatus').className='status '+(r.ready_for_metricool?'ok':'bad');$('scheduleStatus').textContent=r.ready_for_metricool?`${id}: READY для Metricool.`:`${id}: ще не READY — ${issues.join(', ')||'readiness gate'}`}catch(e){$('scheduleStatus').className='status bad';$('scheduleStatus').textContent=e.message}}
$('connectBtn').onclick=connect;$('refreshTopics').onclick=()=>Promise.all([loadTopics(),loadContent()]);$('refreshContent').onclick=loadContent;$('refreshMedia').onclick=loadMedia;$('matrixUploadBtn').onclick=uploadMatrix;$('bulkQaBtn').onclick=bulkQa;$('matrixCid').onchange=buildMatrix;$('topicSearch').oninput=renderTopics;$('topicFilter').onchange=renderTopics;$('scheduleBtn').onclick=checkSchedule;$('scheduleMode').onchange=()=>{$('manualTimeWrap').hidden=$('scheduleMode').value!=='manual'};
$('token').value=TOKEN;buildMatrix();if(TOKEN)connect();