(()=>{
const LANGS=['uk','ru','pl','en','sv','de','es','fr'], HEAD={uk:'UK',ru:'RU',pl:'PL',en:'EN',sv:'SV',de:'DE',es:'ES',fr:'FR'};
const COPY_KEYS={'Facebook':'facebook','Instagram':'instagram','Threads':'threads','TikTok':'tiktok','YouTube title':'youtube_title','YouTube description':'youtube_description','Pinterest title':'pinterest_title','Pinterest description':'pinterest_description','Website reflection':'website_reflection'};
const PACKAGES={
 WQ006:{prod:'/ops/prepared/WQ006-production-package.md',copy:'/ops/prepared/WQ006-platform-copy.md',meta:{quote:'Ми дорослішаємо двічі: спочатку — коли перестаємо потребувати батьків щодня, а потім — коли розуміємо, як сильно вони були нам потрібні.',title:'Ми дорослішаємо двічі — про батьків',quote_type:'adapted',category_slug:'parents-family',original_language:'uk'}},
 WQ011:{prod:'/ops/prepared/WQ011-nietzsche-production-package.md',copy:'/ops/prepared/WQ011-platform-copy.md',meta:{quote:'Was mich nicht umbringt, macht mich stärker.',title:'Was mich nicht umbringt, macht mich stärker — Friedrich Nietzsche',quote_type:'verbatim',category_slug:'philosophy-strength',original_language:'de',author_name:'Friedrich Nietzsche',author_source:'Projekt Gutenberg',source_work:'Götzen-Dämmerung oder Wie man mit dem Hammer philosophiert',source_url:'https://projekt-gutenberg.org/authors/friedrich-wilhelm-nietzsche/books/goetzen-daemmerung/chapter/3/',attribution_status:'verified'}}
};
function token(){return localStorage.getItem('wq_admin_token')||''}
async function api(path,opt={}){opt.headers={...(opt.headers||{}),Authorization:'Bearer '+token()};const r=await fetch(path,opt);let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||`${r.status} ${path}`);return j}
async function text(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${path}: ${r.status}`);return r.text()}
function section(md,start,end){const a=md.indexOf(start);if(a<0)return'';const b=end?md.indexOf(end,a+start.length):-1;return md.slice(a+start.length,b<0?md.length:b)}
function quotes(md){const s=section(md,md.includes('## Localized quote adaptations')?'## Localized quote adaptations':'## Localized quotes','---'),o={};for(const l of LANGS){const h=HEAD[l],re=new RegExp(`^- ${h}(?: original)?:\\s*(.+)$`,'m'),m=s.match(re);if(m)o[l]=m[1].trim()}return o}
function headed(md,sectionTitle,nextTitle){const s=section(md,sectionTitle,nextTitle),o={};for(const l of LANGS){const h=HEAD[l],re=new RegExp(`^### ${h}(?: — original)?\\s*\\n([\\s\\S]*?)(?=^### |^---|^## |$)`,'m'),m=s.match(re);if(m)o[l]=m[1].trim()}return o}
function copy(md){const o={};for(const l of LANGS){const h=HEAD[l],re=new RegExp(`^## ${h}\\s*\\n([\\s\\S]*?)(?=^## |$)`,'m'),m=md.match(re);o[l]={};if(!m)continue;for(const line of m[1].split('\n'))for(const [label,key] of Object.entries(COPY_KEYS))if(line.startsWith(label+':'))o[l][key]=line.slice(label.length+1).trim()}return o}
async function ensureItem(id,meta){let exists=true;try{await api('/api/admin/content/'+id)}catch{exists=false}const payload={...meta,content_id:id};if(exists)await api('/api/admin/content/'+id,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});else await api('/api/admin/content',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)})}
async function syncOne(id,p){const [prod,cp]=await Promise.all([text(p.prod),text(p.copy)]),qs=quotes(prod),vid=headed(prod,'## Gemini video prompts','## Pinterest image prompts'),pins=headed(prod,'## Pinterest image prompts','## Website'),copies=copy(cp);await ensureItem(id,p.meta);
 if(id==='WQ011'){const cur=await api('/api/admin/content/'+id);if(cur.item?.attribution_status!=='verified')await api(`/api/admin/content/${id}/evidence`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({source_type:'primary_text',source_title:'Götzen-Dämmerung — Sprüche und Pfeile, Aphorismus 8',source_url:p.meta.source_url,source_locator:'Sprüche und Pfeile, aphorism 8',original_text:p.meta.quote,original_language:'de',verified:true,verification_notes:'Verified against German primary-text edition hosted by Projekt Gutenberg.'})})}
 for(const l of LANGS){if(!qs[l]||!vid[l])throw new Error(`${id}: missing ${l} quote/prompt`);await api(`/api/admin/content/${id}/versions/${l}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({version:1,adapted_text:qs[l],voiceover_text:qs[l],on_screen_text:qs[l],ai_prompt:vid[l],status:'prompt_ready',language_check_status:'prepared',source_urls:id==='WQ011'?p.meta.source_url:null})});const outs={...(copies[l]||{}),pinterest_prompt:pins[l]||''};for(const [k,v] of Object.entries(outs))if(v)await api(`/api/admin/production/${id}/outputs/${l}/${k}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({output_text:v,status:'ready'})})}
 return true}
async function syncPrepared(){if(!token())throw new Error('Спочатку підключи ADMIN_TOKEN');const box=document.getElementById('preparedSyncStatus');if(box){box.className='status';box.textContent='Синхронізую WQ006 + WQ011: 8 мов, Gemini prompts, Pinterest prompts і тексти платформ…'}for(const [id,p] of Object.entries(PACKAGES))await syncOne(id,p);localStorage.setItem('wq_prepared_synced','2026-08-29-v2');if(box){box.className='status ok';box.textContent='Готово: WQ006 + WQ011 записані в D1 з 8 мовами, prompts і platform copy.'}setTimeout(()=>location.reload(),900)}
function history(){let a=[];try{a=JSON.parse(localStorage.getItem('wq_schedule_history')||'[]')}catch{}return a}
function renderHistory(){const el=document.getElementById('scheduleHistory');if(!el)return;const a=history();el.innerHTML=a.length?a.slice().reverse().map(x=>`<div class="scheduleRow"><b>${x.id}</b><span>${x.date}</span><span>${x.mode==='best'?'Найкращий час':x.time}</span><span>${x.status||'prepared'}</span></div>`).join(''):'<p class="muted">Ще немає підготовлених планувань.</p>'}
function install(){const topics=document.getElementById('topics');if(topics&&!document.getElementById('preparedSyncStatus')){const c=document.createElement('div');c.className='card';c.innerHTML='<div class="detailhead"><div><h2>Підготовлені пакети</h2><p class="muted">WQ006 Parents / Family + WQ011 Friedrich Nietzsche</p></div><button id="syncPreparedBtn">Синхронізувати з D1</button></div><div id="preparedSyncStatus" class="status">Перевіряю D1…</div>';topics.insertBefore(c,topics.children[1]||null);document.getElementById('syncPreparedBtn').onclick=()=>syncPrepared().catch(e=>{const b=document.getElementById('preparedSyncStatus');b.className='status bad';b.textContent=e.message})}
 const metric=document.getElementById('metricool');if(metric&&!document.getElementById('scheduleHistory')){const c=document.createElement('div');c.className='card';c.innerHTML='<h2>Черга планування</h2><div id="scheduleHistory"></div>';metric.appendChild(c);renderHistory()}
 const btn=document.getElementById('scheduleBtn');if(btn&&!btn.dataset.history){btn.dataset.history='1';btn.addEventListener('click',()=>setTimeout(()=>{try{const x=JSON.parse(localStorage.getItem('wq_schedule_request')||'null');if(!x)return;const a=history();if(!a.some(y=>y.created_at===x.created_at)){a.push({...x,status:'prepared'});localStorage.setItem('wq_schedule_history',JSON.stringify(a.slice(-50)));renderHistory()}}catch{}},250))}
 if(token()&&localStorage.getItem('wq_prepared_synced')!=='2026-08-29-v2')syncPrepared().catch(e=>{const b=document.getElementById('preparedSyncStatus');if(b){b.className='status bad';b.textContent='Автосинхронізація: '+e.message}});else{const b=document.getElementById('preparedSyncStatus');if(b){b.className='status ok';b.textContent='WQ006 + WQ011 вже синхронізовані. Натисни кнопку, щоб примусово оновити.'}}}
window.syncPreparedTopics=syncPrepared;window.addEventListener('load',()=>setTimeout(install,300));
})();