(()=>{
const LANGS=['uk','ru','pl','en','sv','de','es','fr'], HEAD={uk:'UK',ru:'RU',pl:'PL',en:'EN',sv:'SV',de:'DE',es:'ES',fr:'FR'};
const COPY_KEYS={'Facebook':'facebook','Instagram':'instagram','Threads':'threads','TikTok':'tiktok','YouTube title':'youtube_title','YouTube description':'youtube_description','Pinterest title':'pinterest_title','Pinterest description':'pinterest_description','Website reflection':'website_reflection'};
const RAW='https://raw.githubusercontent.com/oshtogryn/wisequotesworld-web/main/';
const PACKAGES={
 WQ006:{prod:'ops/prepared/WQ006-production-package.md',copy:'ops/prepared/WQ006-platform-copy.md',meta:{quote:'Ми дорослішаємо двічі: спочатку — коли перестаємо потребувати батьків щодня, а потім — коли розуміємо, як сильно вони були нам потрібні.',title:'Ми дорослішаємо двічі — про батьків',quote_type:'adapted',category_slug:'parents-family',original_language:'uk'}},
 WQ011:{prod:'ops/prepared/WQ011-nietzsche-production-package.md',copy:'ops/prepared/WQ011-platform-copy.md',meta:{quote:'Was mich nicht umbringt, macht mich stärker.',title:'Was mich nicht umbringt, macht mich stärker — Friedrich Nietzsche',quote_type:'verbatim',category_slug:'philosophy-strength',original_language:'de',author_name:'Friedrich Nietzsche',author_source:'Projekt Gutenberg',source_work:'Götzen-Dämmerung oder Wie man mit dem Hammer philosophiert',source_url:'https://projekt-gutenberg.org/authors/friedrich-wilhelm-nietzsche/books/goetzen-daemmerung/chapter/3/'}}
};
function token(){return localStorage.getItem('wq_admin_token')||''}
async function api(path,opt={}){opt.headers={...(opt.headers||{}),Authorization:'Bearer '+token()};const r=await fetch(path,opt);let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(`${opt.method||'GET'} ${path}: ${j.error||r.status}${j.detail?` — ${j.detail}`:''}`);return j}
async function text(path){let r=await fetch('/'+path,{cache:'no-store'});if(r.ok)return r.text();r=await fetch(RAW+path,{cache:'no-store',mode:'cors'});if(!r.ok)throw new Error(`GET package ${path}: ${r.status}`);return r.text()}
function section(md,start,end){const a=md.indexOf(start);if(a<0)return'';const from=a+start.length,b=end?md.indexOf(end,from):-1;return md.slice(from,b<0?md.length:b)}
function quotes(md){const s=section(md,md.includes('## Localized quote adaptations')?'## Localized quote adaptations':'## Localized quotes','---'),o={};for(const l of LANGS){const h=HEAD[l],m=s.match(new RegExp(`(?:^|\\n)- ${h}(?: original)?:\\s*([^\\n]+)`));if(m)o[l]=m[1].trim()}return o}
function headed(md,sectionTitle,nextTitle){const s=section(md,sectionTitle,nextTitle),o={};for(const l of LANGS){const h=HEAD[l],m=s.match(new RegExp(`(?:^|\\n)### ${h}(?: — original)?\\s*\\n([\\s\\S]*?)(?=\\n### |\\n---|\\n## |$)`));if(m)o[l]=m[1].trim()}return o}
function copy(md){const o={};for(const l of LANGS){const h=HEAD[l],m=md.match(new RegExp(`(?:^|\\n)## ${h}\\s*\\n([\\s\\S]*?)(?=\\n## |$)`));o[l]={};if(!m)continue;for(const line of m[1].split('\n'))for(const [label,key] of Object.entries(COPY_KEYS))if(line.startsWith(label+':'))o[l][key]=line.slice(label.length+1).trim()}return o}
function normalizeVideoPrompt(prompt,quote){return `${String(prompt||'').trim()}\n\nCRITICAL FINAL OVERRIDE — THIS SECTION HAS PRIORITY OVER ANY EARLIER BRANDING INSTRUCTION:\n1. The finished Gemini video MUST render the exact approved quote text on screen: “${quote}”. Do not translate, paraphrase, autocorrect, alter punctuation, omit words, add words or invent letters.\n2. The finished video MUST contain native-language voiceover speaking the same quote exactly once. Preserve the first and last spoken word completely. Leave enough audio headroom and tail so no syllable is clipped.\n3. If the quote needs two text blocks, show only one complete block at a time; remove block 1 fully, leave a brief clean gap, then show block 2. No overlap, no typewriter, no word-by-word animation, no automatic subtitles.\n4. Use the full available duration up to 10 seconds if needed. Keep the narration natural; never rush it unnaturally.\n5. ABSOLUTELY NO Wise Quotes World logo, brand mark, branding text or generated logo of any kind. The user adds the correct logo later in CapCut.\n6. NO third-party logos, watermarks, random text, fake UI, unrelated signs or extra captions.\n7. FINAL QA BEFORE OUTPUT: exact spelling and punctuation; every quote word fully visible; first and last spoken words complete; zero generated logo/branding.`}
function packageQa(id,qs,vid,pins,copies){for(const l of LANGS){const missing=[];if(!qs[l])missing.push('quote');if(!vid[l])missing.push('gemini');if(!pins[l])missing.push('pinterest_prompt');for(const key of Object.values(COPY_KEYS))if(!copies[l]?.[key])missing.push(key);if(missing.length)throw new Error(`${id} package QA failed for ${l}: missing ${missing.join(', ')}`)}}
async function maybeResetStale(id,meta){try{const cur=await api('/api/admin/content/'+id);if(id==='WQ006'&&String(cur.item?.original_quote||'').trim()!==meta.quote){await api('/api/admin/prepared/reset/WQ006',{method:'POST'});return true}return false}catch(e){if(String(e.message).includes(': not found'))return false;throw e}}
async function ensureItem(id,meta){let exists=true;try{await api('/api/admin/content/'+id)}catch(e){if(!String(e.message).includes(': not found'))throw e;exists=false}const payload={...meta,content_id:id};if(exists)await api('/api/admin/content/'+id,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});else await api('/api/admin/content',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)})}
async function syncOne(id,p){const [prod,cp]=await Promise.all([text(p.prod),text(p.copy)]),qs=quotes(prod),vid=headed(prod,'## Gemini video prompts','## Pinterest image prompts'),pins=headed(prod,'## Pinterest image prompts','## Website'),copies=copy(cp);packageQa(id,qs,vid,pins,copies);await maybeResetStale(id,p.meta);await ensureItem(id,p.meta);if(id==='WQ011'){const cur=await api('/api/admin/content/'+id);if(cur.item?.attribution_status!=='verified')await api(`/api/admin/content/${id}/evidence`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({source_type:'primary_text',source_title:'Götzen-Dämmerung — Sprüche und Pfeile, Aphorismus 8',source_url:p.meta.source_url,source_locator:'Sprüche und Pfeile, aphorism 8',original_text:p.meta.quote,original_language:'de',verified:true,verification_notes:'Verified against German primary-text edition hosted by Projekt Gutenberg.'})})}for(const l of LANGS){const finalPrompt=normalizeVideoPrompt(vid[l],qs[l]);await api(`/api/admin/content/${id}/versions/${l}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({version:1,adapted_text:qs[l],voiceover_text:qs[l],on_screen_text:qs[l],ai_prompt:finalPrompt,status:'prompt_ready',language_check_status:'prepared',source_urls:id==='WQ011'?p.meta.source_url:null})});const outs={...(copies[l]||{}),pinterest_prompt:pins[l]};for(const [k,v] of Object.entries(outs))await api(`/api/admin/production/${id}/outputs/${l}/${k}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({output_text:v,status:'ready'})})}const check=await api('/api/admin/content/'+id),prodCheck=await api('/api/admin/production/'+id);const latest={};for(const v of check.item.versions||[])if(!latest[v.language_code]||Number(v.version)>Number(latest[v.language_code].version))latest[v.language_code]=v;const outs=prodCheck.outputs||[];const result={id,title:check.item.canonical_title,quote:check.item.original_quote,languages:Object.keys(latest).length,gemini:LANGS.filter(l=>String(latest[l]?.ai_prompt||'').includes('ABSOLUTELY NO Wise Quotes World logo')).length,pinterest:LANGS.filter(l=>outs.some(o=>o.language_code===l&&o.output_key==='pinterest_prompt'&&String(o.output_text||'').trim())).length,platform_copy:LANGS.filter(l=>['facebook','instagram','threads','tiktok','youtube_title','youtube_description','pinterest_title','pinterest_description'].every(k=>outs.some(o=>o.language_code===l&&o.output_key===k&&String(o.output_text||'').trim()))).length};if(result.languages!==8||result.gemini!==8||result.pinterest!==8||result.platform_copy!==8)throw new Error(`${id} D1 readback QA failed: ${JSON.stringify(result)}`);return result}
async function syncPrepared(){if(!token())throw new Error('Спочатку підключи ADMIN_TOKEN');const box=document.getElementById('preparedSyncStatus');if(box){box.className='status';box.textContent='Sync prompts v6: exact text + exact voiceover + NO AI LOGO → D1 readback QA…'}const results=[];for(const [id,p] of Object.entries(PACKAGES))results.push(await syncOne(id,p));localStorage.setItem('wq_prepared_synced','2026-08-29-v6');if(box){box.className='status ok';box.innerHTML=`QA PASS ✓<br>${results.map(r=>`${r.id}: 8/8 мов · Gemini prompt rule 8/8 · Pinterest 8/8 · social copy 8/8`).join('<br>')}`}setTimeout(()=>location.reload(),1800)}
function history(){let a=[];try{a=JSON.parse(localStorage.getItem('wq_schedule_history')||'[]')}catch{}return a}
function renderHistory(){const el=document.getElementById('scheduleHistory');if(!el)return;const a=history();el.innerHTML=a.length?a.slice().reverse().map(x=>`<div class="scheduleRow"><b>${x.id}</b><span>${x.date}</span><span>${x.mode==='best'?'Найкращий час':x.time}</span><span>${x.status||'prepared'}</span></div>`).join(''):'<p class="muted">Ще немає підготовлених планувань.</p>'}
function install(){const topics=document.getElementById('topics');if(topics&&!document.getElementById('preparedSyncStatus')){const c=document.createElement('div');c.className='card';c.innerHTML='<div class="detailhead"><div><h2>Підготовлені пакети</h2><p class="muted">WQ006 Parents / Family + WQ011 Friedrich Nietzsche</p></div><button id="syncPreparedBtn">Синхронізувати з D1</button></div><div id="preparedSyncStatus" class="status">Готово до перевіреної синхронізації.</div>';topics.insertBefore(c,topics.children[1]||null);document.getElementById('syncPreparedBtn').onclick=()=>syncPrepared().catch(e=>{const b=document.getElementById('preparedSyncStatus');b.className='status bad';b.textContent=e.message})}const metric=document.getElementById('metricool');if(metric&&!document.getElementById('scheduleHistory')){const c=document.createElement('div');c.className='card';c.innerHTML='<h2>Черга планування</h2><div id="scheduleHistory"></div>';metric.appendChild(c);renderHistory()}const btn=document.getElementById('scheduleBtn');if(btn&&!btn.dataset.history){btn.dataset.history='1';btn.addEventListener('click',()=>setTimeout(()=>{try{const x=JSON.parse(localStorage.getItem('wq_schedule_request')||'null');if(!x)return;const a=history();if(!a.some(y=>y.created_at===x.created_at)){a.push({...x,status:'prepared'});localStorage.setItem('wq_schedule_history',JSON.stringify(a.slice(-50)));renderHistory()}}catch{}},250))}if(token()&&localStorage.getItem('wq_prepared_synced')!=='2026-08-29-v6')syncPrepared().catch(e=>{const b=document.getElementById('preparedSyncStatus');if(b){b.className='status bad';b.textContent=e.message}});else{const b=document.getElementById('preparedSyncStatus');if(b){b.className='status ok';b.textContent='Пакети синхронізовані за video rule v4.1 та пройшли D1 readback QA.'}}}
window.syncPreparedTopics=syncPrepared;window.addEventListener('load',()=>setTimeout(install,300));
})();