const SOCIAL_HOSTS=[
 ['facebook','facebook.com'],['instagram','instagram.com'],['threads','threads.net'],['threads','threads.com'],
 ['tiktok','tiktok.com'],['youtube','youtube.com'],['youtube','youtu.be'],['pinterest','pinterest.com'],
 ['telegram','t.me'],['telegram','telegram.me'],['x','x.com'],['twitter','twitter.com']
];

export function analyticsEventsScript(locale){
 const l=JSON.stringify(String(locale||''));
 const hosts=JSON.stringify(SOCIAL_HOSTS);
 return `<script id="wqw-analytics-v1">(()=>{const locale=${l},socialHosts=${hosts};let newsletterTracked=false;function send(name,params={}){try{const p={locale,source_path:location.pathname,...params};if(typeof window.gtag==='function'){window.gtag('event',name,p);return}window.dataLayer=window.dataLayer||[];function q(){window.dataLayer.push(arguments)}q('event',name,p)}catch{}}function socialNetwork(host){host=String(host||'').toLowerCase().replace(/^www\\./,'');for(const [name,domain] of socialHosts){if(host===domain||host.endsWith('.'+domain))return name}return null}document.addEventListener('click',e=>{const a=e.target&&e.target.closest?e.target.closest('a[href]'):null;if(!a)return;let d;try{d=new URL(a.href,location.href)}catch{return}const same=d.origin===location.origin,src=location.pathname,dst=d.pathname;const startRe=new RegExp('^/'+locale+'/start/?$'),quoteRe=new RegExp('^/'+locale+'/quotes/[^/]+/?$'),authorRe=new RegExp('^/'+locale+'/author/[^/]+/?$'),topicRe=new RegExp('^/'+locale+'/category/[^/]+/?$');if(startRe.test(src)&&same&&quoteRe.test(dst))send('start_to_article',{destination_path:dst});const network=!same?socialNetwork(d.hostname):null;if(network)send('social_click',{network,destination_host:d.hostname});if(same&&authorRe.test(dst))send('author_hub_click',{destination_path:dst});if(same&&topicRe.test(dst))send('topic_hub_click',{destination_path:dst});if(same&&quoteRe.test(src)&&quoteRe.test(dst)&&src!==dst)send('related_quote_click',{destination_path:dst})},true);const nativeFetch=window.fetch;if(typeof nativeFetch==='function'){window.fetch=async function(...args){const response=await nativeFetch.apply(this,args);try{const input=args[0],raw=typeof input==='string'?input:input&&input.url;if(raw){const u=new URL(raw,location.href);if(!newsletterTracked&&u.pathname==='/api/newsletter/subscribe'&&response.ok){response.clone().json().then(d=>{if(d&&d.ok&&!newsletterTracked){newsletterTracked=true;send('newsletter_signup')}}).catch(()=>{})}}}catch{}return response}}})();</script>`;
}
