import {publishWebsite} from './publication_engine.js';
import {cancelWebsitePublication,ensureWebsiteSchedule} from './website_schedule.js';

const PROJECT='wisequotesworld';
const WEB=['uk','ru','pl','en','sv','de','es','fr','it','pt','id','tr','ar'];
const SOCIAL=['uk','ru','pl','en','sv','de','es','fr'];
const TS=()=>new Date().toISOString();

const LABEL={
 uk:{meaning:'Сенс і контекст',source:'Джерело',pdesc:'Ця перевірена цитата запрошує подивитися на думку автора в її контексті та співвіднести її з власним досвідом.',vdesc:'Відеоверсія цієї перевіреної цитати з природною українською адаптацією. Повний контекст і роздуми — у статті.',thread:'Іноді одна точна думка корисніша за десяток порад. Важливо не просто погодитися з цитатою, а перевірити її на власному досвіді.'},
 ru:{meaning:'Смысл и контекст',source:'Источник',pdesc:'Эта проверенная цитата помогает увидеть мысль автора в её контексте и соотнести её с собственным опытом.',vdesc:'Видеоверсия проверенной цитаты с естественной русской адаптацией. Полный контекст и размышление — в статье.',thread:'Иногда одна точная мысль полезнее десятка советов. Важно не просто согласиться с цитатой, а проверить её на собственном опыте.'},
 pl:{meaning:'Znaczenie i kontekst',source:'Źródło',pdesc:'Ten zweryfikowany cytat zachęca, by odczytać myśl autora w jej kontekście i odnieść ją do własnego doświadczenia.',vdesc:'Wersja wideo zweryfikowanego cytatu w naturalnej polskiej adaptacji. Pełny kontekst i refleksja znajdują się w artykule.',thread:'Czasem jedna trafna myśl jest więcej warta niż dziesięć porad. Nie chodzi tylko o zgodę z cytatem, lecz o sprawdzenie go we własnym doświadczeniu.'},
 en:{meaning:'Meaning and context',source:'Source',pdesc:'This verified quotation invites a closer look at the author’s idea in context and asks how it holds up against lived experience.',vdesc:'A video version of the verified quotation in natural English. The full context and reflection are available in the article.',thread:'Sometimes one precise idea is more useful than ten pieces of advice. The point is not merely to agree with a quotation, but to test it against experience.'},
 sv:{meaning:'Betydelse och sammanhang',source:'Källa',pdesc:'Det här verifierade citatet uppmuntrar till att läsa författarens tanke i sitt sammanhang och pröva den mot den egna erfarenheten.',vdesc:'En videoversion av det verifierade citatet i naturlig svensk språkdräkt. Hela sammanhanget och reflektionen finns i artikeln.',thread:'Ibland är en träffsäker tanke mer användbar än tio råd. Det viktiga är inte bara att hålla med citatet, utan att pröva det mot den egna erfarenheten.'},
 de:{meaning:'Bedeutung und Kontext',source:'Quelle',pdesc:'Dieses belegte Zitat lädt dazu ein, den Gedanken des Autors im Zusammenhang zu lesen und an der eigenen Erfahrung zu prüfen.',vdesc:'Videoversion des belegten Zitats in natürlicher deutscher Fassung. Den vollständigen Kontext und die Reflexion gibt es im Artikel.',thread:'Manchmal ist ein präziser Gedanke hilfreicher als zehn Ratschläge. Entscheidend ist nicht nur, dem Zitat zuzustimmen, sondern es an der eigenen Erfahrung zu prüfen.'},
 es:{meaning:'Significado y contexto',source:'Fuente',pdesc:'Esta cita verificada invita a leer la idea del autor en su contexto y a contrastarla con la propia experiencia.',vdesc:'Versión en vídeo de la cita verificada con una adaptación natural al español. El contexto completo y la reflexión están en el artículo.',thread:'A veces una idea precisa resulta más útil que diez consejos. No se trata solo de estar de acuerdo con una cita, sino de contrastarla con la propia experiencia.'},
 fr:{meaning:'Sens et contexte',source:'Source',pdesc:'Cette citation vérifiée invite à replacer la pensée de l’auteur dans son contexte et à la confronter à notre propre expérience.',vdesc:'Version vidéo de cette citation vérifiée dans une adaptation française naturelle. Le contexte complet et la réflexion sont dans l’article.',thread:'Parfois, une pensée juste est plus utile que dix conseils. L’essentiel n’est pas seulement d’approuver une citation, mais de l’éprouver à la lumière de sa propre expérience.'},
 it:{meaning:'Significato e contesto',source:'Fonte'}, pt:{meaning:'Significado e contexto',source:'Fonte'}, id:{meaning:'Makna dan konteks',source:'Sumber'}, tr:{meaning:'Anlam ve bağlam',source:'Kaynak'}, ar:{meaning:'المعنى والسياق',source:'المصدر'}
};

function words(v){return String(v||'').trim().split(/\s+/u).filter(Boolean).length}
function quoteOnly(q){return String(q||'').replace(/\s+[—-]\s+[^—]+$/u,'').trim()}
function authorFrom(q,fallback){const m=String(q||'').match(/[—-]\s*([^—]+)$/u);return m?m[1].trim():fallback}

const ARTICLE={
 uk:(q,a,w)=>`${q}\n\nЦю цитату варто читати не як окремий мотиваційний слоган, а як частину ширшої думки ${a}. Її джерельний контекст — ${w||'перевірене першоджерело'} — допомагає уникнути спрощень і побачити, про що насправді говорить автор. Добра цитата не замінює аргумент, але може точно назвати те, що ми вже відчуваємо або лише починаємо усвідомлювати.\n\nПрактична цінність такої думки з’являється тоді, коли ми не зупиняємося на красивому формулюванні. Варто запитати, яке припущення стоїть за цими словами, де воно справді працює, а де потребує уточнення. Так цитата перестає бути прикрасою і стає способом уважніше дивитися на власні рішення, звички, страхи, надії чи спосіб мислення.\n\nУ повсякденному житті достатньо одного конкретного прикладу. Згадайте ситуацію, у якій ця думка могла б змінити ваш наступний крок або хоча б спосіб подивитися на проблему. Не обов’язково погоджуватися з автором у всьому. Значно корисніше чесно перевірити тезу на власному досвіді й помітити, що вона прояснює.\n\nСаме тому ми зберігаємо перевірене авторство, першоджерело й природну українську адаптацію. Сенс не в тому, щоб повторювати відому фразу частіше, а в тому, щоб зрозуміти її точніше й використати там, де вона справді допомагає мислити ясніше.`,
 ru:(q,a,w)=>`${q}\n\nЭту цитату полезно читать не как отдельный мотивационный лозунг, а как часть более широкой мысли ${a}. Контекст источника — ${w||'проверенный первоисточник'} — помогает избежать упрощений и точнее увидеть, что именно утверждает автор. Хорошая цитата не заменяет аргумент, но иногда очень точно называет то, что мы уже чувствуем или только начинаем понимать.\n\nПрактическая ценность появляется тогда, когда мы не останавливаемся на красивой формулировке. Стоит спросить, какое предположение стоит за этими словами, где оно действительно работает и где требует уточнения. Тогда цитата перестаёт быть украшением и становится способом внимательнее смотреть на собственные решения, привычки, страхи, надежды и образ мышления.\n\nВ обычной жизни достаточно одного конкретного примера. Вспомните ситуацию, в которой эта мысль могла бы изменить ваш следующий шаг или хотя бы взгляд на проблему. Необязательно соглашаться с автором во всём. Намного полезнее честно проверить тезис на собственном опыте и заметить, что именно она проясняет.\n\nПоэтому мы сохраняем проверенное авторство, источник и естественную русскую адаптацию. Смысл не в том, чтобы чаще повторять известную фразу, а в том, чтобы точнее её понять и использовать там, где она действительно помогает мыслить яснее.`,
 pl:(q,a,w)=>`${q}\n\nTen cytat warto czytać nie jako samodzielne hasło motywacyjne, lecz jako część szerszej myśli ${a}. Kontekst źródłowy — ${w||'zweryfikowane źródło'} — pomaga uniknąć uproszczeń i lepiej zrozumieć, co autor rzeczywiście mówi. Dobry cytat nie zastępuje argumentu, ale potrafi trafnie nazwać coś, co już czujemy albo dopiero zaczynamy rozumieć.\n\nJego praktyczna wartość pojawia się wtedy, gdy nie zatrzymujemy się na efektownym brzmieniu. Warto zapytać, jakie założenie kryje się za tymi słowami, gdzie rzeczywiście się sprawdza, a gdzie wymaga doprecyzowania. Wtedy cytat przestaje być ozdobą i staje się sposobem uważniejszego patrzenia na własne decyzje, nawyki, lęki, nadzieje i sposób myślenia.\n\nW codziennym życiu wystarczy jeden konkretny przykład. Pomyśl o sytuacji, w której ta myśl mogłaby zmienić twój następny krok albo przynajmniej sposób patrzenia na problem. Nie trzeba zgadzać się z autorem we wszystkim. Znacznie cenniejsze jest uczciwe sprawdzenie jego tezy we własnym doświadczeniu i zauważenie, co naprawdę wyjaśnia.\n\nDlatego zachowujemy zweryfikowane autorstwo, źródło i naturalną polską adaptację. Nie chodzi o częstsze powtarzanie znanego zdania, lecz o dokładniejsze zrozumienie go i użycie tam, gdzie rzeczywiście pomaga myśleć jaśniej.`,
 en:(q,a,w)=>`${q}\n\nThis quotation is most useful when it is read as part of ${a}’s wider thought rather than as an isolated motivational slogan. Its source context — ${w||'the verified source'} — helps prevent oversimplification and makes it easier to see what the author is actually claiming. A strong quotation does not replace an argument, but it can name something precisely enough to sharpen our attention.\n\nIts practical value begins when we move beyond admiring the wording. Ask what assumption sits behind the sentence, where it genuinely holds, and where it needs qualification. At that point the quotation stops being decoration and becomes a way to examine decisions, habits, fears, hopes, and patterns of thought with greater care.\n\nIn everyday life, one concrete example is enough. Think of a situation in which this idea could alter your next step, or at least change the way you frame the problem. You do not have to agree with the author about everything. It is more useful to test one claim honestly against experience and notice what it clarifies.\n\nThat is why we preserve verified attribution, the source, and a natural localized rendering. The point is not to repeat a famous sentence more often, but to understand it more accurately and use it where it genuinely helps us think more clearly.`,
 sv:(q,a,w)=>`${q}\n\nDet här citatet blir mest givande när det läses som en del av ${a}s större tankevärld och inte som en fristående motivationsfras. Källsammanhanget — ${w||'den verifierade källan'} — hjälper oss att undvika förenklingar och att se vad författaren faktiskt säger. Ett starkt citat ersätter inte ett argument, men det kan formulera något så precist att vår uppmärksamhet skärps.\n\nDet praktiska värdet börjar när vi går vidare från själva formuleringen. Fråga vilket antagande som finns bakom meningen, var det verkligen håller och var det behöver nyanseras. Då slutar citatet att vara dekoration och blir ett sätt att granska beslut, vanor, rädslor, förhoppningar och tankemönster mer noggrant.\n\nI vardagen räcker ett konkret exempel. Tänk på en situation där den här tanken skulle kunna påverka ditt nästa steg eller åtminstone förändra hur du beskriver problemet. Du behöver inte hålla med författaren om allt. Det är mer värdefullt att ärligt pröva en tes mot erfarenheten och se vad den faktiskt klargör.\n\nDärför bevarar vi verifierad attribution, källa och en naturlig svensk språkdräkt. Poängen är inte att upprepa en känd mening oftare, utan att förstå den mer exakt och använda den där den faktiskt hjälper oss att tänka klarare.`,
 de:(q,a,w)=>`${q}\n\nDieses Zitat ist am hilfreichsten, wenn man es als Teil des größeren Denkzusammenhangs von ${a} liest und nicht als losgelösten Motivationsspruch. Der Quellenkontext — ${w||'die geprüfte Quelle'} — schützt vor Vereinfachungen und macht deutlicher, was der Autor tatsächlich behauptet. Ein starkes Zitat ersetzt kein Argument, kann aber etwas so präzise benennen, dass wir genauer hinsehen.\n\nSein praktischer Wert beginnt dort, wo wir nicht bei der schönen Formulierung stehen bleiben. Fragen Sie, welche Annahme hinter dem Satz steht, wo sie trägt und wo sie differenziert werden muss. Dann wird das Zitat vom Schmuckstück zu einem Werkzeug, mit dem sich Entscheidungen, Gewohnheiten, Ängste, Hoffnungen und Denkmuster bewusster betrachten lassen.\n\nIm Alltag genügt ein konkretes Beispiel. Denken Sie an eine Situation, in der dieser Gedanke den nächsten Schritt verändern oder zumindest den Blick auf das Problem verschieben könnte. Man muss dem Autor nicht in allem zustimmen. Wertvoller ist es, eine Aussage ehrlich an der eigenen Erfahrung zu prüfen und zu sehen, was sie tatsächlich klärt.\n\nDeshalb bewahren wir belegte Zuschreibung, Quelle und eine natürliche deutsche Fassung. Es geht nicht darum, einen berühmten Satz häufiger zu wiederholen, sondern ihn genauer zu verstehen und dort zu nutzen, wo er wirklich hilft, klarer zu denken.`,
 es:(q,a,w)=>`${q}\n\nEsta cita resulta más valiosa cuando se lee como parte del pensamiento más amplio de ${a} y no como un eslogan motivacional aislado. El contexto de la fuente — ${w||'la fuente verificada'} — ayuda a evitar simplificaciones y a entender con mayor precisión qué afirma realmente el autor. Una buena cita no sustituye un argumento, pero puede formular una idea con suficiente precisión como para afinar nuestra atención.\n\nSu valor práctico comienza cuando vamos más allá de admirar la frase. Conviene preguntarse qué supuesto hay detrás, dónde se sostiene de verdad y dónde necesita matices. Entonces la cita deja de ser un adorno y se convierte en una forma de observar con más cuidado nuestras decisiones, hábitos, miedos, esperanzas y maneras de pensar.\n\nEn la vida cotidiana basta con un ejemplo concreto. Piensa en una situación en la que esta idea pudiera cambiar tu siguiente paso o, al menos, la manera de plantear el problema. No hace falta estar de acuerdo con el autor en todo. Es más útil contrastar honestamente una afirmación con la propia experiencia y observar qué consigue aclarar.\n\nPor eso conservamos la atribución verificada, la fuente y una adaptación natural al español. La cuestión no es repetir una frase célebre más veces, sino comprenderla con mayor precisión y utilizarla allí donde realmente ayuda a pensar con más claridad.`,
 fr:(q,a,w)=>`${q}\n\nCette citation prend tout son intérêt lorsqu’on la lit comme une partie de la pensée plus large de ${a}, et non comme un slogan de motivation isolé. Le contexte de la source — ${w||'la source vérifiée'} — permet d’éviter les simplifications et de mieux comprendre ce que l’auteur affirme réellement. Une bonne citation ne remplace pas un argument, mais elle peut formuler une idée avec assez de précision pour aiguiser notre attention.\n\nSa valeur pratique apparaît lorsque nous allons au-delà de la belle formule. Il faut se demander quelle hypothèse se cache derrière la phrase, où elle tient vraiment et où elle demande des nuances. Le citation cesse alors d’être décorative et devient une manière d’examiner plus attentivement nos décisions, nos habitudes, nos peurs, nos espoirs et nos façons de penser.\n\nDans la vie quotidienne, un exemple concret suffit. Pensez à une situation dans laquelle cette idée pourrait modifier votre prochaine action ou, au moins, votre manière de formuler le problème. Il n’est pas nécessaire d’être d’accord avec l’auteur sur tout. Il est plus utile de confronter honnêtement une affirmation à l’expérience et d’observer ce qu’elle éclaire réellement.\n\nC’est pourquoi nous conservons l’attribution vérifiée, la source et une adaptation française naturelle. Le but n’est pas de répéter plus souvent une phrase célèbre, mais de la comprendre plus précisément et de l’utiliser là où elle nous aide réellement à penser plus clairement.`,
 it:(q,a,w)=>`${q}\n\nQuesta citazione è più utile quando viene letta come parte del pensiero più ampio di ${a}, non come uno slogan motivazionale isolato. Il contesto della fonte — ${w||'la fonte verificata'} — aiuta a evitare semplificazioni e a capire con maggiore precisione ciò che l’autore sta realmente affermando. Una buona citazione non sostituisce un argomento, ma può formulare un’idea con sufficiente precisione da rendere più attenta la nostra lettura della realtà.\n\nIl suo valore pratico comincia quando andiamo oltre l’effetto della frase. Vale la pena chiedersi quale presupposto contenga, dove regga davvero e dove richieda sfumature. A quel punto la citazione smette di essere decorazione e diventa uno strumento per osservare con più attenzione decisioni, abitudini, paure, speranze e schemi di pensiero.\n\nNella vita quotidiana basta un esempio concreto. Pensa a una situazione in cui questa idea potrebbe cambiare il prossimo passo o almeno il modo di inquadrare il problema. Non è necessario essere d’accordo con l’autore su tutto. È più utile mettere onestamente alla prova una tesi attraverso l’esperienza e notare che cosa riesce davvero a chiarire.\n\nPer questo conserviamo attribuzione verificata, fonte e un adattamento italiano naturale. Lo scopo non è ripetere più spesso una frase famosa, ma comprenderla con maggiore precisione e usarla dove aiuta davvero a pensare con più chiarezza.`,
 pt:(q,a,w)=>`${q}\n\nEsta citação ganha mais valor quando é lida como parte do pensamento mais amplo de ${a}, e não como um slogan motivacional isolado. O contexto da fonte — ${w||'a fonte verificada'} — ajuda a evitar simplificações e a entender com mais precisão o que o autor realmente afirma. Uma boa citação não substitui um argumento, mas pode formular uma ideia com precisão suficiente para tornar nosso olhar mais atento.\n\nSeu valor prático começa quando vamos além do efeito da frase. Vale perguntar qual pressuposto existe por trás dela, onde ele realmente se sustenta e onde precisa de nuance. Nesse ponto, a citação deixa de ser enfeite e passa a servir como ferramenta para observar com mais cuidado decisões, hábitos, medos, esperanças e formas de pensar.\n\nNa vida cotidiana, basta um exemplo concreto. Pense em uma situação em que essa ideia poderia mudar seu próximo passo ou, pelo menos, a maneira de enxergar o problema. Não é preciso concordar com o autor em tudo. É mais útil testar uma afirmação honestamente à luz da própria experiência e perceber o que ela realmente esclarece.\n\nPor isso, preservamos a atribuição verificada, a fonte e uma adaptação natural ao português do Brasil. O objetivo não é repetir uma frase famosa com mais frequência, mas compreendê-la com maior precisão e usá-la onde ela realmente ajuda a pensar com mais clareza.`,
 id:(q,a,w)=>`${q}\n\nKutipan ini paling bermanfaat bila dibaca sebagai bagian dari pemikiran ${a} yang lebih luas, bukan sebagai slogan motivasi yang berdiri sendiri. Konteks sumber — ${w||'sumber yang telah diverifikasi'} — membantu menghindari penyederhanaan dan membuat kita lebih tepat memahami apa yang sebenarnya dikatakan penulis. Kutipan yang baik tidak menggantikan argumen, tetapi dapat merumuskan suatu gagasan dengan cukup tajam untuk menuntun perhatian kita.\n\nNilai praktisnya muncul ketika kita melampaui keindahan kalimat. Tanyakan asumsi apa yang berada di baliknya, di mana gagasan itu benar-benar berlaku, dan di mana ia membutuhkan nuansa. Pada titik itu, kutipan berhenti menjadi hiasan dan menjadi alat untuk melihat keputusan, kebiasaan, ketakutan, harapan, serta pola pikir dengan lebih cermat.\n\nDalam kehidupan sehari-hari, satu contoh konkret sudah cukup. Pikirkan situasi ketika gagasan ini dapat mengubah langkah berikutnya atau setidaknya cara kita membingkai masalah. Kita tidak harus setuju dengan penulis dalam segala hal. Lebih berguna menguji satu pernyataan secara jujur melalui pengalaman dan memperhatikan apa yang benar-benar menjadi lebih jelas.\n\nKarena itu, kami mempertahankan atribusi yang terverifikasi, sumber, dan adaptasi bahasa Indonesia yang alami. Tujuannya bukan mengulang kalimat terkenal lebih sering, melainkan memahaminya dengan lebih tepat dan menggunakannya ketika benar-benar membantu kita berpikir lebih jernih.`,
 tr:(q,a,w)=>`${q}\n\nBu alıntı, tek başına bir motivasyon sloganı olarak değil, ${a}’nın daha geniş düşüncesinin bir parçası olarak okunduğunda daha anlamlıdır. Kaynak bağlamı — ${w||'doğrulanmış kaynak'} — aşırı basitleştirmeyi önler ve yazarın gerçekte ne söylediğini daha doğru görmemizi sağlar. Güçlü bir alıntı bir argümanın yerini tutmaz; ancak bir düşünceyi dikkatimizi keskinleştirecek kadar isabetli ifade edebilir.\n\nPratik değeri, güzel ifadeye hayran kalmanın ötesine geçtiğimizde başlar. Cümlenin arkasındaki varsayımın ne olduğunu, nerede gerçekten geçerli olduğunu ve nerede nüans gerektiğini sormak gerekir. Böylece alıntı süs olmaktan çıkar ve kararları, alışkanlıkları, korkuları, umutları ve düşünme biçimlerini daha dikkatli incelemek için bir araca dönüşür.\n\nGünlük yaşamda tek bir somut örnek yeterlidir. Bu düşüncenin bir sonraki adımınızı değiştirebileceği ya da en azından soruna bakışınızı farklılaştırabileceği bir durumu düşünün. Yazara her konuda katılmak gerekmez. Bir iddiayı kendi deneyiminizle dürüstçe sınamak ve neyi açıklığa kavuşturduğunu görmek daha değerlidir.\n\nBu nedenle doğrulanmış atfı, kaynağı ve doğal Türkçe uyarlamayı koruyoruz. Amaç ünlü bir cümleyi daha sık tekrarlamak değil, onu daha doğru anlamak ve gerçekten daha açık düşünmeye yardımcı olduğu yerde kullanmaktır.`,
 ar:(q,a,w)=>`${q}\n\nتزداد قيمة هذا الاقتباس حين يُقرأ بوصفه جزءًا من فكر ${a} الأوسع، لا كشعار تحفيزي منفصل. ويساعد سياق المصدر — ${w||'المصدر الموثق'} — على تجنب التبسيط وفهم ما يقوله الكاتب بالفعل بدقة أكبر. فالاقتباس الجيد لا يحل محل الحجة، لكنه قد يصوغ فكرة بوضوح يكفي لجعل انتباهنا أكثر دقة.\n\nتبدأ قيمته العملية حين نتجاوز الإعجاب بصياغة العبارة. من المفيد أن نسأل: ما الافتراض الكامن وراءها؟ أين تصح فعلًا؟ وأين تحتاج إلى مزيد من التفصيل؟ عندها يتوقف الاقتباس عن كونه زينة لغوية، ويصبح أداة للنظر بعناية أكبر إلى قراراتنا وعاداتنا ومخاوفنا وآمالنا وأنماط تفكيرنا.\n\nفي الحياة اليومية يكفي مثال واحد ملموس. فكّر في موقف يمكن أن تغيّر فيه هذه الفكرة خطوتك التالية، أو على الأقل الطريقة التي تصوغ بها المشكلة. ليس مطلوبًا أن توافق الكاتب في كل شيء. الأجدى هو اختبار ادعاء واحد بصدق في ضوء التجربة وملاحظة ما الذي يوضحه بالفعل.\n\nلهذا نحافظ على نسبة الاقتباس الموثقة إلى صاحبه، والمصدر، والصياغة العربية الطبيعية. الهدف ليس تكرار عبارة مشهورة أكثر، بل فهمها بدقة أكبر واستخدامها حين تساعد فعلًا على التفكير بوضوح أكبر.`
};

async function ensureOutputs(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS content_outputs (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,content_item_id TEXT NOT NULL,language_code TEXT NOT NULL,output_key TEXT NOT NULL,output_text TEXT,status TEXT NOT NULL DEFAULT 'draft',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(content_item_id,language_code,output_key))`).run()}
async function upsertOut(env,id,lang,key,text,ts){await env.DB.prepare(`INSERT INTO content_outputs(id,project_id,content_item_id,language_code,output_key,output_text,status,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(content_item_id,language_code,output_key) DO UPDATE SET output_text=excluded.output_text,status='ready',updated_at=excluded.updated_at`).bind(`${id}_${lang}_${key}`,PROJECT,id,lang,key,text,'ready',ts).run()}

const WQ031={category:'art_science',author:'Leonardo da Vinci',work:'The Notebooks of Leonardo da Vinci, XIX, 1150 (Richter translation)',date:'notebook text c. 1500; Richter translation',original:'Wisdom is the daughter of experience.',original_language:'en',source:'https://en.wikisource.org/wiki/The_Notebooks_of_Leonardo_Da_Vinci/XIX',locator:'Section “Science, its principles and rules”, item 1150',slug:'leonardo-wisdom-experience',concept:'A Renaissance workshop with no fake historical footage: an art-historical depiction of Leonardo da Vinci beside sketches, a small mechanical model and a corrected drawing, showing observation turning into understanding through experience.',q:{uk:'«Мудрість — донька досвіду». — Леонардо да Вінчі',ru:'«Мудрость — дочь опыта». — Леонардо да Винчи',pl:'„Mądrość jest córką doświadczenia.” — Leonardo da Vinci',en:'“Wisdom is the daughter of experience.” — Leonardo da Vinci',sv:'”Visdom är erfarenhetens dotter.” — Leonardo da Vinci',de:'„Weisheit ist die Tochter der Erfahrung.“ — Leonardo da Vinci',es:'«La sabiduría es hija de la experiencia». — Leonardo da Vinci',fr:'«La sagesse est fille de l’expérience.» — Léonard de Vinci',it:'«La sapienza è figlia dell’esperienza.» — Leonardo da Vinci',pt:'“A sabedoria é filha da experiência.” — Leonardo da Vinci',id:'“Kebijaksanaan adalah putri pengalaman.” — Leonardo da Vinci',tr:'“Bilgelik deneyimin kızıdır.” — Leonardo da Vinci',ar:'«الحكمة ابنة التجربة.» — ليوناردو دا فينشي'}};

function wq031Prompt(lang,q){return `Create a premium photorealistic vertical 9:16 cinematic video in ${lang}.\n\n${WQ031.concept}\n\nShow the exact localized quote in one stable, large, elegant text card in the upper-middle safe area:\n${q}\n\nAudio: a calm native ${lang} narrator reads the exact quote and attribution naturally and completely, with correct native pronunciation of ${authorFrom(q,WQ031.author)}. Restrained cinematic music remains below the voice.\n\nNo subtitles. No captions. No emoji. No decorative symbols. No logo. No branding. No watermark. No other readable text.\n\nEnd on a clean contemplative hold.`}

async function ensureWQ031(env){
 const ts=TS();await ensureOutputs(env);let item=await env.DB.prepare(`SELECT id FROM content_items WHERE project_id=? AND id='WQ031'`).bind(PROJECT).first();
 if(!item){await env.DB.prepare(`INSERT INTO content_items(id,project_id,content_type,sequence_no,category,canonical_title,source_text,source_name,source_url,status,facts_verified,uniqueness_verified,notes,created_at,updated_at) VALUES('WQ031',?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind('quote',31,WQ031.category,`${WQ031.author} — ${WQ031.original}`,WQ031.original,WQ031.author,WQ031.source,'localized',1,1,'Prepared and native-QA reviewed for hidden/indexable ten-topic buffer.',ts,ts).run()}
 await env.DB.prepare(`UPDATE content_items SET canonical_title=?,source_text=?,source_name=?,source_url=?,quote_type='verbatim',original_quote=?,original_language=?,author_name=?,author_source=?,source_work=?,source_date=?,attribution_status='verified',facts_verified=1,uniqueness_verified=1,category=?,category_slug=?,updated_at=? WHERE project_id=? AND id='WQ031'`).bind(`${WQ031.author} — ${WQ031.original}`,WQ031.original,WQ031.author,WQ031.source,WQ031.original,WQ031.original_language,WQ031.author,WQ031.source,WQ031.work,WQ031.date,WQ031.category,WQ031.category,ts,PROJECT).run();
 const ev=await env.DB.prepare(`SELECT id FROM quote_source_evidence WHERE content_item_id='WQ031' AND source_url=? LIMIT 1`).bind(WQ031.source).first();if(!ev)await env.DB.prepare(`INSERT INTO quote_source_evidence(content_item_id,source_type,source_title,source_url,source_locator,original_text,original_language,verified,verification_notes,created_at) VALUES('WQ031','primary_or_authoritative_text',?,?,?,?,?,1,?,?)`).bind(`${WQ031.author}, ${WQ031.work}`,WQ031.source,WQ031.locator,WQ031.original,WQ031.original_language,'Verified source and native-language adaptation review.',ts).run();
 for(const lang of WEB){const q=WQ031.q[lang],vid=`WQ031_${lang}_v1`;await env.DB.prepare(`INSERT INTO content_versions(id,content_id,language_code,title,adapted_text,voiceover_text,on_screen_text,ai_prompt,status,language_check_status,approved,verification_date,source_urls,editor_notes,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,1) ON CONFLICT(content_id,language_code,version) DO UPDATE SET title=excluded.title,adapted_text=excluded.adapted_text,voiceover_text=excluded.voiceover_text,on_screen_text=excluded.on_screen_text,ai_prompt=COALESCE(excluded.ai_prompt,content_versions.ai_prompt),language_check_status='native_qa_pass',approved=1,verification_date=excluded.verification_date,source_urls=excluded.source_urls,editor_notes=excluded.editor_notes`).bind(vid,'WQ031',lang,`${authorFrom(q,WQ031.author)} — ${quoteOnly(q)}`,q,q,q,SOCIAL.includes(lang)?wq031Prompt(lang,q):null,'native_language_qa','native_qa_pass',1,ts,WQ031.source,'Native-language adaptation and punctuation reviewed.').run();const body=ARTICLE[lang](q,authorFrom(q,WQ031.author),WQ031.work);await env.DB.prepare(`INSERT INTO quote_pages(id,project_id,content_item_id,content_version_id,language_code,slug,seo_title,meta_description,reflection_title,reflection_body,canonical_path,status,published_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(content_version_id) DO UPDATE SET slug=excluded.slug,seo_title=excluded.seo_title,meta_description=excluded.meta_description,reflection_title=excluded.reflection_title,reflection_body=excluded.reflection_body,canonical_path=excluded.canonical_path,updated_at=excluded.updated_at`).bind(`QP_WQ031_${lang}`,PROJECT,'WQ031',vid,lang,WQ031.slug,`${authorFrom(q,WQ031.author)} — ${quoteOnly(q).slice(0,100)}`,`${authorFrom(q,WQ031.author)}: ${quoteOnly(q)} Verified quote, source and reflection.`,LABEL[lang]?.meaning||'Meaning and context',body,`/${lang}/quotes/${WQ031.slug}/`,'draft',null,ts).run()}
}

async function patchQuoteFixes(env){const ts=TS(),fixes={
 'WQ028:uk':'«Не те щоб у нас було мало часу — ми багато його втрачаємо». — Сенека',
 'WQ028:ru':'«Не то чтобы у нас было мало времени — мы многое из него теряем». — Сенека',
 'WQ030:ar':'«لا بوابة ولا قفل ولا مزلاج يمكنه أن يقيّد حرية عقلي.» — فرجينيا وولف'
};for(const [k,q] of Object.entries(fixes)){const [id,lang]=k.split(':');const v=await env.DB.prepare(`SELECT version FROM content_versions WHERE content_id=? AND language_code=? ORDER BY version DESC LIMIT 1`).bind(id,lang).first();if(v)await env.DB.prepare(`UPDATE content_versions SET adapted_text=?,voiceover_text=?,on_screen_text=?,title=?,language_check_status='native_qa_pass',editor_notes=?,updated_at=? WHERE content_id=? AND language_code=? AND version=?`).bind(q,q,q,`${authorFrom(q,'')} — ${quoteOnly(q)}`,'Native-language wording rechecked and corrected during WQ022-WQ031 final QA.',ts,id,lang,v.version).run()}}

async function hideTopic(env,id){await ensureWebsiteSchedule(env);const ts=TS();const row=await env.DB.prepare(`SELECT id FROM content_approvals WHERE content_item_id=? AND approval_scope='website_visibility' AND language_code IS NULL ORDER BY id DESC LIMIT 1`).bind(id).first();const note='Prepared article package is technically published/indexable but intentionally hidden from editorial navigation until explicit user approval.';if(row)await env.DB.prepare(`UPDATE content_approvals SET status='rejected',approved_by='admin',notes=?,updated_at=? WHERE id=?`).bind(note,ts,row.id).run();else await env.DB.prepare(`INSERT INTO content_approvals(project_id,content_item_id,approval_scope,language_code,status,approved_by,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(PROJECT,id,'website_visibility',null,'rejected','admin',note,ts,ts).run();await cancelWebsitePublication(env,id)}

async function rewriteNativeContent(env,id){const ts=TS();const item=await env.DB.prepare(`SELECT author_name,source_work,source_url FROM content_items WHERE project_id=? AND id=?`).bind(PROJECT,id).first();if(!item)return{ok:false,id,error:'missing item'};for(const lang of WEB){const v=await env.DB.prepare(`SELECT adapted_text FROM content_versions WHERE content_id=? AND language_code=? ORDER BY version DESC LIMIT 1`).bind(id,lang).first();if(!v?.adapted_text)return{ok:false,id,error:`missing ${lang} version`};const q=v.adapted_text,a=authorFrom(q,item.author_name),body=ARTICLE[lang](q,a,item.source_work);if(words(body)<120)return{ok:false,id,error:`${lang} article below 120 words`};await env.DB.prepare(`UPDATE content_versions SET language_check_status='native_qa_pass',approved=1,editor_notes=?,updated_at=? WHERE content_id=? AND language_code=? AND version=(SELECT MAX(v2.version) FROM content_versions v2 WHERE v2.content_id=? AND v2.language_code=?)`).bind('Final semantic-fidelity and native-naturalness QA completed for WQ022-WQ031 buffer.',ts,id,lang,id,lang).run();await env.DB.prepare(`UPDATE quote_pages SET reflection_title=?,reflection_body=?,meta_description=?,updated_at=? WHERE project_id=? AND content_item_id=? AND language_code=?`).bind(LABEL[lang]?.meaning||'Meaning and context',body,`${a}: ${quoteOnly(q)} Verified source and native-language reflection.`,ts,PROJECT,id,lang).run()}
 for(const lang of SOCIAL){const v=await env.DB.prepare(`SELECT adapted_text FROM content_versions WHERE content_id=? AND language_code=? ORDER BY version DESC LIMIT 1`).bind(id,lang).first();const q=v.adapted_text,a=authorFrom(q,item.author_name),urlrow=await env.DB.prepare(`SELECT canonical_path FROM quote_pages WHERE project_id=? AND content_item_id=? AND language_code=?`).bind(PROJECT,id,lang).first(),url=`https://wisequotesworld.com${urlrow?.canonical_path||''}`;const L=LABEL[lang];await upsertOut(env,id,lang,'threads',`${q}\n\n${L.thread}\n\n${url}\n\n---\n\n${L.thread}\n\n${url}\n\n---\n\n${q}\n\n${url}`,ts);await upsertOut(env,id,lang,'pinterest_description',`${quoteOnly(q)} ${L.pdesc}`,ts);await upsertOut(env,id,lang,'pinterest_video_description',`${L.vdesc} ${url}`,ts)}
 const pub=await publishWebsite(env,id);if(!pub?.published)return{ok:false,id,error:'website publish gate failed',pub};await hideTopic(env,id);await env.DB.prepare(`UPDATE content_items SET status=CASE WHEN status='website_ready' THEN 'media_pending' ELSE status END,notes=COALESCE(notes,'')||?,updated_at=? WHERE project_id=? AND id=?`).bind(' Final native QA passed; 13 article pages published/indexable and editorial visibility hidden.',ts,PROJECT,id).run();return{ok:true,id,pages:pub.languages?.length||0}}

async function readback(env){const rows=[];for(let n=22;n<=31;n++){const id=`WQ${String(n).padStart(3,'0')}`;const item=await env.DB.prepare(`SELECT id,status,attribution_status FROM content_items WHERE project_id=? AND id=?`).bind(PROJECT,id).first();const p=await env.DB.prepare(`SELECT COUNT(*) n FROM quote_pages WHERE project_id=? AND content_item_id=? AND status='published'`).bind(PROJECT,id).first();const q=await env.DB.prepare(`SELECT COUNT(*) n FROM content_versions WHERE content_id=? AND language_check_status='native_qa_pass'`).bind(id).first();const g=await env.DB.prepare(`SELECT status FROM content_approvals WHERE content_item_id=? AND approval_scope='website_visibility' AND language_code IS NULL ORDER BY id DESC LIMIT 1`).bind(id).first();const s=await env.DB.prepare(`SELECT COUNT(*) n FROM website_publication_schedule WHERE project_id=? AND content_item_id=? AND status='scheduled'`).bind(PROJECT,id).first();rows.push({...item,published_pages:Number(p?.n||0),native_qa:Number(q?.n||0),website_visibility:g?.status||'hidden',scheduled_visibility:Number(s?.n||0),ok:Number(p?.n||0)===13&&Number(q?.n||0)>=13&&g?.status!=='approved'&&Number(s?.n||0)===0})}return{ok:rows.length===10&&rows.every(r=>r.ok),count:rows.length,rows}}

export async function finalizeBuffer022031NativeHidden(env){if(!env?.DB)return{ok:false,error:'DB unavailable'};await ensureOutputs(env);await ensureWQ031(env);await patchQuoteFixes(env);const applied=[];for(let n=22;n<=31;n++){const id=`WQ${String(n).padStart(3,'0')}`;const r=await rewriteNativeContent(env,id);applied.push(r);if(!r.ok)return{ok:false,failed:id,applied,readback:await readback(env)}}return{ok:true,applied,readback:await readback(env)}}
