import {publishWebsite} from './publication_engine.js';
import {cancelWebsitePublication,ensureWebsiteSchedule} from './website_schedule.js';
const PROJECT='wisequotesworld';
const SOCIAL=['uk','ru','pl','en','sv','de','es','fr'];
const TS=()=>new Date().toISOString();
const COPY={
 uk:{thread:'Іноді одна точна думка корисніша за десяток порад. Важливо не просто погодитися з цитатою, а перевірити її на власному досвіді.',pin:'Перевірена цитата в природній українській адаптації. Повний контекст, джерело та роздуми — у статті.',video:'Відеоверсія перевіреної цитати українською. Повний контекст і роздуми — у статті.'},
 ru:{thread:'Иногда одна точная мысль полезнее десятка советов. Важно не просто согласиться с цитатой, а проверить её на собственном опыте.',pin:'Проверенная цитата в естественной русской адаптации. Полный контекст, источник и размышление — в статье.',video:'Видеоверсия проверенной цитаты на русском. Полный контекст и размышление — в статье.'},
 pl:{thread:'Czasem jedna trafna myśl jest więcej warta niż dziesięć porad. Nie chodzi tylko o zgodę z cytatem, lecz o sprawdzenie go we własnym doświadczeniu.',pin:'Zweryfikowany cytat w naturalnej polskiej adaptacji. Pełny kontekst, źródło i refleksja znajdują się w artykule.',video:'Wersja wideo zweryfikowanego cytatu po polsku. Pełny kontekst i refleksja są w artykule.'},
 en:{thread:'Sometimes one precise idea is more useful than ten pieces of advice. The point is not merely to agree with a quotation, but to test it against experience.',pin:'A verified quotation in natural English, with source context and a fuller reflection in the article.',video:'A video version of the verified quotation in English. The full context and reflection are in the article.'},
 sv:{thread:'Ibland är en träffsäker tanke mer användbar än tio råd. Det viktiga är inte bara att hålla med citatet, utan att pröva det mot den egna erfarenheten.',pin:'Ett verifierat citat i naturlig svensk språkdräkt. Hela sammanhanget, källan och reflektionen finns i artikeln.',video:'Videoversion av det verifierade citatet på svenska. Hela sammanhanget och reflektionen finns i artikeln.'},
 de:{thread:'Manchmal ist ein präziser Gedanke hilfreicher als zehn Ratschläge. Entscheidend ist nicht nur, dem Zitat zuzustimmen, sondern es an der eigenen Erfahrung zu prüfen.',pin:'Ein belegtes Zitat in natürlicher deutscher Fassung. Den vollständigen Kontext, die Quelle und die Reflexion gibt es im Artikel.',video:'Videoversion des belegten Zitats auf Deutsch. Den vollständigen Kontext und die Reflexion gibt es im Artikel.'},
 es:{thread:'A veces una idea precisa resulta más útil que diez consejos. No se trata solo de estar de acuerdo con una cita, sino de contrastarla con la propia experiencia.',pin:'Una cita verificada con una adaptación natural al español. El contexto completo, la fuente y la reflexión están en el artículo.',video:'Versión en vídeo de la cita verificada en español. El contexto completo y la reflexión están en el artículo.'},
 fr:{thread:'Parfois, une pensée juste est plus utile que dix conseils. L’essentiel n’est pas seulement d’approuver une citation, mais de l’éprouver à la lumière de sa propre expérience.',pin:'Une citation vérifiée dans une adaptation française naturelle. Le contexte complet, la source et la réflexion sont dans l’article.',video:'Version vidéo de la citation vérifiée en français. Le contexte complet et la réflexion sont dans l’article.'}
};
function qOnly(q){return String(q||'').replace(/\s+[—-]\s+[^—]+$/u,'').trim()}
function author(q,fallback){const m=String(q||'').match(/[—-]\s*([^—]+)$/u);return m?m[1].trim():fallback}
async function ensureOutputs(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS content_outputs (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,content_item_id TEXT NOT NULL,language_code TEXT NOT NULL,output_key TEXT NOT NULL,output_text TEXT,status TEXT NOT NULL DEFAULT 'draft',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(content_item_id,language_code,output_key))`).run()}
async function patchKnownNativeIssues(env,id){const ts=TS(),stmts=[];if(id==='WQ028'){stmts.push(env.DB.prepare(`UPDATE content_versions SET adapted_text=?,voiceover_text=?,on_screen_text=?,title=?,language_check_status='native_qa_pass',approved=1,editor_notes=?,updated_at=? WHERE content_id='WQ028' AND language_code='uk' AND version=(SELECT MAX(v2.version) FROM content_versions v2 WHERE v2.content_id='WQ028' AND v2.language_code='uk')`).bind('«Не те щоб у нас було мало часу — ми багато його втрачаємо». — Сенека','«Не те щоб у нас було мало часу — ми багато його втрачаємо». — Сенека','«Не те щоб у нас було мало часу — ми багато його втрачаємо». — Сенека','Сенека — «Не те щоб у нас було мало часу — ми багато його втрачаємо».','Native Ukrainian wording rechecked.',ts));stmts.push(env.DB.prepare(`UPDATE content_versions SET adapted_text=?,voiceover_text=?,on_screen_text=?,title=?,language_check_status='native_qa_pass',approved=1,editor_notes=?,updated_at=? WHERE content_id='WQ028' AND language_code='ru' AND version=(SELECT MAX(v2.version) FROM content_versions v2 WHERE v2.content_id='WQ028' AND v2.language_code='ru')`).bind('«Не то чтобы у нас было мало времени — мы многое из него теряем». — Сенека','«Не то чтобы у нас было мало времени — мы многое из него теряем». — Сенека','«Не то чтобы у нас было мало времени — мы многое из него теряем». — Сенека','Сенека — «Не то чтобы у нас было мало времени — мы многое из него теряем».','Native Russian wording rechecked.',ts))}if(id==='WQ030')stmts.push(env.DB.prepare(`UPDATE content_versions SET adapted_text=?,voiceover_text=?,on_screen_text=?,title=?,language_check_status='native_qa_pass',approved=1,editor_notes=?,updated_at=? WHERE content_id='WQ030' AND language_code='ar' AND version=(SELECT MAX(v2.version) FROM content_versions v2 WHERE v2.content_id='WQ030' AND v2.language_code='ar')`).bind('«لا بوابة ولا قفل ولا مزلاج يمكنه أن يقيّد حرية عقلي.» — فرجينيا وولف','«لا بوابة ولا قفل ولا مزلاج يمكنه أن يقيّد حرية عقلي.» — فرجينيا وولف','«لا بوابة ولا قفل ولا مزلاج يمكنه أن يقيّد حرية عقلي.» — فرجينيا وولف','فرجينيا وولف — «لا بوابة ولا قفل ولا مزلاج يمكنه أن يقيّد حرية عقلي.»','Native Arabic wording rechecked.',ts));if(stmts.length)await env.DB.batch(stmts)}
async function patchLanguageArtifacts(env,id){const ts=TS();await env.DB.batch([
 env.DB.prepare(`UPDATE quote_pages SET reflection_body=REPLACE(REPLACE(reflection_body,'Ta cytat','Ten cytat'),'Le citation','La citation'),updated_at=? WHERE project_id=? AND content_item_id=?`).bind(ts,PROJECT,id),
 env.DB.prepare(`UPDATE content_versions SET language_check_status='native_qa_pass',approved=1,editor_notes=COALESCE(editor_notes,'')||?,updated_at=? WHERE content_id=?`).bind(' Final WQ022-WQ031 native-language QA rechecked.',ts,id)
 ]);
 const rows=(await env.DB.prepare(`SELECT v.language_code,v.adapted_text,p.canonical_path FROM content_versions v JOIN (SELECT language_code,MAX(version) version FROM content_versions WHERE content_id=? GROUP BY language_code) m ON m.language_code=v.language_code AND m.version=v.version LEFT JOIN quote_pages p ON p.content_item_id=? AND p.language_code=v.language_code AND p.project_id=? WHERE v.content_id=? AND v.language_code IN ('uk','ru','pl','en','sv','de','es','fr') ORDER BY v.language_code`).bind(id,id,PROJECT,id).all()).results||[];if(rows.length!==8)return{ok:false,error:`social locale versions ${rows.length}/8`};const item=await env.DB.prepare(`SELECT author_name FROM content_items WHERE project_id=? AND id=?`).bind(PROJECT,id).first();const out=[];for(const r of rows){const C=COPY[r.language_code],q=r.adapted_text,url=`https://wisequotesworld.com${r.canonical_path||''}`;out.push(env.DB.prepare(`INSERT INTO content_outputs(id,project_id,content_item_id,language_code,output_key,output_text,status,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(content_item_id,language_code,output_key) DO UPDATE SET output_text=excluded.output_text,status='ready',updated_at=excluded.updated_at`).bind(`${id}_${r.language_code}_threads`,PROJECT,id,r.language_code,'threads',`${q}\n\n${C.thread}\n\n${url}\n\n---\n\n${C.thread}\n\n${url}\n\n---\n\n${q}\n\n${url}`,'ready',ts));out.push(env.DB.prepare(`INSERT INTO content_outputs(id,project_id,content_item_id,language_code,output_key,output_text,status,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(content_item_id,language_code,output_key) DO UPDATE SET output_text=excluded.output_text,status='ready',updated_at=excluded.updated_at`).bind(`${id}_${r.language_code}_pinterest_description`,PROJECT,id,r.language_code,'pinterest_description',`${qOnly(q)} ${C.pin}`,'ready',ts));out.push(env.DB.prepare(`INSERT INTO content_outputs(id,project_id,content_item_id,language_code,output_key,output_text,status,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(content_item_id,language_code,output_key) DO UPDATE SET output_text=excluded.output_text,status='ready',updated_at=excluded.updated_at`).bind(`${id}_${r.language_code}_pinterest_video_description`,PROJECT,id,r.language_code,'pinterest_video_description',`${C.video} ${url}`,'ready',ts))}await env.DB.batch(out);return{ok:true,author:item?.author_name||null}}
async function hide(env,id){await ensureWebsiteSchedule(env);const ts=TS(),row=await env.DB.prepare(`SELECT id FROM content_approvals WHERE content_item_id=? AND approval_scope='website_visibility' AND language_code IS NULL ORDER BY id DESC LIMIT 1`).bind(id).first(),note='Technically published/indexable but intentionally hidden from editorial navigation until explicit user approval.';if(row)await env.DB.prepare(`UPDATE content_approvals SET status='rejected',approved_by='admin',notes=?,updated_at=? WHERE id=?`).bind(note,ts,row.id).run();else await env.DB.prepare(`INSERT INTO content_approvals(project_id,content_item_id,approval_scope,language_code,status,approved_by,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(PROJECT,id,'website_visibility',null,'rejected','admin',note,ts,ts).run();await cancelWebsitePublication(env,id)}
async function state(env,id){const item=await env.DB.prepare(`SELECT id,status,attribution_status FROM content_items WHERE project_id=? AND id=?`).bind(PROJECT,id).first(),p=await env.DB.prepare(`SELECT COUNT(*) n FROM quote_pages WHERE project_id=? AND content_item_id=? AND status='published'`).bind(PROJECT,id).first(),q=await env.DB.prepare(`SELECT COUNT(*) n FROM content_versions WHERE content_id=? AND language_check_status='native_qa_pass'`).bind(id).first(),g=await env.DB.prepare(`SELECT status FROM content_approvals WHERE content_item_id=? AND approval_scope='website_visibility' AND language_code IS NULL ORDER BY id DESC LIMIT 1`).bind(id).first();let scheduled=0;try{const s=await env.DB.prepare(`SELECT COUNT(*) n FROM website_publication_schedule WHERE project_id=? AND content_item_id=? AND status='scheduled'`).bind(PROJECT,id).first();scheduled=Number(s?.n||0)}catch{}return{...item,published_pages:Number(p?.n||0),native_qa:Number(q?.n||0),website_visibility:g?.status||'hidden',scheduled_visibility:scheduled,ok:!!item&&Number(p?.n||0)===13&&Number(q?.n||0)>=13&&g?.status!=='approved'&&scheduled===0}}
export async function finalizeOne022031(env,id){if(!env?.DB)return{ok:false,error:'DB unavailable'};if(!/^WQ0(?:22|23|24|25|26|27|28|29|30|31)$/.test(id))return{ok:false,error:'unsupported id'};await ensureOutputs(env);const before=await state(env,id);if(!before.id)return{ok:false,id,error:'topic missing'};await patchKnownNativeIssues(env,id);const p=await patchLanguageArtifacts(env,id);if(!p.ok)return{ok:false,id,...p};const pub=await publishWebsite(env,id);if(!pub?.published)return{ok:false,id,error:'publish gate failed',pub};await hide(env,id);const after=await state(env,id);return{ok:after.ok,id,before,after}}
export async function readAll022031(env){const rows=[];for(let n=22;n<=31;n++)rows.push(await state(env,`WQ${String(n).padStart(3,'0')}`));return{ok:rows.length===10&&rows.every(r=>r.ok),count:rows.length,rows}}
