const PROJECT_ID='wisequotesworld';
const MARKER='legacy_static_discipline_v1';

const DATA={
  uk:{slug:'dystsyplina-koly-nikhto-ne-zmushuie',title:'Найважча перемога: дисципліна, коли ніхто не змушує',meta:'Роздуми про самодисципліну, силу волі та обіцянки, які ми даємо самим собі.',quote:'Найважча перемога — зробити те, що потрібно, коли ніхто не змушує.',reflection:'Дисципліна найкраще проявляється не тоді, коли нас контролюють. Складніше встати, почати роботу, тренування чи навчання, коли ніхто не перевірить результат.\n\nМожна відкласти на завтра. Можна пропустити. Можна нікому нічого не пояснювати. Але самодисципліна починається в момент, коли ми все одно виконуємо те, що пообіцяли собі.\n\nТакі рішення здаються маленькими. Проте саме вони, повторені десятки разів, формують навички, характер і довіру до самого себе.\n\nЩо ви зробили б сьогодні, навіть якби ніхто про це не дізнався?'},
  ru:{slug:'distsiplina-kogda-nikto-ne-zastavlyaet',title:'Самая трудная победа: дисциплина, когда никто не заставляет',meta:'Размышление о самодисциплине, силе воли и обещаниях, которые мы даём самим себе.',quote:'Самая трудная победа — сделать то, что нужно, когда никто тебя не заставляет.',reflection:'Настоящая дисциплина лучше всего видна тогда, когда контроля нет. Намного сложнее начать работу, тренировку или учёбу, если никто не спросит о результате.\n\nМожно перенести на завтра. Можно пропустить. Можно никому ничего не объяснять. Но самодисциплина начинается там, где мы всё равно выполняем обещание, данное самим себе.\n\nТакие решения кажутся маленькими. Но именно они, повторённые десятки раз, формируют навыки, характер и доверие к себе.\n\nЧто вы сделали бы сегодня, даже если бы никто об этом не узнал?'},
  pl:{slug:'dyscyplina-gdy-nikt-nie-zmusza',title:'Najtrudniejsze zwycięstwo: dyscyplina, gdy nikt nie zmusza',meta:'Refleksja o samodyscyplinie, sile woli i dotrzymywaniu obietnic złożonych samemu sobie.',quote:'Najtrudniejsze zwycięstwo to zrobić to, co trzeba, gdy nikt cię do tego nie zmusza.',reflection:'Prawdziwa dyscyplina ujawnia się wtedy, gdy nikt nie patrzy. O wiele trudniej zabrać się do pracy, treningu czy nauki, jeśli nikt nie sprawdzi efektu.\n\nMożesz przełożyć wszystko na jutro. Możesz odpuścić. Nikt nie musi się o tym dowiedzieć. Samodyscyplina zaczyna się wtedy, gdy mimo to robisz to, co sobie obiecałeś.\n\nTakie decyzje wydają się małe, ale powtarzane regularnie budują umiejętności, charakter i zaufanie do samego siebie.\n\nCo zrobiłbyś dziś, nawet gdyby nikt się o tym nie dowiedział?'},
  en:{slug:'discipline-when-no-one-is-watching',title:'The Hardest Victory: Discipline When No One Is Watching',meta:'A reflection on self-discipline, consistency and keeping promises to yourself when no one is watching.',quote:'The hardest victory is doing what needs to be done when no one is making you do it.',reflection:'Discipline is easy to admire when it is visible. The harder version happens quietly: getting up, studying, training, finishing the task or keeping a promise when nobody is checking.\n\nExternal pressure can make us act, but self-discipline begins when that pressure disappears. You could postpone the work. You could skip it. No one might ever know. Yet you choose to do what you said you would do.\n\nThose small choices rarely feel dramatic. But repeated over weeks and months, they shape skills, health, confidence and character. Consistency is often less about feeling motivated and more about deciding that your own word matters.\n\nWhat would you still do today if nobody could praise you for doing it?'},
  sv:{slug:'disciplin-nar-ingen-kraver-det',title:'Den svåraste segern: disciplin när ingen kräver det',meta:'En reflektion om självdisciplin, viljestyrka och att hålla löften till sig själv när ingen annan kontrollerar.',quote:'Den svåraste segern är att göra det som behöver göras när ingen kräver det av dig.',reflection:'Disciplin märks tydligast när ingen håller koll. Det är mycket svårare att träna, studera eller göra klart jobbet när ingen kommer att fråga om resultatet.\n\nDu kan skjuta upp det till i morgon. Du kan låta bli. Ingen annan behöver ens veta. Självdisciplin börjar när du ändå gör det du har bestämt dig för.\n\nDe besluten känns sällan stora i stunden. Men när de upprepas bygger de färdigheter, karaktär och tillit till den egna förmågan.\n\nVad skulle du fortfarande göra i dag om ingen annan kunde se det?'},
  de:{slug:'disziplin-wenn-niemand-dich-zwingt',title:'Der schwerste Sieg: Disziplin, wenn dich niemand zwingt',meta:'Eine Reflexion über Selbstdisziplin, Willenskraft und das Einhalten von Versprechen an sich selbst.',quote:'Der schwerste Sieg ist, das zu tun, was getan werden muss, wenn dich niemand dazu zwingt.',reflection:'Disziplin zeigt sich am deutlichsten, wenn niemand zusieht. Es ist viel schwerer zu trainieren, zu lernen oder eine Aufgabe sauber zu Ende zu bringen, wenn niemand das Ergebnis kontrolliert.\n\nDu kannst es auf morgen verschieben. Du kannst es auslassen. Niemand muss davon erfahren. Selbstdisziplin beginnt dort, wo du trotzdem tust, was du dir vorgenommen hast.\n\nSolche Entscheidungen wirken klein. Wiederholt man sie jedoch über Wochen und Monate, entstehen daraus Fähigkeiten, Verlässlichkeit und Vertrauen in sich selbst.\n\nWas würdest du heute trotzdem tun, wenn niemand es bemerken könnte?'},
  es:{slug:'disciplina-cuando-nadie-te-obliga',title:'La victoria más difícil: disciplina cuando nadie te obliga',meta:'Una reflexión sobre autodisciplina, fuerza de voluntad y cumplir las promesas que te haces a ti mismo.',quote:'La victoria más difícil es hacer lo que tienes que hacer cuando nadie te obliga.',reflection:'La disciplina se ve con más claridad cuando nadie está mirando. Es mucho más difícil entrenar, estudiar o terminar una tarea cuando nadie va a comprobar el resultado.\n\nPuedes dejarlo para mañana. Puedes saltártelo. Nadie tiene por qué enterarse. La autodisciplina empieza cuando, aun así, haces lo que te prometiste hacer.\n\nEsas decisiones parecen pequeñas, pero repetidas durante semanas y meses construyen habilidades, constancia y confianza en uno mismo.\n\n¿Qué seguirías haciendo hoy aunque nadie pudiera felicitarte por ello?'},
  fr:{slug:'discipline-quand-personne-ne-vous-y-oblige',title:'La victoire la plus difficile : la discipline quand personne ne vous y oblige',meta:'Une réflexion sur l’autodiscipline, la constance et les promesses que l’on se fait à soi-même.',quote:'La victoire la plus difficile, c’est de faire ce qui doit être fait quand personne ne vous y oblige.',reflection:'La discipline se révèle surtout lorsque personne ne regarde. Il est bien plus difficile de travailler, de s’entraîner, d’étudier ou d’aller au bout d’une tâche quand personne ne viendra vérifier le résultat.\n\nOn peut remettre à demain. On peut renoncer. Personne n’est obligé de le savoir. L’autodiscipline commence lorsque, malgré tout, on tient la promesse que l’on s’est faite.\n\nCes décisions paraissent petites sur le moment. Pourtant, répétées semaine après semaine, elles construisent les compétences, la constance, le caractère et la confiance en soi.\n\nQue feriez-vous aujourd’hui même si personne ne pouvait vous féliciter de l’avoir fait ?'}
};

function now(){return new Date().toISOString()}
async function chooseId(db){
  const existing=await db.prepare("SELECT id FROM content_items WHERE project_id=? AND notes LIKE ? LIMIT 1").bind(PROJECT_ID,`%${MARKER}%`).first();
  if(existing?.id)return existing.id;
  const wq5=await db.prepare("SELECT id FROM content_items WHERE id='WQ005' LIMIT 1").first();
  if(!wq5)return 'WQ005';
  const row=await db.prepare("SELECT MAX(CAST(SUBSTR(id,3) AS INTEGER)) n FROM content_items WHERE project_id=? AND id GLOB 'WQ[0-9]*'").bind(PROJECT_ID).first();
  return `WQ${String(Number(row?.n||11)+1).padStart(3,'0')}`;
}

export async function ensureLegacyContentMigrated(env){
  if(!env?.DB)return {ok:false,skipped:'no-db'};
  const done=await env.DB.prepare("SELECT id FROM content_items WHERE project_id=? AND notes LIKE ? LIMIT 1").bind(PROJECT_ID,`%${MARKER}%`).first();
  const id=done?.id||await chooseId(env.DB), ts=now();
  if(!done){
    const seq=Number(String(id).replace(/^WQ/i,''))||5;
    await env.DB.prepare(`INSERT INTO content_items(id,project_id,content_type,sequence_no,category,canonical_title,source_text,source_name,source_url,status,facts_verified,uniqueness_verified,notes,created_at,updated_at,quote_type,original_quote,original_language,author_name,author_source,source_work,source_date,attribution_status,category_slug) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,PROJECT_ID,'quote',seq,'discipline','The Hardest Victory: Discipline When No One Is Watching',DATA.en.quote,null,null,'published',1,1,`${MARKER}; migrated from legacy static Wise Quotes pages; FR newly localized from EN during 8-language D1 cutover`,ts,ts,'adapted',DATA.en.quote,'en',null,null,null,null,'not_required','discipline').run();
  }
  for(const [lang,d] of Object.entries(DATA)){
    const vid=`${id}_${lang}_v1`;
    await env.DB.prepare(`INSERT INTO content_versions(id,content_id,language_code,title,adapted_text,voiceover_text,on_screen_text,status,language_check_status,approved,version) VALUES(?,?,?,?,?,?,?,?,?,?,1) ON CONFLICT(content_id,language_code,version) DO UPDATE SET title=excluded.title,adapted_text=excluded.adapted_text,voiceover_text=excluded.voiceover_text,on_screen_text=excluded.on_screen_text,status=excluded.status,language_check_status=excluded.language_check_status,approved=excluded.approved`).bind(vid,id,lang,d.title,d.quote,d.quote,d.quote,'website_ready','legacy_migrated',1).run();
  }
  const approval=await env.DB.prepare("SELECT id,status FROM content_approvals WHERE content_item_id=? AND approval_scope='content' AND language_code IS NULL LIMIT 1").bind(id).first();
  if(approval){
    if(approval.status!=='approved')await env.DB.prepare("UPDATE content_approvals SET status='approved',approved_by='legacy_migration',notes=?,updated_at=? WHERE id=?").bind('Approved as previously public Wise Quotes original during database-first migration',ts,approval.id).run();
  }else{
    await env.DB.prepare("INSERT INTO content_approvals(project_id,content_item_id,approval_scope,language_code,status,approved_by,notes,created_at,updated_at) VALUES(?,?,'content',NULL,'approved','legacy_migration',?,?,?)").bind(PROJECT_ID,id,'Approved as previously public Wise Quotes original during database-first migration',ts,ts).run();
  }
  for(const [lang,d] of Object.entries(DATA)){
    const vid=`${id}_${lang}_v1`, qid=`${id}_${lang}_page`, canonical=`/${lang}/quotes/${d.slug}/`;
    await env.DB.prepare(`INSERT INTO quote_pages(id,project_id,content_item_id,content_version_id,language_code,slug,seo_title,meta_description,reflection_title,reflection_body,canonical_path,status,published_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(content_version_id) DO UPDATE SET slug=excluded.slug,seo_title=excluded.seo_title,meta_description=excluded.meta_description,reflection_title=excluded.reflection_title,reflection_body=excluded.reflection_body,canonical_path=excluded.canonical_path,status='published',published_at=COALESCE(quote_pages.published_at,excluded.published_at),updated_at=excluded.updated_at`).bind(qid,PROJECT_ID,id,vid,lang,d.slug,d.title,d.meta,d.title,d.reflection,canonical,'published',ts,ts).run();
  }
  return {ok:true,id,languages:Object.keys(DATA),marker:MARKER};
}
