const PROJECT_ID='wisequotesworld';
const ALL=['uk','ru','pl','en','sv','de','es','fr','it','pt','id','tr','ar'];
const INDEXNOW_KEY='7f3c91a4d2e85b6076fa34c1b9e2d508';
const NAMES={uk:'Українська',ru:'Русский',pl:'Polski',en:'English',sv:'Svenska',de:'Deutsch',es:'Español',fr:'Français',it:'Italiano',pt:'Português (Brasil)',id:'Bahasa Indonesia',tr:'Türkçe',ar:'العربية'};
const FLAGS={uk:'🇺🇦',ru:'🌐',pl:'🇵🇱',en:'🇬🇧',sv:'🇸🇪',de:'🇩🇪',es:'🇪🇸',fr:'🇫🇷',it:'🇮🇹',pt:'🇧🇷',id:'🇮🇩',tr:'🇹🇷',ar:'🌍'};
const UI={
 id:{title:'Kebijaksanaan yang layak diingat',lead:'Kata-kata abadi, refleksi baru, dan kutipan yang layak dibaca kembali.',all:'Semua kutipan',latest:'Publikasi terbaru',read:'Baca refleksi',empty:'Belum ada kutipan yang diterbitkan.',back:'Kembali ke semua kutipan',topics:'Kutipan dan refleksi',start:'Mulai',categories:'Topik',authors:'Penulis',home:'Beranda'},
 tr:{title:'Hatırlamaya değer bilgelik',lead:'Zamansız sözler, yeni düşünceler ve tekrar dönmeye değer alıntılar.',all:'Tüm alıntılar',latest:'Son yayınlar',read:'Düşünceyi oku',empty:'Henüz yayımlanmış alıntı yok.',back:'Tüm alıntılara dön',topics:'Alıntılar ve düşünceler',start:'Başlangıç',categories:'Konular',authors:'Yazarlar',home:'Ana sayfa'},
 ar:{title:'حكمة تستحق أن نتذكرها',lead:'كلمات خالدة وتأملات جديدة واقتباسات تستحق العودة إليها.',all:'جميع الاقتباسات',latest:'أحدث المنشورات',read:'اقرأ التأمل',empty:'لا توجد اقتباسات منشورة بعد.',back:'العودة إلى جميع الاقتباسات',topics:'اقتباسات وتأملات',start:'صفحة البداية',categories:'الموضوعات',authors:'المؤلفون',home:'الرئيسية'}
};
const CATLABEL={
 discipline:{id:'Disiplin',tr:'Disiplin',ar:'الانضباط'},
 'parents-family':{id:'Orang tua & keluarga',tr:'Anne baba ve aile',ar:'الوالدان والأسرة'},
 'philosophy-strength':{id:'Filsafat & kekuatan',tr:'Felsefe ve güç',ar:'الفلسفة والقوة'},
 identity:{id:'Jati diri',tr:'Kimlik ve özgünlük',ar:'الهوية والأصالة'}
};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function xml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]))}
function slug(v){return String(v||'').trim().toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-+|-+$/g,'')||'other'}
function htmlLang(l){return l==='pt'?'pt-BR':l}
function jsonLd(data){return `<script type="application/ld+json">${JSON.stringify(data).replace(/</g,'\\u003c')}</script>`}
async function list(env,lang,category=null,author=null){let sql=`SELECT qp.slug,qp.seo_title,qp.meta_description,qp.reflection_title,qp.reflection_body,qp.canonical_path,qp.published_at,qp.updated_at,cv.adapted_text,ci.author_name,ci.attribution_status,ci.category,ci.category_slug,ci.content_type,ci.quote_type,ci.id content_id FROM quote_pages qp JOIN content_versions cv ON cv.id=qp.content_version_id JOIN content_items ci ON ci.id=qp.content_item_id WHERE qp.project_id=? AND qp.language_code=? AND qp.status='published'`;const bind=[PROJECT_ID,lang];if(category){sql+=` AND COALESCE(ci.category_slug,'')=?`;bind.push(category)}if(author){sql+=` AND ci.attribution_status='verified' AND ci.author_name=?`;bind.push(author)}sql+=` ORDER BY COALESCE(ci.sequence_no,CAST(SUBSTR(ci.id,3) AS INTEGER),0) DESC,qp.updated_at DESC`;return (await env.DB.prepare(sql).bind(...bind).all()).results||[]}
async function one(env,lang,quoteSlug){return await env.DB.prepare(`SELECT qp.slug,qp.seo_title,qp.meta_description,qp.reflection_title,qp.reflection_body,qp.canonical_path,qp.published_at,qp.updated_at,cv.adapted_text,ci.author_name,ci.attribution_status,ci.category,ci.category_slug,ci.content_type,ci.quote_type,ci.id content_id FROM quote_pages qp JOIN content_versions cv ON cv.id=qp.content_version_id JOIN content_items ci ON ci.id=qp.content_item_id WHERE qp.project_id=? AND qp.language_code=? AND qp.slug=? AND qp.status='published' LIMIT 1`).bind(PROJECT_ID,lang,quoteSlug).first()}
async function alternates(env,contentId){return (await env.DB.prepare(`SELECT language_code,canonical_path FROM quote_pages WHERE project_id=? AND content_item_id=? AND status='published' ORDER BY language_code`).bind(PROJECT_ID,contentId).all()).results||[]}
async function categories(env,lang){return (await env.DB.prepare(`SELECT COALESCE(NULLIF(ci.category_slug,''),'other') slug,COALESCE(NULLIF(ci.category,''),NULLIF(ci.category_slug,''),'Other') label,COUNT(*) count FROM quote_pages qp JOIN content_items ci ON ci.id=qp.content_item_id WHERE qp.project_id=? AND qp.language_code=? AND qp.status='published' GROUP BY COALESCE(NULLIF(ci.category_slug,''),'other'),COALESCE(NULLIF(ci.category,''),NULLIF(ci.category_slug,''),'Other') ORDER BY count DESC,label`).bind(PROJECT_ID,lang).all()).results||[]}
async function authors(env,lang){const a=(await env.DB.prepare(`SELECT ci.author_name,COUNT(*) count FROM quote_pages qp JOIN content_items ci ON ci.id=qp.content_item_id WHERE qp.project_id=? AND qp.language_code=? AND qp.status='published' AND ci.attribution_status='verified' AND TRIM(COALESCE(ci.author_name,''))<>'' GROUP BY ci.author_name ORDER BY count DESC,ci.author_name`).bind(PROJECT_ID,lang).all()).results||[];return a.map(x=>({...x,slug:slug(x.author_name)}))}
function langMenu(){return ALL.map(l=>`<a href="/${l}/">${FLAGS[l]} ${NAMES[l]}</a>`).join('')}
function homeAlternates(path=''){return ALL.map(l=>`<link rel="alternate" hreflang="${htmlLang(l)}" href="https://wisequotesworld.com/${l}/${path}">`).join('')+`<link rel="alternate" hreflang="x-default" href="https://wisequotesworld.com/en/${path}">`}
function quoteAlternates(alts=[]){if(!alts.length)return'';const links=alts.map(a=>`<link rel="alternate" hreflang="${htmlLang(a.language_code)}" href="https://wisequotesworld.com${esc(a.canonical_path)}">`).join('');const en=alts.find(a=>a.language_code==='en')||alts[0];return links+(en?`<link rel="alternate" hreflang="x-default" href="https://wisequotesworld.com${esc(en.canonical_path)}">`:'')}
function baseHead(lang,title,desc,canonical,alternatesHtml='',schema=''){const dir=lang==='ar'?' dir="rtl"':'';return `<!doctype html><html lang="${htmlLang(lang)}"${dir}><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Wise Quotes World</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="https://wisequotesworld.com${esc(canonical)}">${alternatesHtml}${schema}<link rel="stylesheet" href="/styles.css"><style>.locale13{padding:72px 0}.locale13 .lead{max-width:760px}.locale13-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin-top:30px}.locale13-card{display:flex;flex-direction:column;text-decoration:none;color:inherit;background:var(--panel);border:1px solid var(--line);border-radius:22px;padding:24px}.locale13-card blockquote{font-family:Georgia,serif;font-size:24px;line-height:1.35;margin:16px 0}.locale13-card small{color:var(--muted)}.locale13-article{max-width:820px;margin:auto}.locale13-article blockquote{font-family:Georgia,serif;font-size:34px;line-height:1.35;margin:28px 0;padding:24px;border-inline-start:3px solid var(--gold2);background:var(--panel)}.locale13-article .reflection{font-size:18px;line-height:1.8;white-space:pre-line}.locale13-nav{display:flex;gap:14px;align-items:center;justify-content:space-between}.locale13-menu{display:flex;gap:8px;flex-wrap:wrap;margin-top:20px}.locale13-menu a{text-decoration:none;font-size:13px;color:var(--muted)}.langmenu{max-height:70vh;overflow-y:auto}.langmenu a{text-decoration:none}.seo-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:28px}.seo-card{display:block;text-decoration:none;color:inherit;background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:20px}.seo-card small{color:var(--muted)}@media(max-width:650px){.locale13-grid,.seo-grid{grid-template-columns:1fr}.locale13{padding:44px 0}.locale13-article blockquote{font-size:27px}}</style></head><body>`}
function header(lang){return `<header class="header"><div class="container nav"><a class="brand" href="/${lang}/"><span class="mark">W</span><span><strong>Wise Quotes World</strong><small>Timeless words · 13 languages</small></span></a><div class="lang"><button aria-label="Language">${FLAGS[lang]}</button><div class="langmenu">${langMenu()}</div></div></div></header>`}
function footer(lang){return `<footer class="footer"><div class="container"><div class="locale13-menu">${langMenu()}</div><p>© 2026 Wise Quotes World</p></div></footer><script>const lb=document.querySelector('.lang button'),lm=document.querySelector('.langmenu');lb&&lb.addEventListener('click',()=>lm.classList.toggle('show'));</script></body></html>`}
function categoryLabel(lang,row){return CATLABEL[row.category_slug||row.slug]?.[lang]||row.category||row.label||row.category_slug||row.slug||'Wise Quotes World'}
function cards(lang,rows){const u=UI[lang];if(!rows.length)return `<p>${u.empty}</p>`;return `<div class="locale13-grid">${rows.map(r=>`<a class="locale13-card" href="/${lang}/quotes/${encodeURIComponent(r.slug)}/"><small>${esc(categoryLabel(lang,r))}</small><blockquote>“${esc(r.adapted_text)}”</blockquote><b>${r.author_name&&r.attribution_status==='verified'?'— '+esc(r.author_name):'Wise Quotes World'} →</b></a>`).join('')}</div>`}
async function home(env,lang,archive=false){const u=UI[lang],rows=await list(env,lang),cats=await categories(env,lang),auths=await authors(env,lang),title=archive?u.all:u.title,canonical=archive?`/${lang}/quotes/`:`/${lang}/`,alts=homeAlternates(archive?'quotes/':'');const schema=jsonLd({'@context':'https://schema.org','@type':'CollectionPage',name:title,url:`https://wisequotesworld.com${canonical}`,inLanguage:htmlLang(lang),isPartOf:{'@type':'WebSite',name:'Wise Quotes World',url:'https://wisequotesworld.com/'}});const explore=!archive?`${cats.length?`<section><h2>${esc(u.categories)}</h2><div class="seo-grid">${cats.map(c=>`<a class="seo-card" href="/${lang}/category/${encodeURIComponent(c.slug)}/"><strong>${esc(categoryLabel(lang,c))}</strong><small>${c.count}</small></a>`).join('')}</div></section>`:''}${auths.length?`<section><h2>${esc(u.authors)}</h2><div class="seo-grid">${auths.map(a=>`<a class="seo-card" href="/${lang}/author/${encodeURIComponent(a.slug)}/"><strong>${esc(a.author_name)}</strong><small>${a.count}</small></a>`).join('')}</div></section>`:''}`:'';const body=`${baseHead(lang,title,u.lead,canonical,alts,schema)}${header(lang)}<main class="locale13"><div class="container"><span class="kicker">Wise Quotes World</span><h1>${esc(title)}</h1><p class="lead">${esc(u.lead)}</p>${cards(lang,rows)}${explore}${!archive?`<p style="margin-top:26px"><a class="btn" href="/${lang}/quotes/">${esc(u.all)}</a> <a class="btn alt" href="/${lang}/start/">${esc(u.start)}</a></p>`:''}</div></main>${footer(lang)}`;return new Response(body,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=300'}})}
async function detail(env,lang,quoteSlug){const u=UI[lang],r=await one(env,lang,quoteSlug);if(!r)return null;const alts=await alternates(env,r.content_id);const canonical=r.canonical_path||`/${lang}/quotes/${r.slug}/`;const verified=r.author_name&&r.attribution_status==='verified';const author=verified?`<p><strong>— ${esc(r.author_name)}</strong></p>`:'';const authorUrl=verified?`https://wisequotesworld.com/${lang}/author/${encodeURIComponent(slug(r.author_name))}/`:null;const schema=jsonLd([{'@context':'https://schema.org','@type':'Article',headline:r.seo_title||r.reflection_title||r.adapted_text,description:r.meta_description||u.lead,url:`https://wisequotesworld.com${canonical}`,mainEntityOfPage:`https://wisequotesworld.com${canonical}`,datePublished:r.published_at||undefined,dateModified:r.updated_at||r.published_at||undefined,inLanguage:htmlLang(lang),author:verified?{'@type':'Person',name:r.author_name,url:authorUrl}:{'@type':'Organization',name:'Wise Quotes World',url:'https://wisequotesworld.com/'},publisher:{'@type':'Organization',name:'Wise Quotes World',url:'https://wisequotesworld.com/'}},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:u.home,item:`https://wisequotesworld.com/${lang}/`},{'@type':'ListItem',position:2,name:u.all,item:`https://wisequotesworld.com/${lang}/quotes/`},{'@type':'ListItem',position:3,name:r.reflection_title||r.seo_title||u.topics,item:`https://wisequotesworld.com${canonical}`}]}]);const arrow=lang==='ar'?'→':'←';const html=`${baseHead(lang,r.seo_title||r.reflection_title||r.adapted_text,r.meta_description||u.lead,canonical,quoteAlternates(alts),schema)}${header(lang)}<main class="locale13"><article class="container locale13-article"><p><a href="/${lang}/quotes/">${arrow} ${esc(u.back)}</a></p><span class="kicker">Wise Quotes World</span><h1>${esc(r.reflection_title||r.seo_title||u.topics)}</h1><blockquote>“${esc(r.adapted_text)}”</blockquote>${author}<div class="reflection">${esc(r.reflection_body)}</div><p style="margin-top:30px"><a class="btn" href="/${lang}/quotes/">${esc(u.all)}</a>${r.category_slug?` <a class="btn alt" href="/${lang}/category/${encodeURIComponent(r.category_slug)}/">${esc(categoryLabel(lang,r))}</a>`:''}${verified?` <a class="btn alt" href="/${lang}/author/${encodeURIComponent(slug(r.author_name))}/">${esc(r.author_name)}</a>`:''}</p></article></main>${footer(lang)}`;return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=300'}})}
async function taxonomy(env,lang,type,key){const u=UI[lang],cats=await categories(env,lang),auths=await authors(env,lang);if(type==='category'){const found=cats.find(c=>c.slug===key);if(!found)return null;const rows=await list(env,lang,key,null),title=categoryLabel(lang,found),canonical=`/${lang}/category/${encodeURIComponent(key)}/`,schema=jsonLd({'@context':'https://schema.org','@type':'CollectionPage',name:title,url:`https://wisequotesworld.com${canonical}`,inLanguage:htmlLang(lang)});return new Response(`${baseHead(lang,title,`${title} — Wise Quotes World`,canonical,'',schema)}${header(lang)}<main class="locale13"><div class="container"><p><a href="/${lang}/">← ${esc(u.home)}</a></p><h1>${esc(title)}</h1>${cards(lang,rows)}</div></main>${footer(lang)}`,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=300'}})}const found=auths.find(a=>a.slug===key);if(!found)return null;const rows=await list(env,lang,null,found.author_name),title=found.author_name,canonical=`/${lang}/author/${encodeURIComponent(key)}/`,schema=jsonLd({'@context':'https://schema.org','@type':'CollectionPage',name:title,url:`https://wisequotesworld.com${canonical}`,inLanguage:htmlLang(lang),about:{'@type':'Person',name:title}});return new Response(`${baseHead(lang,title,`${title} — Wise Quotes World`,canonical,'',schema)}${header(lang)}<main class="locale13"><div class="container"><p><a href="/${lang}/">← ${esc(u.home)}</a></p><h1>${esc(title)}</h1>${cards(lang,rows)}</div></main>${footer(lang)}`,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=300'}})}
async function sitemapRows(env){return (await env.DB.prepare(`SELECT qp.language_code,qp.canonical_path,qp.updated_at,qp.content_item_id,ci.category_slug,ci.author_name,ci.attribution_status FROM quote_pages qp JOIN content_items ci ON ci.id=qp.content_item_id WHERE qp.project_id=? AND qp.status='published' ORDER BY qp.language_code,qp.canonical_path`).bind(PROJECT_ID).all()).results||[]}
async function sitemap(env){const rows=await sitemapRows(env);const urls=new Map();const add=(loc,lastmod=null,alts=null)=>urls.set(loc,{loc,lastmod,alts});for(const l of ALL){add(`https://wisequotesworld.com/${l}/`);add(`https://wisequotesworld.com/${l}/quotes/`);add(`https://wisequotesworld.com/${l}/start/`)}const byContent={};for(const r of rows){if(!byContent[r.content_item_id])byContent[r.content_item_id]=[];byContent[r.content_item_id].push(r);if(r.category_slug)add(`https://wisequotesworld.com/${r.language_code}/category/${encodeURIComponent(r.category_slug)}/`);if(r.attribution_status==='verified'&&String(r.author_name||'').trim())add(`https://wisequotesworld.com/${r.language_code}/author/${encodeURIComponent(slug(r.author_name))}/`)}for(const r of rows){const alts=(byContent[r.content_item_id]||[]).map(a=>({lang:htmlLang(a.language_code),href:`https://wisequotesworld.com${a.canonical_path}`}));add(`https://wisequotesworld.com${r.canonical_path}`,r.updated_at,alts)}const body=[...urls.values()].map(x=>`<url><loc>${xml(x.loc)}</loc>${x.lastmod?`<lastmod>${String(x.lastmod).slice(0,10)}</lastmod>`:''}${x.alts?.map(a=>`<xhtml:link rel="alternate" hreflang="${xml(a.lang)}" href="${xml(a.href)}"/>`).join('')||''}</url>`).join('');const out=`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">${body}</urlset>`;return new Response(out,{headers:{'content-type':'application/xml; charset=utf-8','cache-control':'public, max-age=300'}})}
function robots(){return new Response(`User-agent: *\nAllow: /\nDisallow: /admin/\nDisallow: /api/admin/\nDisallow: /ops/\nSitemap: https://wisequotesworld.com/sitemap.xml\n`,{headers:{'content-type':'text/plain; charset=utf-8','cache-control':'public, max-age=3600'}})}
async function seoHealth(env){const rows=await sitemapRows(env),cats=new Set(),auths=new Set();for(const r of rows){if(r.category_slug)cats.add(`${r.language_code}:${r.category_slug}`);if(r.attribution_status==='verified'&&String(r.author_name||'').trim())auths.add(`${r.language_code}:${slug(r.author_name)}`)}return new Response(JSON.stringify({ok:true,locales:ALL.length,published_quote_pages:rows.length,category_pages:cats.size,author_pages:auths.size,sitemap:'https://wisequotesworld.com/sitemap.xml',robots:'https://wisequotesworld.com/robots.txt',indexnow_key_location:`https://wisequotesworld.com/${INDEXNOW_KEY}.txt`}),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function indexNow(request,env){if(request.method!=='POST')return null;if(!env.ADMIN_TOKEN||(request.headers.get('authorization')||'')!==`Bearer ${env.ADMIN_TOKEN}`)return new Response(JSON.stringify({ok:false,error:'unauthorized'}),{status:401,headers:{'content-type':'application/json'}});let body={};try{body=await request.json()}catch{}let urls=Array.isArray(body.urls)?body.urls.filter(x=>typeof x==='string'&&x.startsWith('https://wisequotesworld.com/')):[];if(!urls.length){const rows=await sitemapRows(env);urls=rows.map(r=>`https://wisequotesworld.com${r.canonical_path}`)}urls=[...new Set(urls)].slice(0,10000);const payload={host:'wisequotesworld.com',key:INDEXNOW_KEY,keyLocation:`https://wisequotesworld.com/${INDEXNOW_KEY}.txt`,urlList:urls};const res=await fetch('https://api.indexnow.org/indexnow',{method:'POST',headers:{'content-type':'application/json; charset=utf-8'},body:JSON.stringify(payload)});return new Response(JSON.stringify({ok:res.ok,status:res.status,submitted:urls.length}),{status:res.ok?200:502,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
export async function locale13Site(request,env){if(!env?.DB||request.method==='HEAD')return null;const u=new URL(request.url);if(u.pathname==='/robots.txt'&&request.method==='GET')return robots();if(u.pathname==='/sitemap.xml'&&request.method==='GET')return sitemap(env);if(u.pathname===`/${INDEXNOW_KEY}.txt`&&request.method==='GET')return new Response(INDEXNOW_KEY,{headers:{'content-type':'text/plain; charset=utf-8','cache-control':'public, max-age=86400'}});if(u.pathname==='/ops/readback/seo-health.json'&&request.method==='GET')return seoHealth(env);if(u.pathname==='/api/admin/seo/indexnow')return indexNow(request,env);if(request.method!=='GET')return null;let m=u.pathname.match(/^\/(id|tr|ar)\/?$/);if(m)return home(env,m[1],false);m=u.pathname.match(/^\/(id|tr|ar)\/quotes\/?$/);if(m)return home(env,m[1],true);m=u.pathname.match(/^\/(id|tr|ar)\/quotes\/([^/]+)\/?$/);if(m)return detail(env,m[1],decodeURIComponent(m[2]));m=u.pathname.match(/^\/(id|tr|ar)\/(category|author)\/([^/]+)\/?$/);if(m)return taxonomy(env,m[1],m[2],decodeURIComponent(m[3]));return null}
