const PROJECT_ID='wisequotesworld';
const NEW=['id','tr','ar'];
const ALL=['uk','ru','pl','en','sv','de','es','fr','it','pt','id','tr','ar'];
const NAMES={uk:'Українська',ru:'Русский',pl:'Polski',en:'English',sv:'Svenska',de:'Deutsch',es:'Español',fr:'Français',it:'Italiano',pt:'Português (Brasil)',id:'Bahasa Indonesia',tr:'Türkçe',ar:'العربية'};
const FLAGS={uk:'🇺🇦',ru:'🌐',pl:'🇵🇱',en:'🇬🇧',sv:'🇸🇪',de:'🇩🇪',es:'🇪🇸',fr:'🇫🇷',it:'🇮🇹',pt:'🇧🇷',id:'🇮🇩',tr:'🇹🇷',ar:'🌍'};
const UI={
 id:{title:'Kebijaksanaan yang layak diingat',lead:'Kata-kata abadi, refleksi baru, dan kutipan yang layak dibaca kembali.',all:'Semua kutipan',latest:'Publikasi terbaru',read:'Baca refleksi',empty:'Belum ada kutipan yang diterbitkan.',back:'Kembali ke semua kutipan',topics:'Kutipan dan refleksi',start:'Mulai'},
 tr:{title:'Hatırlamaya değer bilgelik',lead:'Zamansız sözler, yeni düşünceler ve tekrar dönmeye değer alıntılar.',all:'Tüm alıntılar',latest:'Son yayınlar',read:'Düşünceyi oku',empty:'Henüz yayımlanmış alıntı yok.',back:'Tüm alıntılara dön',topics:'Alıntılar ve düşünceler',start:'Başlangıç'},
 ar:{title:'حكمة تستحق أن نتذكرها',lead:'كلمات خالدة وتأملات جديدة واقتباسات تستحق العودة إليها.',all:'جميع الاقتباسات',latest:'أحدث المنشورات',read:'اقرأ التأمل',empty:'لا توجد اقتباسات منشورة بعد.',back:'العودة إلى جميع الاقتباسات',topics:'اقتباسات وتأملات',start:'صفحة البداية'}
};
const CATLABEL={
 discipline:{id:'Disiplin',tr:'Disiplin',ar:'الانضباط'},
 'parents-family':{id:'Orang tua & keluarga',tr:'Anne baba ve aile',ar:'الوالدان والأسرة'},
 'philosophy-strength':{id:'Filsafat & kekuatan',tr:'Felsefe ve güç',ar:'الفلسفة والقوة'},
 identity:{id:'Jati diri',tr:'Kimlik ve özgünlük',ar:'الهوية والأصالة'}
};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function list(env,lang){return (await env.DB.prepare(`SELECT qp.slug,qp.seo_title,qp.meta_description,qp.reflection_title,qp.reflection_body,qp.canonical_path,qp.published_at,cv.adapted_text,ci.author_name,ci.attribution_status,ci.category,ci.category_slug,ci.content_type,ci.id content_id FROM quote_pages qp JOIN content_versions cv ON cv.id=qp.content_version_id JOIN content_items ci ON ci.id=qp.content_item_id WHERE qp.project_id=? AND qp.language_code=? AND qp.status='published' ORDER BY COALESCE(ci.sequence_no,0) DESC,qp.updated_at DESC`).bind(PROJECT_ID,lang).all()).results||[]}
async function one(env,lang,slug){return await env.DB.prepare(`SELECT qp.slug,qp.seo_title,qp.meta_description,qp.reflection_title,qp.reflection_body,qp.canonical_path,qp.published_at,cv.adapted_text,ci.author_name,ci.attribution_status,ci.category,ci.category_slug,ci.content_type,ci.id content_id FROM quote_pages qp JOIN content_versions cv ON cv.id=qp.content_version_id JOIN content_items ci ON ci.id=qp.content_item_id WHERE qp.project_id=? AND qp.language_code=? AND qp.slug=? AND qp.status='published' LIMIT 1`).bind(PROJECT_ID,lang,slug).first()}
async function alternates(env,contentId){return (await env.DB.prepare(`SELECT language_code,canonical_path FROM quote_pages WHERE project_id=? AND content_item_id=? AND status='published'`).bind(PROJECT_ID,contentId).all()).results||[]}
function langMenu(){return ALL.map(l=>`<a href="/${l}/">${FLAGS[l]} ${NAMES[l]}</a>`).join('')}
function baseHead(lang,title,desc,canonical,alts=[]){const dir=lang==='ar'?' dir="rtl"':'';const hreflang=alts.map(a=>`<link rel="alternate" hreflang="${a.language_code==='pt'?'pt-BR':a.language_code}" href="https://wisequotesworld.com${esc(a.canonical_path)}">`).join('');return `<!doctype html><html lang="${lang==='pt'?'pt-BR':lang}"${dir}><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Wise Quotes World</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="index,follow"><link rel="canonical" href="https://wisequotesworld.com${canonical}">${hreflang}<link rel="stylesheet" href="/styles.css"><style>.locale13{padding:72px 0}.locale13 .lead{max-width:760px}.locale13-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin-top:30px}.locale13-card{display:flex;flex-direction:column;text-decoration:none;color:inherit;background:var(--panel);border:1px solid var(--line);border-radius:22px;padding:24px}.locale13-card blockquote{font-family:Georgia,serif;font-size:24px;line-height:1.35;margin:16px 0}.locale13-card small{color:var(--muted)}.locale13-article{max-width:820px;margin:auto}.locale13-article blockquote{font-family:Georgia,serif;font-size:34px;line-height:1.35;margin:28px 0;padding:24px;border-inline-start:3px solid var(--gold2);background:var(--panel)}.locale13-article .reflection{font-size:18px;line-height:1.8;white-space:pre-line}.locale13-nav{display:flex;gap:14px;align-items:center;justify-content:space-between}.locale13-menu{display:flex;gap:8px;flex-wrap:wrap;margin-top:20px}.locale13-menu a{text-decoration:none;font-size:13px;color:var(--muted)}.langmenu{max-height:70vh;overflow-y:auto}.langmenu a{text-decoration:none}@media(max-width:650px){.locale13-grid{grid-template-columns:1fr}.locale13{padding:44px 0}.locale13-article blockquote{font-size:27px}}</style></head><body>`}
function header(lang){return `<header class="header"><div class="container nav"><a class="brand" href="/${lang}/"><span class="mark">W</span><span><strong>Wise Quotes World</strong><small>Timeless words · 13 languages</small></span></a><div class="lang"><button aria-label="Language">${FLAGS[lang]}</button><div class="langmenu">${langMenu()}</div></div></div></header>`}
function footer(lang){return `<footer class="footer"><div class="container"><div class="locale13-menu">${langMenu()}</div><p>© 2026 Wise Quotes World</p></div></footer><script>const lb=document.querySelector('.lang button'),lm=document.querySelector('.langmenu');lb&&lb.addEventListener('click',()=>lm.classList.toggle('show'));</script></body></html>`}
function categoryLabel(lang,row){return CATLABEL[row.category_slug]?.[lang]||row.category||'Wise Quotes World'}
function cards(lang,rows){const u=UI[lang];if(!rows.length)return `<p>${u.empty}</p>`;return `<div class="locale13-grid">${rows.map(r=>`<a class="locale13-card" href="/${lang}/quotes/${encodeURIComponent(r.slug)}/"><small>${esc(categoryLabel(lang,r))}</small><blockquote>“${esc(r.adapted_text)}”</blockquote><b>${r.author_name&&r.attribution_status==='verified'?'— '+esc(r.author_name):'Wise Quotes World'} →</b></a>`).join('')}</div>`}
async function home(env,lang,archive=false){const u=UI[lang],rows=await list(env,lang),title=archive?u.all:u.title;const body=`${baseHead(lang,title,u.lead,archive?`/${lang}/quotes/`:`/${lang}/`)}${header(lang)}<main class="locale13"><div class="container"><span class="kicker">Wise Quotes World</span><h1>${esc(title)}</h1><p class="lead">${esc(u.lead)}</p>${cards(lang,rows)}${!archive?`<p style="margin-top:26px"><a class="btn" href="/${lang}/quotes/">${esc(u.all)}</a> <a class="btn alt" href="/${lang}/start/">${esc(u.start)}</a></p>`:''}</div></main>${footer(lang)}`;return new Response(body,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=300'}})}
async function detail(env,lang,slug){const u=UI[lang],r=await one(env,lang,slug);if(!r)return null;const alts=await alternates(env,r.content_id);const author=r.author_name&&r.attribution_status==='verified'?`<p><strong>— ${esc(r.author_name)}</strong></p>`:'';const arrow=lang==='ar'?'→':'←';const html=`${baseHead(lang,r.seo_title||r.reflection_title||r.adapted_text,r.meta_description||u.lead,r.canonical_path||`/${lang}/quotes/${r.slug}/`,alts)}${header(lang)}<main class="locale13"><article class="container locale13-article"><p><a href="/${lang}/quotes/">${arrow} ${esc(u.back)}</a></p><span class="kicker">Wise Quotes World</span><h1>${esc(r.reflection_title||r.seo_title||u.topics)}</h1><blockquote>“${esc(r.adapted_text)}”</blockquote>${author}<div class="reflection">${esc(r.reflection_body)}</div><p style="margin-top:30px"><a class="btn" href="/${lang}/quotes/">${esc(u.all)}</a></p></article></main>${footer(lang)}`;return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=300'}})}
async function sitemap(env){const rows=(await env.DB.prepare(`SELECT canonical_path,updated_at FROM quote_pages WHERE project_id=? AND status='published' ORDER BY language_code,canonical_path`).bind(PROJECT_ID).all()).results||[];const urls=[...ALL.map(l=>({loc:`https://wisequotesworld.com/${l}/`})),...ALL.map(l=>({loc:`https://wisequotesworld.com/${l}/start/`})),...rows.map(r=>({loc:`https://wisequotesworld.com${r.canonical_path}`,lastmod:r.updated_at}))];const xml=`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(x=>`<url><loc>${esc(x.loc)}</loc>${x.lastmod?`<lastmod>${String(x.lastmod).slice(0,10)}</lastmod>`:''}</url>`).join('')}</urlset>`;return new Response(xml,{headers:{'content-type':'application/xml; charset=utf-8','cache-control':'public, max-age=300'}})}
export async function locale13Site(request,env){if(!env.DB||request.method!=='GET')return null;const u=new URL(request.url);if(u.pathname==='/sitemap.xml')return sitemap(env);let m=u.pathname.match(/^\/(id|tr|ar)\/?$/);if(m)return home(env,m[1],false);m=u.pathname.match(/^\/(id|tr|ar)\/quotes\/?$/);if(m)return home(env,m[1],true);m=u.pathname.match(/^\/(id|tr|ar)\/quotes\/([^/]+)\/?$/);if(m)return detail(env,m[1],decodeURIComponent(m[2]));return null}
