const PROJECT_ID='wisequotesworld';
const LOCALES=['uk','ru','pl','en','sv','de','es','fr','it','pt'];
const HREFLANG={uk:'uk',ru:'ru',pl:'pl',en:'en',sv:'sv',de:'de',es:'es',fr:'fr',it:'it',pt:'pt-BR'};
const HTMLLANG={it:'it',pt:'pt-BR'};
const NAMES={uk:'Українська',ru:'Русский',pl:'Polski',en:'English',sv:'Svenska',de:'Deutsch',es:'Español',fr:'Français',it:'Italiano',pt:'Português (Brasil)'};
const FLAGS={uk:'🇺🇦',ru:'🌐',pl:'🇵🇱',en:'🇬🇧',sv:'🇸🇪',de:'🇩🇪',es:'🇪🇸',fr:'🇫🇷',it:'🇮🇹',pt:'🇧🇷'};
const UI={
  it:{title:'Saggezza da ricordare',lead:'Parole senza tempo, nuove riflessioni e citazioni a cui vale la pena tornare.',all:'Tutte le citazioni',latest:'Ultime pubblicazioni',categories:'Temi',authors:'Autori',read:'Leggi la riflessione',empty:'Non ci sono ancora citazioni pubblicate.',home:'Home',quote:'Citazione',explore:'Esplora',thinkers:'Pensatori'},
  pt:{title:'Sabedoria que vale a pena lembrar',lead:'Palavras atemporais, novas reflexões e citações às quais vale a pena voltar.',all:'Todas as citações',latest:'Publicações recentes',categories:'Temas',authors:'Autores',read:'Leia a reflexão',empty:'Ainda não há citações publicadas.',home:'Início',quote:'Citação',explore:'Explore',thinkers:'Pensadores'}
};
const CATLABEL={
  discipline:{it:'Disciplina',pt:'Disciplina'},
  'parents-family':{it:'Genitori e famiglia',pt:'Pais e família'},
  'philosophy-strength':{it:'Filosofia e forza',pt:'Filosofia e força'},
  'self-authenticity':{it:'Autenticità',pt:'Autenticidade'},
  stoicism:{it:'Stoicismo',pt:'Estoicismo'},
  philosophy:{it:'Filosofia',pt:'Filosofia'}
};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function slug(v){return String(v||'').trim().toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\u0400-\u04ff]+/g,'-').replace(/^-+|-+$/g,'')||'other'}
function paragraphs(text){return String(text||'').split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join('')}
function label(locale,row){return CATLABEL[row.category_slug]?.[locale]||row.category||row.category_slug||'Wise Quotes'}
async function rows(env,locale,category=null,author=null){let sql=`SELECT qp.slug,qp.seo_title,qp.meta_description,qp.reflection_title,qp.reflection_body,qp.canonical_path,qp.published_at,cv.adapted_text,ci.id content_id,ci.author_name,ci.attribution_status,ci.category,ci.category_slug,ci.quote_type,ci.source_work FROM quote_pages qp JOIN content_versions cv ON cv.id=qp.content_version_id JOIN content_items ci ON ci.id=qp.content_item_id WHERE qp.project_id=? AND qp.language_code=? AND qp.status='published'`;const bind=[PROJECT_ID,locale];if(category){sql+=` AND COALESCE(ci.category_slug,'')=?`;bind.push(category)}if(author){sql+=` AND ci.attribution_status='verified' AND ci.author_name=?`;bind.push(author)}sql+=` ORDER BY COALESCE(ci.sequence_no,CAST(SUBSTR(ci.id,3) AS INTEGER),0) DESC,COALESCE(qp.published_at,qp.updated_at) DESC`;return (await env.DB.prepare(sql).bind(...bind).all()).results||[]}
async function categories(env,locale){return (await env.DB.prepare(`SELECT COALESCE(NULLIF(ci.category_slug,''),'other') slug,COALESCE(NULLIF(ci.category,''),NULLIF(ci.category_slug,''),'Other') label,COUNT(*) count FROM quote_pages qp JOIN content_items ci ON ci.id=qp.content_item_id WHERE qp.project_id=? AND qp.language_code=? AND qp.status='published' GROUP BY COALESCE(NULLIF(ci.category_slug,''),'other'),COALESCE(NULLIF(ci.category,''),NULLIF(ci.category_slug,''),'Other') ORDER BY count DESC,label`).bind(PROJECT_ID,locale).all()).results||[]}
async function authors(env,locale){const a=(await env.DB.prepare(`SELECT ci.author_name,COUNT(*) count FROM quote_pages qp JOIN content_items ci ON ci.id=qp.content_item_id WHERE qp.project_id=? AND qp.language_code=? AND qp.status='published' AND ci.attribution_status='verified' AND TRIM(COALESCE(ci.author_name,''))<>'' GROUP BY ci.author_name ORDER BY count DESC,ci.author_name`).bind(PROJECT_ID,locale).all()).results||[];return a.map(x=>({...x,slug:slug(x.author_name)}))}
async function equivalents(env,contentId){return (await env.DB.prepare(`SELECT language_code,canonical_path FROM quote_pages WHERE project_id=? AND content_item_id=? AND status='published' ORDER BY language_code`).bind(PROJECT_ID,contentId).all()).results||[]}
function localeLinks(){return LOCALES.map(l=>`<a href="/${l}/"><span>${FLAGS[l]}</span>${NAMES[l]}</a>`).join('')}
function hreflangLinks(paths,canonical){const by=new Map((paths||[]).map(x=>[x.language_code,x.canonical_path]));let out='';for(const l of LOCALES){const p=by.get(l);if(p)out+=`<link rel="alternate" hreflang="${HREFLANG[l]}" href="https://wisequotesworld.com${esc(p)}">`}const en=by.get('en');if(en)out+=`<link rel="alternate" hreflang="x-default" href="https://wisequotesworld.com${esc(en)}">`;return out||`<link rel="alternate" hreflang="${HREFLANG[canonical.locale]}" href="${esc(canonical.url)}">`}
function shell(locale,{title,description,canonicalPath,body,alternates=[]}){const u=UI[locale],canonical=`https://wisequotesworld.com${canonicalPath}`;return `<!doctype html><html lang="${HTMLLANG[locale]}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Wise Quotes World</title><meta name="description" content="${esc(description||u.lead)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${esc(canonical)}">${hreflangLinks(alternates,{locale,url:canonical})}<link rel="stylesheet" href="/styles.css"><style>.live{display:flex;flex-direction:column;text-decoration:none;color:inherit}.live .author{margin-top:auto;display:flex;justify-content:space-between}.langmenu a,.topic,.author-card,.all-link,.hero-latest{text-decoration:none}.all-link{color:var(--gold2);font-weight:800}.topic,.author-card{color:inherit}.empty{padding:26px;border:1px solid var(--line);border-radius:20px;background:var(--panel);color:var(--muted)}.article-wrap{max-width:860px;margin:0 auto;padding:74px 20px}.article-head{margin-bottom:34px}.article-head h1{font-family:Georgia,serif;font-size:clamp(34px,6vw,58px);line-height:1.08;margin:14px 0}.article-quote{font-family:Georgia,serif;font-size:clamp(26px,4vw,38px);line-height:1.35;padding:30px;border:1px solid var(--line);border-radius:22px;background:var(--panel);margin:30px 0}.article-copy{font-size:18px;line-height:1.78;color:#d8dbe2}.article-copy p{margin:0 0 22px}.crumbs{color:var(--muted);font-size:14px}.crumbs a{color:inherit}.source{color:var(--muted);font-size:14px;margin-top:26px}.brand small{white-space:nowrap}@media(max-width:580px){.hero{padding-top:54px}.hero h1{font-size:44px}.article-wrap{padding-top:48px}}</style></head><body><header class="header"><div class="container nav"><a class="brand" href="/${locale}/"><span class="mark">W</span><span><strong>Wise Quotes World</strong><small>Timeless words · ten languages</small></span></a><button class="menu" aria-label="Menu">☰</button><nav class="navlinks"><a href="/${locale}/quotes/">${esc(u.all)}</a><a href="/${locale}/#authors">${esc(u.authors)}</a></nav><div class="lang"><button aria-label="Language">${FLAGS[locale]}</button><div class="langmenu">${localeLinks()}</div></div></div></header>${body}<footer class="footer"><div class="container footer-grid"><div>© 2026 Wise Quotes World</div><div><a href="/${locale}/start/">Start</a> · <a href="/${locale}/quotes/">${esc(u.all)}</a></div></div></footer><script>const lb=document.querySelector('.lang button'),lm=document.querySelector('.langmenu');lb&&lb.addEventListener('click',()=>lm.classList.toggle('show'));const mb=document.querySelector('.menu'),nl=document.querySelector('.navlinks');mb&&mb.addEventListener('click',()=>nl.classList.toggle('open'));</script></body></html>`}
function cards(locale,a){return `<div class="cards">${a.map(x=>`<a class="card live" href="/${locale}/quotes/${encodeURIComponent(x.slug)}/"><span class="tag">${esc(label(locale,x))}</span><blockquote>“${esc(x.adapted_text)}”</blockquote><div class="author"><span>${x.author_name&&x.attribution_status==='verified'?'— '+esc(x.author_name):'Wise Quotes World'}</span><b>→</b></div></a>`).join('')}</div>`}
function home(locale,a,cats,auts){const u=UI[locale],newest=a[0];const hero=newest?`<a class="hero-latest" href="/${locale}/quotes/${encodeURIComponent(newest.slug)}/"><aside class="quote-card"><span class="kicker">${esc(u.latest)}</span><blockquote>“${esc(newest.adapted_text)}”</blockquote><footer>${newest.author_name&&newest.attribution_status==='verified'?esc(newest.author_name):'Wise Quotes World'} →</footer></aside></a>`:`<aside class="quote-card"><blockquote>Wise Quotes World</blockquote></aside>`;return `<main><section class="hero"><div class="container hero-grid"><div><span class="kicker">Wise Quotes World</span><h1>${esc(u.title)}<br><span>Every day.</span></h1><p class="lead">${esc(u.lead)}</p><div class="actions"><a class="btn" href="#quotes">${esc(u.latest)}</a><a class="btn alt" href="/${locale}/quotes/">${esc(u.all)}</a></div></div>${hero}</div></section><section class="section" id="quotes"><div class="container"><div class="section-head"><div><span class="kicker">Latest</span><h2>${esc(u.latest)}</h2></div><a class="all-link" href="/${locale}/quotes/">${esc(u.all)} →</a></div>${a.length?cards(locale,a):`<div class="empty">${esc(u.empty)}</div>`}</div></section>${cats.length?`<section class="section"><div class="container"><div class="section-head"><div><span class="kicker">${esc(u.explore)}</span><h2>${esc(u.categories)}</h2></div></div><div class="grid4">${cats.map(c=>`<a class="topic" href="/${locale}/category/${encodeURIComponent(c.slug)}/"><span>✦</span><h3>${esc(CATLABEL[c.slug]?.[locale]||c.label)}</h3><p>${c.count}</p></a>`).join('')}</div></div></section>`:''}${auts.length?`<section class="section authors" id="authors"><div class="container"><div class="section-head"><div><span class="kicker">${esc(u.thinkers)}</span><h2>${esc(u.authors)}</h2></div></div><div class="grid4">${auts.map(a=>`<a class="author-card" href="/${locale}/author/${encodeURIComponent(a.slug)}/"><span>✦</span><h3>${esc(a.author_name)}</h3><p>${a.count}</p></a>`).join('')}</div></div></section>`:''}</main>`}
function archive(locale,a,title){const u=UI[locale];return `<main><section class="section"><div class="container"><div class="section-head"><div><span class="kicker">Wise Quotes World</span><h1>${esc(title)}</h1></div><a class="all-link" href="/${locale}/">← ${esc(u.home)}</a></div>${a.length?cards(locale,a):`<div class="empty">${esc(u.empty)}</div>`}</div></section></main>`}
function article(locale,row,alternates){const u=UI[locale],author=row.author_name&&row.attribution_status==='verified'?row.author_name:null;return shell(locale,{title:row.seo_title||row.reflection_title||row.adapted_text,description:row.meta_description,canonicalPath:row.canonical_path,alternates,body:`<main class="article-wrap"><div class="crumbs"><a href="/${locale}/">${esc(u.home)}</a> / <a href="/${locale}/quotes/">${esc(u.all)}</a></div><header class="article-head"><span class="kicker">${esc(label(locale,row))}</span><h1>${esc(row.reflection_title||row.seo_title||u.quote)}</h1></header><blockquote class="article-quote">${esc(row.adapted_text)}${author?`<footer>— ${esc(author)}</footer>`:''}</blockquote><article class="article-copy">${paragraphs(row.reflection_body)}</article>${row.source_work&&author?`<p class="source">${locale==='it'?'Fonte':'Fonte'}: ${esc(row.source_work)}</p>`:''}<div class="actions"><a class="btn alt" href="/${locale}/quotes/">${esc(u.all)} →</a></div></main>`})}
async function sitemap(env){const pages=(await env.DB.prepare(`SELECT language_code,canonical_path,updated_at,published_at FROM quote_pages WHERE project_id=? AND status='published' AND language_code IN ('uk','ru','pl','en','sv','de','es','fr','it','pt') ORDER BY language_code,canonical_path`).bind(PROJECT_ID).all()).results||[];const urls=[];for(const l of LOCALES){urls.push({loc:`https://wisequotesworld.com/${l}/`,lastmod:null});urls.push({loc:`https://wisequotesworld.com/${l}/quotes/`,lastmod:null});urls.push({loc:`https://wisequotesworld.com/${l}/start/`,lastmod:null})}for(const p of pages)urls.push({loc:`https://wisequotesworld.com${p.canonical_path}`,lastmod:(p.updated_at||p.published_at||'').slice(0,10)||null});const xml=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(x=>`  <url><loc>${esc(x.loc)}</loc>${x.lastmod?`<lastmod>${x.lastmod}</lastmod>`:''}</url>`).join('\n')}\n</urlset>`;return new Response(xml,{headers:{'content-type':'application/xml; charset=utf-8','cache-control':'public, max-age=900'}})}
export async function newLocalesSite(request,env){const url=new URL(request.url);if(url.pathname==='/sitemap.xml'&&request.method==='GET'&&env?.DB)return sitemap(env);const m=url.pathname.match(/^\/(it|pt)(?:\/(.*))?$/);if(!m||request.method!=='GET')return null;if(!env?.DB)return new Response('Database unavailable',{status:503});const locale=m[1],rest=(m[2]||'').replace(/\/+$/,'');if(!rest){const a=await rows(env,locale),c=await categories(env,locale),au=await authors(env,locale);return new Response(shell(locale,{title:UI[locale].title,description:UI[locale].lead,canonicalPath:`/${locale}/`,body:home(locale,a,c,au)}),{headers:{'content-type':'text/html; charset=utf-8'}})}if(rest==='quotes'){const a=await rows(env,locale);return new Response(shell(locale,{title:UI[locale].all,description:UI[locale].lead,canonicalPath:`/${locale}/quotes/`,body:archive(locale,a,UI[locale].all)}),{headers:{'content-type':'text/html; charset=utf-8'}})}const qm=rest.match(/^quotes\/([^/]+)$/);if(qm){const row=await env.DB.prepare(`SELECT qp.*,cv.adapted_text,ci.id content_id,ci.author_name,ci.attribution_status,ci.category,ci.category_slug,ci.quote_type,ci.source_work FROM quote_pages qp JOIN content_versions cv ON cv.id=qp.content_version_id JOIN content_items ci ON ci.id=qp.content_item_id WHERE qp.project_id=? AND qp.language_code=? AND qp.slug=? AND qp.status='published' LIMIT 1`).bind(PROJECT_ID,locale,decodeURIComponent(qm[1])).first();if(!row)return new Response('Not found',{status:404});return new Response(article(locale,row,await equivalents(env,row.content_id)),{headers:{'content-type':'text/html; charset=utf-8'}})}const cm=rest.match(/^category\/([^/]+)$/);if(cm){const key=decodeURIComponent(cm[1]),a=await rows(env,locale,key);const title=CATLABEL[key]?.[locale]||key;return new Response(shell(locale,{title,description:UI[locale].lead,canonicalPath:`/${locale}/category/${encodeURIComponent(key)}/`,body:archive(locale,a,title)}),{headers:{'content-type':'text/html; charset=utf-8'}})}const am=rest.match(/^author\/([^/]+)$/);if(am){const key=decodeURIComponent(am[1]),all=await authors(env,locale),found=all.find(x=>x.slug===key);if(!found)return new Response('Not found',{status:404});const a=await rows(env,locale,null,found.author_name);return new Response(shell(locale,{title:found.author_name,description:UI[locale].lead,canonicalPath:`/${locale}/author/${encodeURIComponent(key)}/`,body:archive(locale,a,found.author_name)}),{headers:{'content-type':'text/html; charset=utf-8'}})}return null}
