const PROJECT_ID='wisequotesworld';
const BRAND='Wise Quotes World';
const BASE='https://wisequotesworld.com';

const COPY={
 uk:{subject:'Wise Quotes World — нові думки за останні два тижні',preheader:'Нові цитати й роздуми, які варто забрати із собою.',eyebrow:'Дайджест · раз на два тижні',title:'Нові думки, до яких варто повернутися',intro:'Ми зібрали нові цитати й роздуми Wise Quotes World за останній період. Без зайвого шуму — лише слова, над якими хочеться затриматися.',read:'Читати',all:'Переглянути всі цитати',footer:'Ви отримали цей лист, бо підписалися на українську розсилку Wise Quotes World.',unsub:'Відписатися від розсилки'},
 ru:{subject:'Wise Quotes World — новые мысли за последние две недели',preheader:'Новые цитаты и размышления, к которым стоит вернуться.',eyebrow:'Дайджест · раз в две недели',title:'Новые мысли, к которым стоит вернуться',intro:'Мы собрали новые цитаты и размышления Wise Quotes World за последнее время. Без лишнего шума — только слова, над которыми хочется задержаться.',read:'Читать',all:'Посмотреть все цитаты',footer:'Вы получили это письмо, потому что подписались на русскую рассылку Wise Quotes World.',unsub:'Отписаться от рассылки'},
 pl:{subject:'Wise Quotes World — nowe myśli z ostatnich dwóch tygodni',preheader:'Nowe cytaty i refleksje, do których warto wrócić.',eyebrow:'Biuletyn · co dwa tygodnie',title:'Nowe myśli, do których warto wrócić',intro:'Zebraliśmy nowe cytaty i refleksje Wise Quotes World z ostatniego czasu. Bez zbędnego szumu — tylko słowa, przy których warto zatrzymać się na chwilę.',read:'Czytaj',all:'Zobacz wszystkie cytaty',footer:'Otrzymujesz tę wiadomość, ponieważ zapisałeś(-aś) się na polski biuletyn Wise Quotes World.',unsub:'Wypisz się'},
 en:{subject:'Wise Quotes World — new thoughts from the past two weeks',preheader:'New quotes and reflections worth carrying with you.',eyebrow:'Digest · every two weeks',title:'New thoughts worth returning to',intro:'We gathered the latest Wise Quotes World quotes and reflections in one quiet digest. No noise — just words worth sitting with for a moment.',read:'Read',all:'Explore all quotes',footer:'You are receiving this email because you subscribed to the English Wise Quotes World newsletter.',unsub:'Unsubscribe'},
 sv:{subject:'Wise Quotes World — nya tankar från de senaste två veckorna',preheader:'Nya citat och reflektioner värda att bära med sig.',eyebrow:'Brev · varannan vecka',title:'Nya tankar värda att återvända till',intro:'Vi har samlat de senaste citaten och reflektionerna från Wise Quotes World i ett lugnt brev. Inget brus — bara ord som är värda att stanna upp vid.',read:'Läs',all:'Se alla citat',footer:'Du får det här mejlet eftersom du prenumererar på Wise Quotes Worlds svenska utskick.',unsub:'Avsluta prenumerationen'},
 de:{subject:'Wise Quotes World — neue Gedanken aus den letzten zwei Wochen',preheader:'Neue Zitate und Gedanken, zu denen es sich zurückzukehren lohnt.',eyebrow:'Digest · alle zwei Wochen',title:'Neue Gedanken, zu denen es sich zurückzukehren lohnt',intro:'Wir haben die neuesten Zitate und Gedanken von Wise Quotes World in einem ruhigen Digest gesammelt. Kein unnötiger Lärm — nur Worte, bei denen es sich lohnt, kurz innezuhalten.',read:'Lesen',all:'Alle Zitate ansehen',footer:'Sie erhalten diese E-Mail, weil Sie den deutschen Newsletter von Wise Quotes World abonniert haben.',unsub:'Abbestellen'},
 es:{subject:'Wise Quotes World — nuevas reflexiones de las últimas dos semanas',preheader:'Nuevas citas y reflexiones que merece la pena guardar.',eyebrow:'Selección · cada dos semanas',title:'Nuevas ideas a las que merece la pena volver',intro:'Hemos reunido las últimas citas y reflexiones de Wise Quotes World en una selección tranquila. Sin ruido innecesario: solo palabras que invitan a detenerse un momento.',read:'Leer',all:'Ver todas las citas',footer:'Recibes este correo porque te suscribiste al boletín en español de Wise Quotes World.',unsub:'Darse de baja'},
 fr:{subject:'Wise Quotes World — nouvelles réflexions des deux dernières semaines',preheader:'De nouvelles citations et réflexions à garder près de soi.',eyebrow:'Sélection · toutes les deux semaines',title:'De nouvelles pensées auxquelles revenir',intro:'Nous avons réuni les dernières citations et réflexions de Wise Quotes World dans une sélection sobre. Pas de bruit inutile — seulement des mots qui méritent qu’on s’y attarde.',read:'Lire',all:'Voir toutes les citations',footer:'Vous recevez cet e-mail parce que vous êtes inscrit(e) à la newsletter française de Wise Quotes World.',unsub:'Se désabonner'},
 it:{subject:'Wise Quotes World — nuovi pensieri delle ultime due settimane',preheader:'Nuove citazioni e riflessioni da portare con sé.',eyebrow:'Raccolta · ogni due settimane',title:'Nuovi pensieri a cui vale la pena tornare',intro:'Abbiamo raccolto le ultime citazioni e riflessioni di Wise Quotes World in una selezione essenziale. Niente rumore inutile — solo parole su cui vale la pena soffermarsi.',read:'Leggi',all:'Scopri tutte le citazioni',footer:'Ricevi questa e-mail perché ti sei iscritto alla newsletter italiana di Wise Quotes World.',unsub:'Annulla iscrizione'},
 pt:{subject:'Wise Quotes World — novas reflexões das últimas duas semanas',preheader:'Novas citações e reflexões que vale a pena guardar.',eyebrow:'Seleção · a cada duas semanas',title:'Novas ideias às quais vale a pena voltar',intro:'Reunimos as citações e reflexões mais recentes do Wise Quotes World em uma seleção tranquila. Sem ruído desnecessário — apenas palavras que merecem alguns instantes de atenção.',read:'Ler',all:'Ver todas as citações',footer:'Você recebeu este e-mail porque se inscreveu na newsletter em português do Brasil do Wise Quotes World.',unsub:'Cancelar inscrição'},
 id:{subject:'Wise Quotes World — pemikiran baru dari dua minggu terakhir',preheader:'Kutipan dan refleksi baru yang layak disimpan.',eyebrow:'Pilihan · setiap dua minggu',title:'Pemikiran baru yang layak direnungkan kembali',intro:'Kami merangkum kutipan dan refleksi terbaru Wise Quotes World dalam satu pilihan yang tenang. Tanpa kebisingan yang tidak perlu — hanya kata-kata yang layak direnungkan sejenak.',read:'Baca',all:'Lihat semua kutipan',footer:'Anda menerima e-mail ini karena berlangganan newsletter Wise Quotes World dalam Bahasa Indonesia.',unsub:'Berhenti berlangganan'},
 tr:{subject:'Wise Quotes World — son iki haftadan yeni düşünceler',preheader:'Yanınızda taşımaya değer yeni alıntılar ve düşünceler.',eyebrow:'Seçki · iki haftada bir',title:'Dönüp yeniden düşünmeye değer yeni fikirler',intro:'Wise Quotes World’ün son alıntı ve düşüncelerini sade bir seçkide bir araya getirdik. Gereksiz gürültü yok — yalnızca üzerinde biraz durmaya değer sözler.',read:'Oku',all:'Tüm alıntıları gör',footer:'Bu e-postayı Wise Quotes World Türkçe bültenine abone olduğunuz için alıyorsunuz.',unsub:'Abonelikten çık'},
 ar:{subject:'Wise Quotes World — تأملات جديدة من الأسبوعين الماضيين',preheader:'اقتباسات وتأملات جديدة تستحق أن تبقى معك.',eyebrow:'مختارات · كل أسبوعين',title:'أفكار جديدة تستحق أن نعود إليها',intro:'جمعنا أحدث اقتباسات وتأملات Wise Quotes World في رسالة هادئة ومختصرة. بلا ضجيج زائد — فقط كلمات تستحق أن نتوقف عندها قليلًا.',read:'اقرأ',all:'عرض جميع الاقتباسات',footer:'تصلك هذه الرسالة لأنك اشتركت في النشرة العربية من Wise Quotes World.',unsub:'إلغاء الاشتراك'}
};

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
function normLocale(v){const l=String(v||'en').toLowerCase();return COPY[l]?l:'en'}
function strip(v){return String(v||'').replace(/\s+/g,' ').trim()}

export async function latestDigestArticles(env,languageCode,limit=5){
 const locale=normLocale(languageCode);
 const n=Math.max(3,Math.min(6,Number(limit)||5));
 const q=`SELECT qp.content_item_id,qp.slug,qp.seo_title,qp.meta_description,qp.canonical_path,cv.adapted_text,ci.author_name,ci.attribution_status,ci.sequence_no
 FROM quote_pages qp
 JOIN content_versions cv ON cv.id=qp.content_version_id
 JOIN content_items ci ON ci.id=qp.content_item_id
 WHERE qp.project_id=?
   AND qp.language_code=?
   AND qp.status='published'
   AND ci.project_id=?
   AND ci.status='published'
 ORDER BY COALESCE(ci.sequence_no,CAST(SUBSTR(ci.id,3) AS INTEGER),0) DESC
 LIMIT ?`;
 const r=await env.DB.prepare(q).bind(PROJECT_ID,locale,PROJECT_ID,n).all();
 return r.results||[];
}

export function digestCopy(languageCode){return COPY[normLocale(languageCode)]}

export function renderDigest({languageCode,articles,unsubscribeToken}){
 const locale=normLocale(languageCode),c=COPY[locale],rtl=locale==='ar';
 const unsubscribe=`${BASE}/newsletter/unsubscribe?token=${encodeURIComponent(unsubscribeToken||'')}`;
 const cards=(articles||[]).map(a=>{
   const href=a.canonical_path?`${BASE}${a.canonical_path}`:`${BASE}/${locale}/quotes/${encodeURIComponent(a.slug)}/`;
   const quote=strip(a.adapted_text||a.seo_title||'');
   const desc=strip(a.meta_description||'');
   const author=a.author_name&&a.attribution_status==='verified'?`— ${a.author_name}`:BRAND;
   return `<tr><td style="padding:0 0 18px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#151821;border:1px solid #383426;border-radius:16px"><tr><td style="padding:22px"><div style="font-family:Georgia,'Times New Roman',serif;font-size:22px;line-height:1.38;color:#f5f2ea;margin:0 0 12px">“${esc(quote)}”</div><div style="font-size:13px;color:#d9bd73;margin-bottom:12px">${esc(author)}</div>${desc?`<div style="font-size:15px;line-height:1.6;color:#bdb9af;margin-bottom:18px">${esc(desc)}</div>`:''}<a href="${esc(href)}" style="display:inline-block;background:#e4c576;color:#111;text-decoration:none;padding:11px 17px;border-radius:9px;font-size:14px;font-weight:700">${esc(c.read)} →</a></td></tr></table></td></tr>`;
 }).join('');
 const html=`<!doctype html><html lang="${locale}"${rtl?' dir="rtl"':''}><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(c.subject)}</title></head><body style="margin:0;padding:0;background:#0b0d12;color:#f5f2ea;font-family:Arial,sans-serif;${rtl?'direction:rtl;text-align:right;':''}"><div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent">${esc(c.preheader)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#0b0d12"><tr><td align="center" style="padding:28px 14px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px"><tr><td style="padding:28px;background:#11151f;border:1px solid #5f5133;border-radius:20px"><div style="font-size:27px;font-weight:800;color:#e4c576;margin-bottom:8px">${BRAND}</div><div style="font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:#a99a73;margin-bottom:26px">${esc(c.eyebrow)}</div><h1 style="font-family:Georgia,'Times New Roman',serif;font-size:30px;line-height:1.2;color:#f5f2ea;margin:0 0 16px">${esc(c.title)}</h1><p style="font-size:16px;line-height:1.7;color:#c9c5bc;margin:0 0 28px">${esc(c.intro)}</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0">${cards}</table><div style="text-align:center;margin:8px 0 30px"><a href="${BASE}/${locale}/quotes/" style="display:inline-block;border:1px solid #e4c576;color:#e4c576;text-decoration:none;padding:12px 18px;border-radius:9px;font-size:14px;font-weight:700">${esc(c.all)}</a></div><div style="border-top:1px solid #343434;padding-top:18px;font-size:12px;line-height:1.6;color:#8f8b83"><div>${esc(c.footer)}</div><div style="margin-top:8px"><a href="${esc(unsubscribe)}" style="color:#aaa">${esc(c.unsub)}</a></div><div style="margin-top:8px">© 2026 ${BRAND}</div></div></td></tr></table></td></tr></table></body></html>`;
 const text=[BRAND,c.title,c.intro,...(articles||[]).flatMap(a=>{const href=a.canonical_path?`${BASE}${a.canonical_path}`:`${BASE}/${locale}/quotes/${encodeURIComponent(a.slug)}/`;const author=a.author_name&&a.attribution_status==='verified'?`— ${a.author_name}`:BRAND;return [`“${strip(a.adapted_text||a.seo_title||'')}”`,author,href]}),`${c.all}: ${BASE}/${locale}/quotes/`,`${c.unsub}: ${unsubscribe}`].join('\n\n');
 return {locale,subject:c.subject,preheader:c.preheader,htmlContent:html,textContent:text,unsubscribe};
}
