import {prepareBuffer022031,readBuffer022031} from './prepared_buffer_022_031.js';

const PROJECT='wisequotesworld';
const SOCIAL=['uk','ru','pl','en','sv','de','es','fr'];
const TS=()=>new Date().toISOString();

const COPY={
 uk:{t2:'Іноді одна точна думка корисніша за десяток загальних порад.',t3:'Який конкретний крок із цієї думки можна застосувати сьогодні?',pin:'Перевірена цитата та коротка рефлексія про її сенс у повсякденному житті.',video:'Відеоверсія цитати з повною рефлексією за посиланням на статтю цією ж мовою.'},
 ru:{t2:'Иногда одна точная мысль полезнее десятка общих советов.',t3:'Какой конкретный шаг из этой мысли можно применить сегодня?',pin:'Проверенная цитата и краткая рефлексия о её смысле в повседневной жизни.',video:'Видеоверсия цитаты с полной рефлексией по ссылке на статью на этом же языке.'},
 pl:{t2:'Czasem jedna precyzyjna myśl jest cenniejsza niż dziesięć ogólnych porad.',t3:'Jaki konkretny krok z tej myśli możesz zastosować już dziś?',pin:'Zweryfikowany cytat i krótka refleksja o jego znaczeniu w codziennym życiu.',video:'Wersja wideo cytatu z pełną refleksją pod linkiem do artykułu w tym samym języku.'},
 en:{t2:'Sometimes one precise idea is more useful than ten general pieces of advice.',t3:'What concrete step from this idea could you apply today?',pin:'A verified quote with a concise reflection on what it can mean in everyday life.',video:'A video version of the quote, with the full reflection available through the same-language article.'},
 sv:{t2:'Ibland är en exakt tanke mer värdefull än tio allmänna råd.',t3:'Vilket konkret steg ur den här tanken kan du använda redan i dag?',pin:'Ett verifierat citat med en kort reflektion över vad det kan betyda i vardagen.',video:'En videoversion av citatet med hela reflektionen i artikeln på samma språk.'},
 de:{t2:'Manchmal ist ein präziser Gedanke hilfreicher als zehn allgemeine Ratschläge.',t3:'Welchen konkreten Schritt aus diesem Gedanken kannst du heute umsetzen?',pin:'Ein geprüftes Zitat mit einer kurzen Reflexion über seine Bedeutung im Alltag.',video:'Die Videoversion des Zitats mit der vollständigen Reflexion im Artikel derselben Sprache.'},
 es:{t2:'A veces una idea precisa vale más que diez consejos generales.',t3:'¿Qué paso concreto de esta idea puedes aplicar hoy?',pin:'Una cita verificada con una breve reflexión sobre lo que puede significar en la vida cotidiana.',video:'Versión en vídeo de la cita con la reflexión completa en el artículo del mismo idioma.'},
 fr:{t2:'Parfois, une pensée précise vaut mieux que dix conseils généraux.',t3:'Quel geste concret pouvez-vous tirer de cette idée aujourd’hui ?',pin:'Une citation vérifiée accompagnée d’une brève réflexion sur son sens dans la vie quotidienne.',video:'Version vidéo de la citation, avec la réflexion complète dans l’article de la même langue.'}
};

function baseQuote(v){return String(v||'').trim()}
async function upsert(env,id,lang,key,text,ts){await env.DB.prepare(`INSERT INTO content_outputs(id,project_id,content_item_id,language_code,output_key,output_text,status,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(content_item_id,language_code,output_key) DO UPDATE SET output_text=excluded.output_text,status=excluded.status,updated_at=excluded.updated_at`).bind(`${id}_${lang}_${key}`,PROJECT,id,lang,key,text,'ready',ts).run()}

async function patchNativeOutputs(env){const ts=TS();for(let n=22;n<=31;n++){const id=`WQ${String(n).padStart(3,'0')}`;for(const lang of SOCIAL){const c=COPY[lang];const v=await env.DB.prepare(`SELECT adapted_text FROM content_versions WHERE content_id=? AND language_code=? ORDER BY version DESC LIMIT 1`).bind(id,lang).first();const u=await env.DB.prepare(`SELECT output_text FROM content_outputs WHERE project_id=? AND content_item_id=? AND language_code=? AND output_key='article_url' LIMIT 1`).bind(PROJECT,id,lang).first();const p=await env.DB.prepare(`SELECT output_text FROM content_outputs WHERE project_id=? AND content_item_id=? AND language_code=? AND output_key='pinterest_title' LIMIT 1`).bind(PROJECT,id,lang).first();if(!v?.adapted_text||!u?.output_text)continue;const quote=baseQuote(v.adapted_text),url=u.output_text;const threads=[`${quote}\n\n${url}`,`${c.t2}\n\n${url}`,`${c.t3}\n\n${quote}\n\n${url}`].join('\n\n---\n\n');await upsert(env,id,lang,'threads',threads,ts);await upsert(env,id,lang,'pinterest_description',`${quote} ${c.pin}`,ts);await upsert(env,id,lang,'pinterest_video_title',p?.output_text||quote.slice(0,95),ts);await upsert(env,id,lang,'pinterest_video_description',`${quote} ${c.video}`,ts)}}return{ok:true}}

export async function prepareBuffer022031V2(env){const first=await prepareBuffer022031(env);if(!first?.ok)return{ok:false,stage:'prepare',first};const patched=await patchNativeOutputs(env);const readback=await readBuffer022031(env);return{ok:!!readback?.ok,first,patched,readback}}
