const PROJECT='wisequotesworld';
const LANGS=['uk','ru','pl','en','sv','de','es','fr','it','pt'];
const LANGUAGE={uk:'Ukrainian',ru:'Russian',pl:'Polish',en:'English',sv:'Swedish',de:'German',es:'Spanish',fr:'French',it:'Italian',pt:'Brazilian Portuguese'};
const TS=()=>new Date().toISOString();

const FIX={
 'WQ023:ru':'«Без надежды всё же буду надеяться. Буду жить! Прочь, печальные мысли!» — Леся Украинка',
 'WQ023:pl':'„Choć bez nadziei, wciąż będę mieć nadzieję. Będę żyć! Precz, smutne myśli!” — Łesia Ukrainka',
 'WQ023:es':'«Incluso sin esperanza, seguiré esperando. ¡Viviré! ¡Lejos de mí, pensamientos tristes!» — Lesia Ukrainka',
 'WQ023:pt':'“Mesmo sem esperança, continuarei a ter esperança. Viverei! Longe de mim, pensamentos tristes!” — Lesya Ukrainka',
 'WQ025:uk':'«Де розум вільний від страху, а голова піднята високо». — Рабіндранат Тагор',
 'WQ025:ru':'«Где разум свободен от страха, а голова поднята высоко». — Рабиндранат Тагор',
 'WQ025:pl':'„Gdzie umysł jest wolny od lęku, a głowa uniesiona wysoko.” — Rabindranath Tagore',
 'WQ025:pt':'“Onde a mente é livre do medo e a cabeça se mantém erguida.” — Rabindranath Tagore',
 'WQ026:pl':'„Moim rzemiosłem i moją sztuką jest życie.” — Michel de Montaigne',
 'WQ026:en':'“Living is my trade and my art.” — Michel de Montaigne',
 'WQ026:de':'„Mein Handwerk und meine Kunst bestehen darin, zu leben.“ — Michel de Montaigne',
 'WQ026:es':'«Mi oficio y mi arte consisten en vivir». — Michel de Montaigne',
 'WQ026:it':'«Il mio mestiere e la mia arte consistono nel vivere.» — Michel de Montaigne',
 'WQ026:pt':'“Meu ofício e minha arte consistem em viver.” — Michel de Montaigne',
 'WQ027:es':'«Cuando ya no podemos cambiar una situación, se nos plantea el desafío de cambiarnos a nosotros mismos». — Viktor E. Frankl',
 'WQ028:uk':'«Не те щоб у нас було мало часу — ми багато його марнуємо». — Сенека',
 'WQ028:ru':'«Дело не в том, что у нас мало времени, — мы много его теряем». — Сенека',
 'WQ028:pl':'„Nie chodzi o to, że mamy mało czasu — wiele go tracimy.” — Seneka',
 'WQ028:pt':'“Não é que tenhamos pouco tempo; é que desperdiçamos muito dele.” — Sêneca',
 'WQ029:sv':'”Jag lärde mig att mod inte är frånvaro av rädsla, utan seger över den.” — Nelson Mandela',
 'WQ030:uk':'«Немає ні воріт, ні замка, ні засуву, здатних замкнути свободу мого розуму». — Вірджинія Вулф',
 'WQ030:ru':'«Нет ни ворот, ни замка, ни засова, способных запереть свободу моего разума». — Вирджиния Вулф',
 'WQ030:pl':'„Nie ma bramy, zamka ani zasuwy, które mogłyby zamknąć wolność mojego umysłu.” — Virginia Woolf',
 'WQ030:es':'«No hay puerta, cerradura ni cerrojo que pueda encerrar la libertad de mi mente». — Virginia Woolf',
 'WQ030:fr':'«Il n’existe ni grille, ni serrure, ni verrou capables d’enfermer la liberté de mon esprit.» — Virginia Woolf',
 'WQ030:it':'«Non esistono cancello, serratura o chiavistello capaci di imprigionare la libertà della mia mente.» — Virginia Woolf'
};

const SCENE={
 WQ023:'A symbolic spring scene in a quiet literary garden. A small classical stone bust of an anonymous woman poet stands among traces of late frost. Tiny spring flowers push through the cold ground while warm early sunlight reaches the horizon. Nearby lie an open poetry book, handwritten manuscript pages, and a fountain pen. The visual story is active hope emerging through difficulty: dignified, resilient, calm, and hopeful without sentimentality.',
 WQ024:'A symbolic civic scene at early dawn in a restrained memorial courtyard. A small classical stone bust of an anonymous statesman stands beside broad stone steps and clean architectural lines. Beyond the steps, the horizon opens into warm morning light, suggesting responsibility, public service, courage, and forward action. The mood is dignified, focused, inspiring, and active without theatrical patriotism.',
 WQ025:'A symbolic poetic scene in a serene riverside garden at sunrise. A small classical stone bust of an anonymous poet stands beneath delicate branches beside still water and soft mist. Nearby are an open notebook and loose manuscript pages moved gently by the breeze. Warm morning light spreads across the landscape, creating spiritual openness, tenderness, beauty, and quiet wonder without sentimentality.',
 WQ026:'A symbolic reflective scene in a quiet Renaissance-style study. A small classical stone bust of an anonymous philosopher stands on a wooden table beside an open essay book, handwritten pages, a quill, and a simple hourglass. Soft window light meets restrained candlelight. The room feels orderly, inward-looking, intellectually curious, and humane, expressing self-examination rather than grandiosity.',
 WQ027:'A symbolic mid-20th-century scene of inner freedom in a modest study. A small classical stone bust of an anonymous thinker stands near a simple desk, an open notebook, and a quiet lamp. Outside the window, a road ends at a stone wall; inside, a hand-drawn route on the desk turns toward a new direction. Subtle light gradually softens the shadows. The mood is serious, humane, dignified, and quietly hopeful.',
 WQ028:'A symbolic Stoic scene in a quiet Roman-inspired courtyard at late afternoon. A small classical stone bust of an anonymous philosopher stands beside a water clock, an hourglass, untouched wax tablets, and restrained olive branches. Long sunlight moves across stone while grains continue to fall, making the passage and loss of time visually clear. The mood is disciplined, lucid, calm, and unsentimental.',
 WQ029:'A symbolic scene of courage and liberation in an open courtyard after rain. A small classical stone bust of an anonymous statesman stands beside a long pathway leading from shadow toward clear daylight. A simple gate stands open in the distance, and fresh light breaks through the clouds. The visual story is perseverance, dignity, reconciliation, and movement through fear rather than the absence of fear.',
 WQ030:'A symbolic literary scene in a quiet writer’s room near water. A small classical stone bust of an anonymous woman writer stands beside a writing desk with an open notebook, loose manuscript pages, and a fountain pen. Through the window, moving reflections of water and sky fill the room with shifting natural light. The space suggests intellectual independence, inner freedom, and the private territory of the mind. The mood is elegant, introspective, sensitive, and calm.'
};

const VISUAL={
 uk:'Use deep blue, wheat-gold and dusk neutrals; warm side light; a close human-scale composition with clear foreground-to-horizon depth.',
 ru:'Use burgundy, charcoal and muted ivory; intimate three-quarter framing, low-key light and tactile stone and paper textures.',
 pl:'Use warm ivory, muted crimson and graphite; strong architectural framing, balanced negative space and crisp editorial daylight.',
 en:'Use Oxford navy, parchment and restrained brass; layered editorial depth and controlled cinematic window light.',
 sv:'Use Nordic cool blue, pale stone and soft amber; minimalist framing, airy negative space and calm natural side light.',
 de:'Use charcoal, forest green and warm ochre; precise geometry, structured framing and textured shadows.',
 es:'Use terracotta, olive and warm cream; warm sunlight, diagonal visual movement and textured walls or landscape.',
 fr:'Use slate blue, warm ivory and muted burgundy; elegant asymmetry, fine-art texture and soft directional light.',
 it:'Use olive, terracotta and warm stone; refined classical framing, sun-warmed texture and balanced Mediterranean light without tourist clichés.',
 pt:'Use deep emerald, warm sand and muted azure; fluid composition, luminous natural light and a refined contemporary editorial feel.'
};

function videoPrompt(id,lang,quote){const language=LANGUAGE[lang];return `Create a premium photorealistic vertical 9:16 cinematic video in ${language}.\n\n${SCENE[id]}\n\nDo not depict any recognizable public figure or exact likeness. The bust must be generic, anonymous, and not identifiable as any specific real person. Do not reproduce a known portrait, photograph, memorial statue, or distinctive facial features of the quoted author.\n\nRender EXACT text in one stable, elegant, mobile-readable upper-middle text card:\n${quote}\n\nTypography: clean, large, elegant, mobile-readable; keep the complete quote stable on screen; no word-by-word or letter-by-letter animation.\n\nAudio: a calm native ${language} narrator reads the exact quote and attribution naturally and completely, with correct native pronunciation of the author’s name. Restrained cinematic music remains below the voice.\n\nNo subtitles. No captions. No emoji. No decorative symbols. No logo. No branding. No watermark. No other readable text.\n\nEnd on a clean contemplative hold.`}
function pinterestPrompt(id,lang,quote){return `Create a premium photorealistic vertical 2:3 Pinterest image, target 1000×1500.\n\n${SCENE[id]} ${VISUAL[lang]} Adapt the composition specifically for a still editorial image rather than a video frame. Keep the anonymous stone bust secondary to the visual metaphor and never identifiable as the quoted author.\n\nLeave generous clean upper-middle space for large mobile-readable typography. Render EXACT text:\n${quote}\n\nTypography: elegant, highly readable, balanced spacing, no clipped words, no tiny type.\n\nNo CTA on the image. No other readable text. No flag. No national emblem. No logo. No branding. No watermark.`}
async function latest(env,id,lang){return env.DB.prepare(`SELECT id,adapted_text,version FROM content_versions WHERE content_id=? AND language_code=? ORDER BY version DESC LIMIT 1`).bind(id,lang).first()}
async function upsertOut(env,id,lang,key,text,ts){await env.DB.prepare(`INSERT INTO content_outputs(id,project_id,content_item_id,language_code,output_key,output_text,status,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(content_item_id,language_code,output_key) DO UPDATE SET output_text=excluded.output_text,status=excluded.status,updated_at=excluded.updated_at`).bind(`${id}_${lang}_${key}`,PROJECT,id,lang,key,text,'ready',ts).run()}
export async function ensurePromptAuditStep(env){if(!env?.DB)return{ok:false,error:'DB unavailable'};await env.DB.exec(`CREATE TABLE IF NOT EXISTS system_migrations(id TEXT PRIMARY KEY,applied_at TEXT NOT NULL,notes TEXT); CREATE TABLE IF NOT EXISTS content_outputs(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,content_item_id TEXT NOT NULL,language_code TEXT NOT NULL,output_key TEXT NOT NULL,output_text TEXT,status TEXT NOT NULL DEFAULT 'draft',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(content_item_id,language_code,output_key));`);for(let n=23;n<=30;n++){const id=`WQ${String(n).padStart(3,'0')}`,mid=`prompt-audit-${id}-10langs-20260914-v2`,done=await env.DB.prepare(`SELECT id FROM system_migrations WHERE id=?`).bind(mid).first();if(done)continue;const ts=TS();for(const lang of LANGS){const row=await latest(env,id,lang);if(!row)throw new Error(`${id}/${lang}: missing version`);const fixed=FIX[`${id}:${lang}`]||String(row.adapted_text||'').trim();if(!fixed)throw new Error(`${id}/${lang}: empty quote`);if(fixed!==row.adapted_text)await env.DB.prepare(`UPDATE content_versions SET adapted_text=?,language_check_status='native_qa_pass',verification_date=?,updated_at=? WHERE id=?`).bind(fixed,ts.slice(0,10),ts,row.id).run();await env.DB.prepare(`UPDATE content_versions SET ai_prompt=?,language_check_status='native_qa_pass',verification_date=?,updated_at=? WHERE id=?`).bind(videoPrompt(id,lang,fixed),ts.slice(0,10),ts,row.id).run();await upsertOut(env,id,lang,'pinterest_prompt',pinterestPrompt(id,lang,fixed),ts)}await env.DB.prepare(`INSERT INTO system_migrations(id,applied_at,notes) VALUES(?,?,?)`).bind(mid,ts,`Final native-language audit plus video and Pinterest prompts for ${id}, 10 locales`).run();return{ok:true,applied:id}}return{ok:true,done:true}}
export async function readPromptAudit(env){if(!env?.DB)return{ok:false,error:'DB unavailable'};const rows=(await env.DB.prepare(`SELECT cv.content_id,cv.language_code,cv.adapted_text,cv.ai_prompt,co.output_text pinterest_prompt FROM content_versions cv JOIN (SELECT content_id,language_code,MAX(version) version FROM content_versions WHERE content_id BETWEEN 'WQ023' AND 'WQ030' AND language_code IN ('uk','ru','pl','en','sv','de','es','fr','it','pt') GROUP BY content_id,language_code) x ON x.content_id=cv.content_id AND x.language_code=cv.language_code AND x.version=cv.version LEFT JOIN content_outputs co ON co.project_id=? AND co.content_item_id=cv.content_id AND co.language_code=cv.language_code AND co.output_key='pinterest_prompt' ORDER BY cv.content_id,cv.language_code`).bind(PROJECT).all()).results||[];const checks=rows.map(r=>{const q=String(r.adapted_text||'').trim(),v=String(r.ai_prompt||''),p=String(r.pinterest_prompt||'');return{id:r.content_id,language:r.language_code,quote:q,video_ok:v.includes(q)&&v.includes('Do not depict any recognizable public figure or exact likeness.')&&v.includes('Render EXACT text'),pinterest_ok:p.includes(q)&&p.includes('1000×1500')&&p.includes('Render EXACT text')&&p.includes('No CTA on the image.'),video_chars:v.length,pinterest_chars:p.length}});return{ok:checks.length===80&&checks.every(x=>x.video_ok&&x.pinterest_ok),expected_locales:80,count:checks.length,video_prompts:checks.filter(x=>x.video_ok).length,pinterest_prompts:checks.filter(x=>x.pinterest_ok).length,checks}}
