const SNAPSHOT_DATE='2026-08-30';
const ORDER=['uk','ru','pl','en','sv','de','es','fr'];
const META={uk:['🇺🇦','Українська'],ru:['🌐','Русский'],pl:['🇵🇱','Polski'],en:['🇬🇧','English'],sv:['🇸🇪','Svenska'],de:['🇩🇪','Deutsch'],es:['🇪🇸','Español'],fr:['🇫🇷','Français']};
// Latest available Metricool follower/subscriber snapshot. Pinterest is one shared global account, so it is not attributed to a language total.
const STATS={
 uk:{facebook:8,instagram:945,threads:42,tiktok:53,youtube:36},
 ru:{facebook:5,instagram:44,threads:13,tiktok:86,youtube:96},
 pl:{facebook:14,instagram:17,threads:6,tiktok:37,youtube:29},
 en:{facebook:11,instagram:17,threads:10,tiktok:30,youtube:31},
 sv:{facebook:4,instagram:9,threads:6,tiktok:10,youtube:4},
 de:{facebook:19,instagram:106,threads:3,tiktok:59,youtube:22},
 es:{facebook:21,instagram:196,threads:3,tiktok:11,youtube:82},
 fr:{facebook:0,instagram:0,threads:0,tiktok:0,youtube:0}
};
const LABELS={facebook:'Facebook',instagram:'Instagram',threads:'Threads',tiktok:'TikTok',youtube:'YouTube'};
function total(s){return Object.values(s).reduce((a,b)=>a+Number(b||0),0)}
function fmt(n){return new Intl.NumberFormat('en-US').format(Number(n||0))}
function cards(lang){const s=STATS[lang];return `<section class="social-followers"><div class="container"><div class="social-head"><span class="kicker">Community</span><h2>${lang==='fr'?'Notre communauté':lang==='uk'?'Наша спільнота':lang==='ru'?'Наше сообщество':lang==='pl'?'Nasza społeczność':lang==='sv'?'Vår gemenskap':lang==='de'?'Unsere Community':lang==='es'?'Nuestra comunidad':'Our community'}</h2><p>Metricool · ${SNAPSHOT_DATE}</p></div><div class="social-grid">${Object.entries(LABELS).map(([k,l])=>`<div class="social-stat"><strong>${fmt(s[k])}</strong><span>${l}</span></div>`).join('')}<div class="social-stat total"><strong>${fmt(total(s))}</strong><span>Total</span></div></div><p class="social-note">Pinterest: one shared Wise Quotes World account; followers are not assigned to individual languages.</p></div></section>`}
export async function injectLocaleFollowers(response,url){if(!response)return response;const lang=url.pathname.match(/^\/(uk|ru|pl|en|sv|de|es|fr)\/?$/)?.[1];if(!lang)return response;const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let html=await response.text();const block=cards(lang);html=html.includes('</main>')?html.replace('</main>',`${block}</main>`):html.replace('</body>',`${block}</body>`);html=html.replace('</head>',`<style>.social-followers{padding:18px 0 70px}.social-head p,.social-note{color:var(--muted)}.social-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin-top:20px}.social-stat{padding:18px 12px;border:1px solid var(--line);border-radius:18px;background:var(--panel);text-align:center}.social-stat strong{display:block;font-size:26px;color:var(--gold2)}.social-stat span{font-size:13px;color:var(--muted)}.social-stat.total{border-color:var(--gold2)}.social-note{font-size:12px;margin-top:12px}@media(max-width:760px){.social-grid{grid-template-columns:repeat(2,1fr)}}</style></head>`);const h=new Headers(response.headers);h.delete('content-length');return new Response(html,{status:response.status,statusText:response.statusText,headers:h})}
export function mainFollowerDashboard(){const grand=ORDER.reduce((n,l)=>n+total(STATS[l]),0);const rows=ORDER.map(l=>{const s=STATS[l];return `<a class="langcard" href="/${l}/"><div class="langname"><span>${META[l][0]}</span><strong>${META[l][1]}</strong></div><b>${fmt(total(s))}</b><small>followers / subscribers</small></a>`}).join('');return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wise Quotes World — Global Community</title><meta name="description" content="Wise Quotes World in eight languages"><link rel="stylesheet" href="/styles.css"><style>.dash{padding:70px 0}.dash h1{font-size:clamp(42px,7vw,78px);margin:12px 0}.dash .lead{max-width:720px}.totalbox{margin:30px 0;padding:24px;border:1px solid var(--gold2);border-radius:22px;background:var(--panel)}.totalbox strong{font-size:42px;color:var(--gold2);display:block}.langgrid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.langcard{padding:22px;border:1px solid var(--line);border-radius:20px;background:var(--panel);text-decoration:none;color:inherit}.langname{display:flex;gap:9px;align-items:center}.langcard b{display:block;font-size:30px;color:var(--gold2);margin-top:18px}.langcard small{color:var(--muted)}.note{color:var(--muted);font-size:13px;margin-top:20px}@media(max-width:800px){.langgrid{grid-template-columns:repeat(2,1fr)}}@media(max-width:480px){.langgrid{grid-template-columns:1fr}}</style></head><body><header class="header"><div class="container nav"><a class="brand" href="/"><span class="mark">W</span><span><strong>Wise Quotes World</strong><small>Timeless words · eight languages</small></span></a></div></header><main class="dash"><div class="container"><span class="kicker">Global community</span><h1>Wise Quotes World</h1><p class="lead">Eight languages. One collection of timeless words and reflections.</p><div class="totalbox"><strong>${fmt(grand)}</strong><span>followers / subscribers across language channels</span></div><div class="langgrid">${rows}</div><p class="note">Metricool snapshot: ${SNAPSHOT_DATE}. Totals combine Facebook, Instagram, Threads, TikTok and YouTube for each language. Pinterest uses one shared global account and is therefore excluded from language totals.</p></div></main></body></html>`,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=300'}})}
