const PROJECT_ID='wisequotesworld';
const LANGS=['uk','ru','pl','en','sv','de','es','fr','it','pt','id','tr','ar'];
const COPY={
 uk:{aq:n=>`Цитати ${n}`,ad:(n,c)=>`Добірка перевірених цитат ${n}: ${c} публікацій із поясненнями, контекстом і роздумами.`,ai:n=>`Зібрані в одному місці цитати ${n} з поясненнями, контекстом і посиланнями на повні роздуми.`,cq:n=>`Цитати: ${n}`,cd:(n,c)=>`${n}: ${c} цитат і роздумів Wise Quotes World. Добірка оновлюється разом із новими публікаціями.`,ci:n=>`Добірка цитат і роздумів на тему «${n}». Відкривайте повні матеріали, пов’язаних авторів і близькі теми.`},
 ru:{aq:n=>`Цитаты ${n}`,ad:(n,c)=>`Подборка проверенных цитат ${n}: ${c} публикаций с объяснениями, контекстом и размышлениями.`,ai:n=>`Цитаты ${n}, собранные в одном месте, с объяснениями, контекстом и ссылками на полные материалы.`,cq:n=>`Цитаты: ${n}`,cd:(n,c)=>`${n}: ${c} цитат и размышлений Wise Quotes World. Подборка обновляется вместе с новыми публикациями.`,ci:n=>`Подборка цитат и размышлений на тему «${n}». Открывайте полные материалы, связанных авторов и близкие темы.`},
 pl:{aq:n=>`Cytaty ${n}`,ad:(n,c)=>`Zbiór zweryfikowanych cytatów ${n}: ${c} publikacji z objaśnieniami, kontekstem i refleksjami.`,ai:n=>`Cytaty ${n} w jednym miejscu — z objaśnieniami, kontekstem i odnośnikami do pełnych refleksji.`,cq:n=>`Cytaty: ${n}`,cd:(n,c)=>`${n}: ${c} cytatów i refleksji Wise Quotes World. Zbiór rośnie wraz z nowymi publikacjami.`,ci:n=>`Zbiór cytatów i refleksji na temat „${n}”. Otwieraj pełne teksty, powiązanych autorów i bliskie tematy.`},
 en:{aq:n=>`${n} quotes`,ad:(n,c)=>`A curated collection of verified ${n} quotes: ${c} posts with meaning, context, and reflection.`,ai:n=>`Explore ${n} quotes in one place, with context, interpretation, and links to the full reflections.`,cq:n=>`Quotes about ${n}`,cd:(n,c)=>`${n}: ${c} quotes and reflections from Wise Quotes World, updated as new material is published.`,ci:n=>`Explore quotes and reflections about ${n}, with full articles, related thinkers, and connected themes.`},
 sv:{aq:n=>`Citat av ${n}`,ad:(n,c)=>`En samling verifierade citat av ${n}: ${c} publiceringar med förklaring, sammanhang och reflektion.`,ai:n=>`Utforska citat av ${n} på ett ställe, med sammanhang, tolkning och länkar till fullständiga reflektioner.`,cq:n=>`Citat om ${n}`,cd:(n,c)=>`${n}: ${c} citat och reflektioner från Wise Quotes World, uppdaterade när nytt material publiceras.`,ci:n=>`Utforska citat och reflektioner om ${n}, med fullständiga texter, relaterade tänkare och närliggande teman.`},
 de:{aq:n=>`Zitate von ${n}`,ad:(n,c)=>`Eine Sammlung verifizierter Zitate von ${n}: ${c} Beiträge mit Bedeutung, Kontext und Reflexion.`,ai:n=>`Entdecken Sie Zitate von ${n} an einem Ort – mit Kontext, Einordnung und Links zu den vollständigen Gedanken.`,cq:n=>`Zitate über ${n}`,cd:(n,c)=>`${n}: ${c} Zitate und Gedanken von Wise Quotes World, fortlaufend mit neuen Veröffentlichungen ergänzt.`,ci:n=>`Entdecken Sie Zitate und Gedanken zum Thema ${n}, mit vollständigen Beiträgen, verwandten Denkern und ähnlichen Themen.`},
 es:{aq:n=>`Citas de ${n}`,ad:(n,c)=>`Una colección de citas verificadas de ${n}: ${c} publicaciones con significado, contexto y reflexión.`,ai:n=>`Explora citas de ${n} en un solo lugar, con contexto, interpretación y enlaces a las reflexiones completas.`,cq:n=>`Citas sobre ${n}`,cd:(n,c)=>`${n}: ${c} citas y reflexiones de Wise Quotes World, actualizadas con cada nueva publicación.`,ci:n=>`Explora citas y reflexiones sobre ${n}, con artículos completos, autores relacionados y temas afines.`},
 fr:{aq:n=>`Citations de ${n}`,ad:(n,c)=>`Une sélection de citations vérifiées de ${n} : ${c} publications avec sens, contexte et réflexion.`,ai:n=>`Découvrez les citations de ${n} réunies au même endroit, avec contexte, interprétation et liens vers les réflexions complètes.`,cq:n=>`Citations sur ${n}`,cd:(n,c)=>`${n} : ${c} citations et réflexions de Wise Quotes World, enrichies au fil des nouvelles publications.`,ci:n=>`Découvrez des citations et réflexions sur ${n}, avec les articles complets, des auteurs liés et des thèmes proches.`},
 it:{aq:n=>`Citazioni di ${n}`,ad:(n,c)=>`Una raccolta di citazioni verificate di ${n}: ${c} pubblicazioni con significato, contesto e riflessioni.`,ai:n=>`Scopri le citazioni di ${n} in un unico luogo, con contesto, interpretazione e link alle riflessioni complete.`,cq:n=>`Citazioni su ${n}`,cd:(n,c)=>`${n}: ${c} citazioni e riflessioni di Wise Quotes World, aggiornate con le nuove pubblicazioni.`,ci:n=>`Scopri citazioni e riflessioni su ${n}, con articoli completi, autori collegati e temi affini.`},
 pt:{aq:n=>`Citações de ${n}`,ad:(n,c)=>`Uma seleção de citações verificadas de ${n}: ${c} publicações com significado, contexto e reflexão.`,ai:n=>`Explore citações de ${n} em um só lugar, com contexto, interpretação e links para as reflexões completas.`,cq:n=>`Citações sobre ${n}`,cd:(n,c)=>`${n}: ${c} citações e reflexões do Wise Quotes World, atualizadas com novas publicações.`,ci:n=>`Explore citações e reflexões sobre ${n}, com artigos completos, autores relacionados e temas próximos.`},
 id:{aq:n=>`Kutipan ${n}`,ad:(n,c)=>`Kumpulan kutipan terverifikasi dari ${n}: ${c} publikasi dengan makna, konteks, dan refleksi.`,ai:n=>`Jelajahi kutipan ${n} dalam satu tempat, lengkap dengan konteks, penafsiran, dan tautan ke refleksi penuh.`,cq:n=>`Kutipan tentang ${n}`,cd:(n,c)=>`${n}: ${c} kutipan dan refleksi dari Wise Quotes World, diperbarui seiring terbitnya materi baru.`,ci:n=>`Jelajahi kutipan dan refleksi tentang ${n}, dengan artikel lengkap, tokoh terkait, dan tema yang berdekatan.`},
 tr:{aq:n=>`${n} sözleri`,ad:(n,c)=>`${n}'dan doğrulanmış sözler: anlam, bağlam ve yorum içeren ${c} yayınlık seçki.`,ai:n=>`${n}'ın sözlerini bağlam, yorum ve tam yazılara bağlantılarla tek yerde keşfedin.`,cq:n=>`${n} hakkında sözler`,cd:(n,c)=>`${n}: Wise Quotes World'den ${c} alıntı ve düşünce; yeni yayınlarla düzenli olarak güncellenir.`,ci:n=>`${n} hakkında alıntı ve düşünceleri; tam yazılar, ilgili düşünürler ve yakın temalarla keşfedin.`},
 ar:{aq:n=>`اقتباسات ${n}`,ad:(n,c)=>`مجموعة من الاقتباسات الموثقة لـ${n}: ${c} منشورات مع المعنى والسياق والتأمل.`,ai:n=>`استكشف اقتباسات ${n} في مكان واحد، مع السياق والتفسير وروابط إلى التأملات الكاملة.`,cq:n=>`اقتباسات عن ${n}`,cd:(n,c)=>`${n}: ${c} اقتباسات وتأملات من Wise Quotes World، تُحدَّث مع نشر مواد جديدة.`,ci:n=>`استكشف اقتباسات وتأملات عن ${n}، مع المقالات الكاملة والمفكرين المرتبطين والموضوعات القريبة.`}
};
export function htmlLang(l){return l==='pt'?'pt-BR':l}
export function authorSlug(v){return String(v||'').trim().toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-+|-+$/g,'')||'other'}
export function taxonomyCopy(locale,type,name,count){const c=COPY[locale]||COPY.en,n=Number(count||0);return type==='author'?{title:c.aq(name),description:c.ad(name,n),intro:c.ai(name)}:{title:c.cq(name),description:c.cd(name,n),intro:c.ci(name)}}
export async function taxonomyAlternates(env,type,key){if(!env?.DB)return[];if(type==='category'){return (await env.DB.prepare(`SELECT DISTINCT qp.language_code FROM quote_pages qp JOIN content_items ci ON ci.id=qp.content_item_id WHERE qp.project_id=? AND qp.status='published' AND ci.category_slug=? AND qp.language_code IN ('uk','ru','pl','en','sv','de','es','fr','it','pt','id','tr','ar') ORDER BY qp.language_code`).bind(PROJECT_ID,key).all()).results||[]}return (await env.DB.prepare(`SELECT qp.language_code,MIN(ci.author_name) author_name FROM quote_pages qp JOIN content_items ci ON ci.id=qp.content_item_id WHERE qp.project_id=? AND qp.status='published' AND ci.attribution_status='verified' AND ci.author_name=? AND qp.language_code IN ('uk','ru','pl','en','sv','de','es','fr','it','pt','id','tr','ar') GROUP BY qp.language_code ORDER BY qp.language_code`).bind(PROJECT_ID,key).all()).results||[]}
export function taxonomyAlternateLinks(type,key,rows=[]){if(!rows.length)return'';let out='';for(const r of rows){const p=type==='category'?`/${r.language_code}/category/${encodeURIComponent(key)}/`:`/${r.language_code}/author/${encodeURIComponent(authorSlug(r.author_name||key))}/`;out+=`<link rel="alternate" hreflang="${htmlLang(r.language_code)}" href="https://wisequotesworld.com${p}">`}const en=rows.find(r=>r.language_code==='en')||rows[0];if(en){const p=type==='category'?`/${en.language_code}/category/${encodeURIComponent(key)}/`:`/${en.language_code}/author/${encodeURIComponent(authorSlug(en.author_name||key))}/`;out+=`<link rel="alternate" hreflang="x-default" href="https://wisequotesworld.com${p}">`}return out}
export function taxonomySchema(locale,type,title,canonical,count){const base='https://wisequotesworld.com',page=`${base}${canonical}`,items=[{'@type':'ListItem',position:1,name:'Wise Quotes World',item:`${base}/${locale}/`},{'@type':'ListItem',position:2,name:title,item:page}];const collection={'@context':'https://schema.org','@type':'CollectionPage',name:title,url:page,inLanguage:htmlLang(locale),isPartOf:{'@type':'WebSite',name:'Wise Quotes World',url:`${base}/`},numberOfItems:Number(count||0)};if(type==='author')collection.about={'@type':'Person',name:title.replace(/^(Цитати |Цитаты |Cytaty |Citat av |Zitate von |Citas de |Citations de |Citazioni di |Citações de |Kutipan |اقتباسات )/,'').replace(/ quotes$/,'')};return [collection,{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:items}]}
export const TAXONOMY_LANGS=LANGS;
