import {normalizeLocale,localeConfig,WEBSITE_LOCALES} from './locale_registry.js';

export const UI_COPY=Object.freeze({
uk:{title:'Мудрість, яку варто пам’ятати',lead:'Позачасові думки, нові роздуми й цитати, до яких хочеться повертатися.',home:'Головна',all:'Усі цитати',latest:'Останні публікації',curated:'Вибрані цитати',categories:'Теми',authors:'Автори',read:'Читати роздуми',empty:'Поки що немає опублікованих цитат.',day:'Щодня.',latestKicker:'Нове',curatedKicker:'Вибране',exploreKicker:'Досліджуйте',thinkersKicker:'Мислителі',archiveKicker:'Архів',brandTagline:'Позачасові слова · 13 мов',menuLabel:'Меню',languageLabel:'Мова',relatedTopics:'Інші теми',relatedAuthors:'Інші автори',source:'Джерело',original:'Оригінал',related:'Схожі думки',verified:'Джерело перевірено',copyQuote:'Копіювати цитату',share:'Поділитися'},
ru:{title:'Мудрость, которую стоит помнить',lead:'Вечные мысли, новые размышления и цитаты, к которым хочется возвращаться.',home:'Главная',all:'Все цитаты',latest:'Последние публикации',curated:'Избранные цитаты',categories:'Темы',authors:'Авторы',read:'Читать размышления',empty:'Пока нет опубликованных цитат.',day:'Каждый день.',latestKicker:'Новое',curatedKicker:'Избранное',exploreKicker:'Исследуйте',thinkersKicker:'Мыслители',archiveKicker:'Архив',brandTagline:'Вечные слова · 13 языков',menuLabel:'Меню',languageLabel:'Язык',relatedTopics:'Другие темы',relatedAuthors:'Другие авторы',source:'Источник',original:'Оригинал',related:'Похожие мысли',verified:'Источник проверен',copyQuote:'Копировать цитату',share:'Поделиться'},
pl:{title:'Mądrość, do której warto wracać',lead:'Ponadczasowe myśli, nowe refleksje i cytaty, do których chce się wracać.',home:'Strona główna',all:'Wszystkie cytaty',latest:'Najnowsze publikacje',curated:'Wybrane cytaty',categories:'Tematy',authors:'Autorzy',read:'Czytaj refleksję',empty:'Brak opublikowanych cytatów.',day:'Każdego dnia.',latestKicker:'Najnowsze',curatedKicker:'Wybrane',exploreKicker:'Odkrywaj',thinkersKicker:'Myśliciele',archiveKicker:'Archiwum',brandTagline:'Ponadczasowe słowa · 13 języków',menuLabel:'Menu',languageLabel:'Język',relatedTopics:'Inne tematy',relatedAuthors:'Inni autorzy',source:'Źródło',original:'Oryginał',related:'Powiązane myśli',verified:'Źródło zweryfikowane',copyQuote:'Kopiuj cytat',share:'Udostępnij'},
en:{title:'Wisdom worth remembering',lead:'Timeless words, new reflections, and quotes worth returning to.',home:'Home',all:'All quotes',latest:'Latest posts',curated:'Curated quotes',categories:'Topics',authors:'Authors',read:'Read the reflection',empty:'No published quotes yet.',day:'Every day.',latestKicker:'Latest',curatedKicker:'Curated',exploreKicker:'Explore',thinkersKicker:'Thinkers',archiveKicker:'Archive',brandTagline:'Timeless words · 13 languages',menuLabel:'Menu',languageLabel:'Language',relatedTopics:'Related topics',relatedAuthors:'Other authors',source:'Source',original:'Original',related:'Related reflections',verified:'Source verified',copyQuote:'Copy quote',share:'Share'},
sv:{title:'Visdom värd att minnas',lead:'Tidlösa ord, nya reflektioner och citat att återvända till.',home:'Hem',all:'Alla citat',latest:'Senaste inläggen',curated:'Utvalda citat',categories:'Ämnen',authors:'Författare',read:'Läs reflektionen',empty:'Inga publicerade citat ännu.',day:'Varje dag.',latestKicker:'Senast',curatedKicker:'Utvalt',exploreKicker:'Utforska',thinkersKicker:'Tänkare',archiveKicker:'Arkiv',brandTagline:'Tidlösa ord · 13 språk',menuLabel:'Meny',languageLabel:'Språk',relatedTopics:'Fler ämnen',relatedAuthors:'Fler författare',source:'Källa',original:'Original',related:'Relaterade reflektioner',verified:'Källan är verifierad',copyQuote:'Kopiera citat',share:'Dela'},
de:{title:'Weisheit, an die man sich erinnern sollte',lead:'Zeitlose Gedanken, neue Reflexionen und Zitate, zu denen man gern zurückkehrt.',home:'Startseite',all:'Alle Zitate',latest:'Neueste Beiträge',curated:'Ausgewählte Zitate',categories:'Themen',authors:'Autoren',read:'Gedanken lesen',empty:'Noch keine veröffentlichten Zitate.',day:'Jeden Tag.',latestKicker:'Neu',curatedKicker:'Ausgewählt',exploreKicker:'Entdecken',thinkersKicker:'Denker',archiveKicker:'Archiv',brandTagline:'Zeitlose Worte · 13 Sprachen',menuLabel:'Menü',languageLabel:'Sprache',relatedTopics:'Weitere Themen',relatedAuthors:'Weitere Autoren',source:'Quelle',original:'Original',related:'Ähnliche Gedanken',verified:'Quelle verifiziert',copyQuote:'Zitat kopieren',share:'Teilen'},
es:{title:'Sabiduría que vale la pena recordar',lead:'Palabras atemporales, nuevas reflexiones y citas a las que merece la pena volver.',home:'Inicio',all:'Todas las citas',latest:'Últimas publicaciones',curated:'Citas seleccionadas',categories:'Temas',authors:'Autores',read:'Leer la reflexión',empty:'Aún no hay citas publicadas.',day:'Cada día.',latestKicker:'Lo último',curatedKicker:'Selección',exploreKicker:'Explorar',thinkersKicker:'Pensadores',archiveKicker:'Archivo',brandTagline:'Palabras atemporales · 13 idiomas',menuLabel:'Menú',languageLabel:'Idioma',relatedTopics:'Otros temas',relatedAuthors:'Otros autores',source:'Fuente',original:'Original',related:'Reflexiones relacionadas',verified:'Fuente verificada',copyQuote:'Copiar cita',share:'Compartir'},
fr:{title:'Une sagesse à garder en mémoire',lead:'Des mots intemporels, de nouvelles réflexions et des citations auxquelles revenir.',home:'Accueil',all:'Toutes les citations',latest:'Dernières publications',curated:'Citations choisies',categories:'Thèmes',authors:'Auteurs',read:'Lire la réflexion',empty:'Aucune citation publiée pour le moment.',day:'Chaque jour.',latestKicker:'À la une',curatedKicker:'Sélection',exploreKicker:'Explorer',thinkersKicker:'Penseurs',archiveKicker:'Archives',brandTagline:'Des mots intemporels · 13 langues',menuLabel:'Menu',languageLabel:'Langue',relatedTopics:'Autres thèmes',relatedAuthors:'Autres auteurs',source:'Source',original:'Original',related:'Réflexions liées',verified:'Source vérifiée',copyQuote:'Copier la citation',share:'Partager'},
it:{title:'Saggezza da ricordare',lead:'Parole senza tempo, nuove riflessioni e citazioni a cui vale la pena tornare.',home:'Home',all:'Tutte le citazioni',latest:'Ultime pubblicazioni',curated:'Citazioni selezionate',categories:'Temi',authors:'Autori',read:'Leggi la riflessione',empty:'Non ci sono ancora citazioni pubblicate.',day:'Ogni giorno.',latestKicker:'Novità',curatedKicker:'Selezione',exploreKicker:'Esplora',thinkersKicker:'Pensatori',archiveKicker:'Archivio',brandTagline:'Parole senza tempo · 13 lingue',menuLabel:'Menu',languageLabel:'Lingua',relatedTopics:'Altri temi',relatedAuthors:'Altri autori',source:'Fonte',original:'Originale',related:'Riflessioni correlate',verified:'Fonte verificata',copyQuote:'Copia citazione',share:'Condividi'},
pt:{title:'Sabedoria que vale a pena lembrar',lead:'Palavras atemporais, novas reflexões e citações às quais vale a pena voltar.',home:'Início',all:'Todas as citações',latest:'Publicações recentes',curated:'Citações selecionadas',categories:'Temas',authors:'Autores',read:'Leia a reflexão',empty:'Ainda não há citações publicadas.',day:'Todos os dias.',latestKicker:'Recentes',curatedKicker:'Seleção',exploreKicker:'Explorar',thinkersKicker:'Pensadores',archiveKicker:'Arquivo',brandTagline:'Palavras atemporais · 13 idiomas',menuLabel:'Menu',languageLabel:'Idioma',relatedTopics:'Outros temas',relatedAuthors:'Outros autores',source:'Fonte',original:'Original',related:'Reflexões relacionadas',verified:'Fonte verificada',copyQuote:'Copiar citação',share:'Compartilhar'},
id:{title:'Kebijaksanaan yang layak diingat',lead:'Kata-kata lintas zaman, refleksi baru, dan kutipan yang layak dibaca kembali.',home:'Beranda',all:'Semua kutipan',latest:'Publikasi terbaru',curated:'Kutipan pilihan',categories:'Topik',authors:'Penulis',read:'Baca refleksi',empty:'Belum ada kutipan yang diterbitkan.',day:'Setiap hari.',latestKicker:'Terbaru',curatedKicker:'Pilihan',exploreKicker:'Jelajahi',thinkersKicker:'Pemikir',archiveKicker:'Arsip',brandTagline:'Kata-kata lintas zaman · 13 bahasa',menuLabel:'Menu',languageLabel:'Bahasa',relatedTopics:'Topik lainnya',relatedAuthors:'Penulis lainnya',source:'Sumber',original:'Asli',related:'Refleksi terkait',verified:'Sumber terverifikasi',copyQuote:'Salin kutipan',share:'Bagikan'},
tr:{title:'Hatırlamaya değer bilgelik',lead:'Zamansız sözler, yeni düşünceler ve yeniden dönmeye değer alıntılar.',home:'Ana sayfa',all:'Tüm alıntılar',latest:'Son yayınlar',curated:'Seçili alıntılar',categories:'Konular',authors:'Yazarlar',read:'Düşünceyi oku',empty:'Henüz yayımlanmış alıntı yok.',day:'Her gün.',latestKicker:'Yeni',curatedKicker:'Seçki',exploreKicker:'Keşfet',thinkersKicker:'Düşünürler',archiveKicker:'Arşiv',brandTagline:'Zamansız sözler · 13 dil',menuLabel:'Menü',languageLabel:'Dil',relatedTopics:'Diğer konular',relatedAuthors:'Diğer yazarlar',source:'Kaynak',original:'Özgün metin',related:'İlgili düşünceler',verified:'Kaynak doğrulandı',copyQuote:'Alıntıyı kopyala',share:'Paylaş'},
ar:{title:'حكمة تستحق أن نتذكرها',lead:'كلمات خالدة وتأملات جديدة واقتباسات تستحق العودة إليها.',home:'الرئيسية',all:'جميع الاقتباسات',latest:'أحدث المنشورات',curated:'اقتباسات مختارة',categories:'الموضوعات',authors:'المؤلفون',read:'اقرأ التأمل',empty:'لا توجد اقتباسات منشورة بعد.',day:'كل يوم.',latestKicker:'الأحدث',curatedKicker:'مختارات',exploreKicker:'استكشف',thinkersKicker:'المفكرون',archiveKicker:'الأرشيف',brandTagline:'كلمات خالدة · 13 لغة',menuLabel:'القائمة',languageLabel:'اللغة',relatedTopics:'موضوعات أخرى',relatedAuthors:'مؤلفون آخرون',source:'المصدر',original:'النص الأصلي',related:'تأملات ذات صلة',verified:'تم التحقق من المصدر',copyQuote:'نسخ الاقتباس',share:'مشاركة'}
});

const CATEGORY_COPY=Object.freeze({
'philosophy':{uk:'Філософія',ru:'Философия',pl:'Filozofia',en:'Philosophy',sv:'Filosofi',de:'Philosophie',es:'Filosofía',fr:'Philosophie',it:'Filosofia',pt:'Filosofia',id:'Filsafat',tr:'Felsefe',ar:'الفلسفة'},
'stoicism':{uk:'Стоїцизм',ru:'Стоицизм',pl:'Stoicyzm',en:'Stoicism',sv:'Stoicism',de:'Stoizismus',es:'Estoicismo',fr:'Stoïcisme',it:'Stoicismo',pt:'Estoicismo',id:'Stoisisme',tr:'Stoacılık',ar:'الرواقية'},
'science':{uk:'Наука',ru:'Наука',pl:'Nauka',en:'Science',sv:'Vetenskap',de:'Wissenschaft',es:'Ciencia',fr:'Science',it:'Scienza',pt:'Ciência',id:'Sains',tr:'Bilim',ar:'العلم'},
'literature':{uk:'Література',ru:'Литература',pl:'Literatura',en:'Literature',sv:'Litteratur',de:'Literatur',es:'Literatura',fr:'Littérature',it:'Letteratura',pt:'Literatura',id:'Sastra',tr:'Edebiyat',ar:'الأدب'},
'history':{uk:'Історія',ru:'История',pl:'Historia',en:'History',sv:'Historia',de:'Geschichte',es:'Historia',fr:'Histoire',it:'Storia',pt:'História',id:'Sejarah',tr:'Tarih',ar:'التاريخ'},
'discipline':{uk:'Дисципліна',ru:'Дисциплина',pl:'Dyscyplina',en:'Discipline',sv:'Disciplin',de:'Disziplin',es:'Disciplina',fr:'Discipline',it:'Disciplina',pt:'Disciplina',id:'Disiplin',tr:'Disiplin',ar:'الانضباط'},
'parents-family':{uk:'Батьки та сім’я',ru:'Родители и семья',pl:'Rodzice i rodzina',en:'Parents & Family',sv:'Föräldrar & familj',de:'Eltern & Familie',es:'Padres y familia',fr:'Parents et famille',it:'Genitori e famiglia',pt:'Pais e família',id:'Orang tua & keluarga',tr:'Anne baba ve aile',ar:'الوالدان والأسرة'},
'philosophy-strength':{uk:'Філософія та сила',ru:'Философия и сила',pl:'Filozofia i siła',en:'Philosophy & Strength',sv:'Filosofi & styrka',de:'Philosophie & Stärke',es:'Filosofía y fortaleza',fr:'Philosophie et force',it:'Filosofia e forza',pt:'Filosofia e força',id:'Filsafat & kekuatan',tr:'Felsefe ve güç',ar:'الفلسفة والقوة'},
'identity':{uk:'Ідентичність',ru:'Идентичность',pl:'Tożsamość',en:'Identity',sv:'Identitet',de:'Identität',es:'Identidad',fr:'Identité',it:'Identità',pt:'Identidade',id:'Jati diri',tr:'Kimlik',ar:'الهوية'},
'self-authenticity':{uk:'Автентичність',ru:'Аутентичность',pl:'Autentyczność',en:'Authenticity',sv:'Autenticitet',de:'Authentizität',es:'Autenticidad',fr:'Authenticité',it:'Autenticità',pt:'Autenticidade',id:'Keaslian diri',tr:'Özgünlük',ar:'الأصالة'},
'learning':{uk:'Навчання',ru:'Обучение',pl:'Nauka i rozwój',en:'Learning',sv:'Lärande',de:'Lernen',es:'Aprendizaje',fr:'Apprentissage',it:'Apprendimento',pt:'Aprendizado',id:'Pembelajaran',tr:'Öğrenme',ar:'التعلّم'},
'hope':{uk:'Надія',ru:'Надежда',pl:'Nadzieja',en:'Hope',sv:'Hopp',de:'Hoffnung',es:'Esperanza',fr:'Espoir',it:'Speranza',pt:'Esperança',id:'Harapan',tr:'Umut',ar:'الأمل'},
'resilience':{uk:'Стійкість',ru:'Стойкость',pl:'Odporność',en:'Resilience',sv:'Motståndskraft',de:'Resilienz',es:'Resiliencia',fr:'Résilience',it:'Resilienza',pt:'Resiliência',id:'Ketangguhan',tr:'Dayanıklılık',ar:'المرونة النفسية'},
'fear':{uk:'Страх',ru:'Страх',pl:'Strach',en:'Fear',sv:'Rädsla',de:'Angst',es:'Miedo',fr:'Peur',it:'Paura',pt:'Medo',id:'Ketakutan',tr:'Korku',ar:'الخوف'},
'love':{uk:'Любов',ru:'Любовь',pl:'Miłość',en:'Love',sv:'Kärlek',de:'Liebe',es:'Amor',fr:'Amour',it:'Amore',pt:'Amor',id:'Cinta',tr:'Sevgi',ar:'الحب'},
'meaning':{uk:'Сенс',ru:'Смысл',pl:'Sens',en:'Meaning',sv:'Mening',de:'Sinn',es:'Sentido',fr:'Sens',it:'Significato',pt:'Sentido',id:'Makna',tr:'Anlam',ar:'المعنى'},
'responsibility':{uk:'Відповідальність',ru:'Ответственность',pl:'Odpowiedzialność',en:'Responsibility',sv:'Ansvar',de:'Verantwortung',es:'Responsabilidad',fr:'Responsabilité',it:'Responsabilità',pt:'Responsabilidade',id:'Tanggung jawab',tr:'Sorumluluk',ar:'المسؤولية'}
});

export function uiCopy(locale){const code=normalizeLocale(locale)||'en';return UI_COPY[code]||UI_COPY.en}
export function categoryLabel(locale,slug,fallback=''){const code=normalizeLocale(locale)||'en';return CATEGORY_COPY[String(slug||'').trim()]?.[code]||fallback||String(slug||'').replace(/[-_]+/g,' ')}
export function languageMenuEntries(){return WEBSITE_LOCALES.map(code=>({code,url:`/${localeConfig(code).url}/`,name:localeConfig(code).name,canonical:localeConfig(code).canonical,dir:localeConfig(code).dir}))}
