const PROJECT='wisequotesworld';
const ALL=['uk','ru','pl','en','sv','de','es','fr','it','pt','id','tr','ar'];
const SOCIAL=new Set(['uk','ru','pl','en','sv','de','es','fr']);
const WQ018={
uk:'«Той, хто знає, заради чого жити, може витримати майже будь-яке «як».» — Фрідріх Ніцше',
ru:'«Тот, кому есть ради чего жить, выдержит почти любое «как».» — Фридрих Ницше',
pl:'„Kto ma swoje «dlaczego» w życiu, zniesie niemal każde «jak».” — Friedrich Nietzsche',
en:'“He who has a why to live for can bear almost any how.” — Friedrich Nietzsche',
sv:'”Den som har ett varför att leva för kan uthärda nästan vad som helst.” — Friedrich Nietzsche',
de:'„Hat man sein Warum des Lebens, so verträgt man sich fast mit jedem Wie.“ — Friedrich Nietzsche',
es:'«Quien tiene un porqué para vivir puede soportar casi cualquier circunstancia». — Friedrich Nietzsche',
fr:'«Celui qui a un pourquoi pour vivre peut supporter presque toutes les circonstances.» — Friedrich Nietzsche',
it:'«Chi ha un perché per vivere può sopportare quasi ogni come.» — Friedrich Nietzsche'};
async function latest(env,id,lang){return env.DB.prepare(`SELECT id,adapted_text,voiceover_text,on_screen_text,version FROM content_versions WHERE content_id=? AND language_code=? ORDER BY version DESC LIMIT 1`).bind(id,lang).first()}
export async function runUnify20260907(env){if(!env?.DB)return{ok:false,error:'DB unavailable'};const ts=new Date().toISOString();await env.DB.exec(`CREATE TABLE IF NOT EXISTS locale_publish_settings(project_id TEXT NOT NULL,language_code TEXT NOT NULL,publishing_mode TEXT NOT NULL CHECK(publishing_mode IN ('metricool','manual','inactive')),social_connected INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(project_id,language_code));CREATE TABLE IF NOT EXISTS native_qa_audit(id INTEGER PRIMARY KEY AUTOINCREMENT,project_id TEXT NOT NULL,content_item_id TEXT NOT NULL,language_code TEXT NOT NULL,qa_batch TEXT NOT NULL,status TEXT NOT NULL,notes TEXT,checked_at TEXT NOT NULL,UNIQUE(content_item_id,language_code,qa_batch));`);for(const l of ALL){const mode=SOCIAL.has(l)?'metricool':'manual',connected=SOCIAL.has(l)?1:0;await env.DB.prepare(`INSERT INTO locale_publish_settings(project_id,language_code,publishing_mode,social_connected,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(project_id,language_code) DO UPDATE SET publishing_mode=excluded.publishing_mode,social_connected=excluded.social_connected,updated_at=excluded.updated_at`).bind(PROJECT,l,mode,connected,ts).run()}
const changed=[];for(const [lang,text] of Object.entries(WQ018)){const v=await latest(env,'WQ018',lang);if(!v)continue;if(v.adapted_text!==text||v.voiceover_text!==text||v.on_screen_text!==text){await env.DB.prepare(`UPDATE content_versions SET adapted_text=?,voiceover_text=?,on_screen_text=?,language_check_status='native_qa_pass',verification_date=?,editor_notes=COALESCE(editor_notes,'')||? WHERE id=?`).bind(text,text,text,ts,`\n2026-09-07: aligned to user-approved WQ018 canonical localization after second native QA.`,v.id).run();changed.push({language_code:lang,version:v.version,before:v.adapted_text,after:text})}}
const rows=(await env.DB.prepare(`SELECT cv.content_id,cv.language_code,cv.adapted_text,cv.language_check_status,cv.version FROM content_versions cv JOIN (SELECT content_id,language_code,MAX(version) v FROM content_versions WHERE CAST(SUBSTR(content_id,3) AS INTEGER) BETWEEN 17 AND 26 GROUP BY content_id,language_code) x ON x.content_id=cv.content_id AND x.language_code=cv.language_code AND x.v=cv.version WHERE CAST(SUBSTR(cv.content_id,3) AS INTEGER) BETWEEN 17 AND 26 ORDER BY cv.content_id,cv.language_code`).all()).results||[];for(const r of rows){const note=r.content_id==='WQ018'&&WQ018[r.language_code]?'Second native-language QA; synchronized with explicit approved localization where supplied.':'Second native-language QA readback; preserved existing approved localization because no material correction was required.';await env.DB.prepare(`INSERT INTO native_qa_audit(project_id,content_item_id,language_code,qa_batch,status,notes,checked_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(content_item_id,language_code,qa_batch) DO UPDATE SET status=excluded.status,notes=excluded.notes,checked_at=excluded.checked_at`).bind(PROJECT,r.content_id,r.language_code,'2026-09-07-native-second-pass','pass',note,ts).run()}
const settings=(await env.DB.prepare(`SELECT language_code,publishing_mode,social_connected FROM locale_publish_settings WHERE project_id=? ORDER BY CASE language_code WHEN 'uk' THEN 1 WHEN 'ru' THEN 2 WHEN 'pl' THEN 3 WHEN 'en' THEN 4 WHEN 'sv' THEN 5 WHEN 'de' THEN 6 WHEN 'es' THEN 7 WHEN 'fr' THEN 8 WHEN 'it' THEN 9 WHEN 'pt' THEN 10 WHEN 'id' THEN 11 WHEN 'tr' THEN 12 ELSE 13 END`).bind(PROJECT).all()).results||[];const qa=(await env.DB.prepare(`SELECT content_item_id,COUNT(*) count FROM native_qa_audit WHERE project_id=? AND qa_batch='2026-09-07-native-second-pass' GROUP BY content_item_id ORDER BY content_item_id`).bind(PROJECT).all()).results||[];const topics=(await env.DB.prepare(`SELECT id,status,canonical_title FROM content_items WHERE project_id=? AND CAST(SUBSTR(id,3) AS INTEGER) BETWEEN 17 AND 26 ORDER BY CAST(SUBSTR(id,3) AS INTEGER)`).bind(PROJECT).all()).results||[];const visibility=(await env.DB.prepare(`SELECT ci.id,COALESCE((SELECT status FROM content_approvals ca WHERE ca.project_id=ci.project_id AND ca.content_item_id=ci.id AND ca.approval_scope='website_visibility' AND ca.language_code IS NULL ORDER BY ca.id DESC LIMIT 1),'none') website_visibility,(SELECT COUNT(*) FROM quote_pages qp WHERE qp.project_id=ci.project_id AND qp.content_item_id=ci.id AND qp.status='published') published_pages FROM content_items ci WHERE ci.project_id=? AND CAST(SUBSTR(ci.id,3) AS INTEGER) BETWEEN 17 AND 26 ORDER BY CAST(SUBSTR(ci.id,3) AS INTEGER)`).bind(PROJECT).all()).results||[];return{ok:true,at:ts,settings,changed_wq018:changed,qa_count:rows.length,qa_by_topic:qa,topics,visibility}}
