const PROJECT='wisequotesworld';
const LANGS=['uk','ru','pl','en','sv','de','es','fr'];
export async function exportWQ019Schedule(env){
 const id='WQ019';
 const item=await env.DB.prepare(`SELECT id,status,quote_type,author_name,attribution_status FROM content_items WHERE project_id=? AND id=?`).bind(PROJECT,id).first();
 const approval=await env.DB.prepare(`SELECT status,updated_at FROM content_approvals WHERE content_item_id=? AND approval_scope='content' AND language_code IS NULL ORDER BY id DESC LIMIT 1`).bind(id).first();
 const visibility=await env.DB.prepare(`SELECT status,updated_at FROM content_approvals WHERE content_item_id=? AND approval_scope='website_visibility' AND language_code IS NULL ORDER BY id DESC LIMIT 1`).bind(id).first();
 const versions=(await env.DB.prepare(`SELECT cv.language_code,cv.adapted_text,cv.ai_prompt,cv.language_check_status FROM content_versions cv JOIN (SELECT language_code,MAX(version) v FROM content_versions WHERE content_id=? GROUP BY language_code) x ON x.language_code=cv.language_code AND x.v=cv.version WHERE cv.content_id=? AND cv.language_code IN ('uk','ru','pl','en','sv','de','es','fr') ORDER BY cv.language_code`).bind(id,id).all()).results||[];
 const outputs=(await env.DB.prepare(`SELECT language_code,output_key,output_text,status FROM content_outputs WHERE project_id=? AND content_item_id=? AND language_code IN ('uk','ru','pl','en','sv','de','es','fr') ORDER BY language_code,output_key`).bind(PROJECT,id).all()).results||[];
 const media=(await env.DB.prepare(`SELECT m.id,m.language_code,m.asset_type,m.mime_type,m.original_filename,m.r2_key,COALESCE(r.qa_status,'pending') qa_status FROM media_inbox m LEFT JOIN media_reviews r ON r.media_inbox_id=m.id WHERE m.project_id=? AND m.content_item_id=? AND m.language_code IN ('uk','ru','pl','en','sv','de','es','fr') ORDER BY m.language_code,m.created_at DESC`).bind(PROJECT,id).all()).results||[];
 const latest={};
 for(const m of media){const kind=(String(m.asset_type||'').toLowerCase().includes('video')||String(m.mime_type||'').toLowerCase().startsWith('video/'))?'video':((String(m.asset_type||'').toLowerCase().includes('pinterest')||String(m.asset_type||'').toLowerCase().includes('image')||String(m.mime_type||'').toLowerCase().startsWith('image/'))?'pinterest':'other'); if(kind==='other')continue; const k=m.language_code+':'+kind;if(!latest[k])latest[k]={...m,kind};}
 const byLang={};for(const l of LANGS)byLang[l]={language:l,quote:versions.find(v=>v.language_code===l)?.adapted_text||'',ai_prompt:versions.find(v=>v.language_code===l)?.ai_prompt||'',language_check_status:versions.find(v=>v.language_code===l)?.language_check_status||'',outputs:Object.fromEntries(outputs.filter(o=>o.language_code===l).map(o=>[o.output_key,o.output_text])),video:latest[l+':video']||null,pinterest:latest[l+':pinterest']||null,video_url:`https://wisequotesworld.com/media/approved/${id}/${l}/video.mp4`,pinterest_url:`https://wisequotesworld.com/media/approved/${id}/${l}/pinterest.png`};
 const complete=LANGS.every(l=>byLang[l].video?.qa_status==='approved'&&byLang[l].pinterest?.qa_status==='approved'&&byLang[l].outputs.article_url&&byLang[l].outputs.facebook&&byLang[l].outputs.instagram&&byLang[l].outputs.threads&&byLang[l].outputs.tiktok&&byLang[l].outputs.youtube_title&&byLang[l].outputs.youtube_description&&byLang[l].outputs.pinterest_title&&byLang[l].outputs.pinterest_description);
 return {ok:true,item,approval,website_visibility:visibility||{status:'hidden'},complete,languages:byLang};
}
