const PROJECT_ID='wisequotesworld';
const CONTENT_ID='WQ011';
const LANGS=['uk','ru','pl','en','sv','de','es','fr'];
const HEAD={uk:'UK',ru:'RU',pl:'PL',en:'EN',sv:'SV',de:'DE',es:'ES',fr:'FR'};
const RAW='https://raw.githubusercontent.com/oshtogryn/wisequotesworld-web/main/ops/prepared/WQ011-platform-copy.md';
const KEYS={'Facebook':'facebook','Instagram':'instagram','Threads':'threads','TikTok':'tiktok','YouTube title':'youtube_title','YouTube description':'youtube_description','Pinterest title':'pinterest_title','Pinterest description':'pinterest_description','Website reflection':'website_reflection'};
const SLUGS={uk:'shcho-mene-ne-vbyvaie-robyt-sylnishym-nitsshe',ru:'chto-menya-ne-ubivaet-delaet-silnee-nicshe',pl:'co-mnie-nie-zabija-czyni-silniejszym-nietzsche',en:'what-does-not-kill-me-makes-me-stronger-nietzsche',sv:'det-som-inte-dodar-mig-gor-mig-starkare-nietzsche',de:'was-mich-nicht-umbringt-macht-mich-staerker-nietzsche',es:'lo-que-no-me-mata-me-hace-mas-fuerte-nietzsche',fr:'ce-qui-ne-me-tue-pas-me-rend-plus-fort-nietzsche'};
function parse(md){const out={};for(const l of LANGS){const m=md.match(new RegExp(`(?:^|\\n)## ${HEAD[l]}\\s*\\n([\\s\\S]*?)(?=\\n## |$)`));if(!m)throw new Error(`WQ011 copy missing ${l}`);out[l]={};for(const line of m[1].split('\n'))for(const [label,key] of Object.entries(KEYS))if(line.startsWith(label+':'))out[l][key]=line.slice(label.length+1).trim();for(const key of Object.values(KEYS))if(!out[l][key])throw new Error(`WQ011 ${l} missing ${key}`);out[l].article_url=`https://wisequotesworld.com/${l}/quotes/${SLUGS[l]}/`}return out}
async function load(){const r=await fetch(RAW,{headers:{'user-agent':'wisequotesworld-worker'}});if(!r.ok)throw new Error(`WQ011 copy fetch ${r.status}`);return parse(await r.text())}
export async function ensureWQ011CopySynced(env){if(!env?.DB)return{ok:false,error:'DB binding unavailable'};const exists=await env.DB.prepare(`SELECT 1 FROM content_items WHERE project_id=? AND id=?`).bind(PROJECT_ID,CONTENT_ID).first();if(!exists)return{ok:false,error:'WQ011 missing'};const copy=await load(),ts=new Date().toISOString();let n=0;for(const l of LANGS)for(const [key,text] of Object.entries(copy[l])){const id=`${CONTENT_ID}_${l}_${key}`;await env.DB.prepare(`INSERT INTO content_outputs(id,project_id,content_item_id,language_code,output_key,output_text,status,updated_at) VALUES(?,?,?,?,?,?, 'ready', ?) ON CONFLICT(content_item_id,language_code,output_key) DO UPDATE SET output_text=excluded.output_text,status='ready',updated_at=excluded.updated_at`).bind(id,PROJECT_ID,CONTENT_ID,l,key,text,ts).run();n++}return{ok:true,languages:8,outputs:n}}
export async function readbackWQ011Copy(env){if(!env?.DB)return{ok:false,error:'DB binding unavailable'};const canonical=await load();const rows=(await env.DB.prepare(`SELECT language_code,output_key,output_text FROM content_outputs WHERE project_id=? AND content_item_id=?`).bind(PROJECT_ID,CONTENT_ID).all()).results||[];const map=new Map(rows.map(r=>[`${r.language_code}:${r.output_key}`,String(r.output_text||'')]));const languages=LANGS.map(l=>{const keys=Object.keys(canonical[l]);const matches=keys.filter(k=>map.get(`${l}:${k}`)===canonical[l][k]);return{language:l,expected:keys.length,matched:matches.length,all_match:matches.length===keys.length}});return{ok:true,languages,all_match:languages.every(x=>x.all_match)}}
