(()=>{
  const l=(document.documentElement.lang||'en').split('-')[0];
  const T={
    uk:{sub:'Мудрість, до якої хочеться повертатися.',read:'Читати останню статтю повністю',readSmall:'Найновіший матеріал Wise Quotes World',latest:'Усі цитати та роздуми',latestSmall:'Переглянути всі публікації цією мовою',channels:'Офіційні канали',site:'Сайт',change:'Змінити мову',foot:'Wise Quotes World — позачасові слова, вдумливо зібрані.',contact:'Зв’язатися з нами',contactText:'Маєте запитання, пропозицію або ідею для співпраці? Напишіть нам.',send:'Надіслати e-mail',direct:'Або напишіть напряму',subject:'Повідомлення з Wise Quotes World',soon:'У процесі створення',followers:'підписників'},
    ru:{sub:'Мудрость, к которой хочется возвращаться.',read:'Читать последнюю статью полностью',readSmall:'Самый новый материал Wise Quotes World',latest:'Все цитаты и размышления',latestSmall:'Посмотреть все публикации на русском',channels:'Официальные каналы',site:'Сайт',change:'Сменить язык',foot:'Wise Quotes World — вечные слова, собранные с вниманием.',contact:'Связаться с нами',contactText:'Есть вопрос, предложение или идея для сотрудничества? Напишите нам.',send:'Отправить e-mail',direct:'Или напишите напрямую',subject:'Сообщение с Wise Quotes World',soon:'В процессе создания',followers:'подписчиков'},
    pl:{sub:'Mądrość, do której chce się wracać.',read:'Przeczytaj najnowszy artykuł w całości',readSmall:'Najnowszy materiał Wise Quotes World',latest:'Wszystkie cytaty i refleksje',latestSmall:'Zobacz wszystkie publikacje po polsku',channels:'Oficjalne kanały',site:'Strona',change:'Zmień język',foot:'Wise Quotes World — ponadczasowe słowa, starannie wybrane.',contact:'Skontaktuj się z nami',contactText:'Masz pytanie, propozycję lub pomysł na współpracę? Napisz do nas.',send:'Wyślij e-mail',direct:'Lub napisz bezpośrednio',subject:'Wiadomość z Wise Quotes World',soon:'W przygotowaniu',followers:'obserwujących'},
    en:{sub:'Wisdom worth returning to.',read:'Read the latest article in full',readSmall:'Newest Wise Quotes World story',latest:'All quotes and reflections',latestSmall:'Browse all English publications',channels:'Official channels',site:'Website',change:'Change language',foot:'Wise Quotes World — timeless words, thoughtfully curated.',contact:'Contact us',contactText:'Have a question, suggestion, or collaboration idea? Send us a message.',send:'Send e-mail',direct:'Or e-mail us directly',subject:'Message from Wise Quotes World',soon:'Coming soon',followers:'followers / subscribers'},
    sv:{sub:'Visdom att återvända till.',read:'Läs den senaste artikeln i sin helhet',readSmall:'Senaste materialet från Wise Quotes World',latest:'Alla citat och reflektioner',latestSmall:'Se alla svenska publiceringar',channels:'Officiella kanaler',site:'Webbplats',change:'Byt språk',foot:'Wise Quotes World — tidlösa ord, omsorgsfullt utvalda.',contact:'Kontakta oss',contactText:'Har du en fråga, ett förslag eller en idé om samarbete? Skriv till oss.',send:'Skicka e-post',direct:'Eller mejla oss direkt',subject:'Meddelande från Wise Quotes World',soon:'Under förberedelse',followers:'följare / prenumeranter'},
    de:{sub:'Weisheit, zu der man gern zurückkehrt.',read:'Neuesten Artikel vollständig lesen',readSmall:'Der neueste Beitrag von Wise Quotes World',latest:'Alle Zitate und Gedanken',latestSmall:'Alle deutschsprachigen Beiträge ansehen',channels:'Offizielle Kanäle',site:'Website',change:'Sprache ändern',foot:'Wise Quotes World — zeitlose Worte, sorgfältig ausgewählt.',contact:'Kontakt',contactText:'Haben Sie eine Frage, einen Vorschlag oder eine Idee für eine Zusammenarbeit? Schreiben Sie uns.',send:'E-Mail senden',direct:'Oder schreiben Sie uns direkt',subject:'Nachricht von Wise Quotes World',soon:'In Vorbereitung',followers:'Follower / Abonnenten'},
    es:{sub:'Sabiduría a la que merece la pena volver.',read:'Leer completo el artículo más reciente',readSmall:'El contenido más reciente de Wise Quotes World',latest:'Todas las citas y reflexiones',latestSmall:'Ver todas las publicaciones en español',channels:'Canales oficiales',site:'Sitio web',change:'Cambiar idioma',foot:'Wise Quotes World — palabras atemporales, cuidadosamente seleccionadas.',contact:'Contáctanos',contactText:'¿Tienes una pregunta, propuesta o idea de colaboración? Escríbenos.',send:'Enviar e-mail',direct:'O escríbenos directamente',subject:'Mensaje desde Wise Quotes World',soon:'En preparación',followers:'seguidores / suscriptores'},
    fr:{sub:'Une sagesse à laquelle revenir.',read:'Lire le dernier article en entier',readSmall:'Le contenu le plus récent de Wise Quotes World',latest:'Toutes les citations et réflexions',latestSmall:'Voir toutes les publications en français',channels:'Canaux officiels',site:'Site web',change:'Changer de langue',foot:'Wise Quotes World — des mots intemporels, choisis avec soin.',contact:'Nous contacter',contactText:'Une question, une proposition ou une idée de collaboration ? Écrivez-nous.',send:'Envoyer un e-mail',direct:'Ou écrivez-nous directement',subject:'Message depuis Wise Quotes World',soon:'En préparation',followers:'abonnés'},
    it:{sub:'Una saggezza a cui vale la pena tornare.',read:'Leggi per intero l’ultimo articolo',readSmall:'Il contenuto più recente di Wise Quotes World',latest:'Tutte le citazioni e le riflessioni',latestSmall:'Scopri tutte le pubblicazioni in italiano',channels:'Canali ufficiali',site:'Sito web',change:'Cambia lingua',foot:'Wise Quotes World — parole senza tempo, scelte con cura.',contact:'Contattaci',contactText:'Hai una domanda, una proposta o un’idea di collaborazione? Scrivici.',send:'Invia un’e-mail',direct:'Oppure scrivi direttamente a',subject:'Messaggio da Wise Quotes World',soon:'In preparazione',followers:'follower / iscritti'},
    pt:{sub:'Sabedoria à qual vale a pena voltar.',read:'Leia o artigo mais recente na íntegra',readSmall:'O conteúdo mais recente do Wise Quotes World',latest:'Todas as citações e reflexões',latestSmall:'Veja todas as publicações em português',channels:'Canais oficiais',site:'Site',change:'Mudar idioma',foot:'Wise Quotes World — palavras atemporais, escolhidas com cuidado.',contact:'Fale conosco',contactText:'Tem uma pergunta, sugestão ou ideia de colaboração? Escreva para nós.',send:'Enviar e-mail',direct:'Ou escreva diretamente para',subject:'Mensagem do Wise Quotes World',soon:'Em preparação',followers:'seguidores / inscritos'},
    id:{sub:'Kebijaksanaan yang layak untuk direnungkan kembali.',read:'Baca artikel terbaru selengkapnya',readSmall:'Materi terbaru dari Wise Quotes World',latest:'Semua kutipan dan refleksi',latestSmall:'Lihat semua publikasi dalam bahasa Indonesia',channels:'Kanal resmi',site:'Situs web',change:'Ganti bahasa',foot:'Wise Quotes World — kata-kata abadi, dipilih dengan penuh pertimbangan.',contact:'Hubungi kami',contactText:'Punya pertanyaan, saran, atau ide kolaborasi? Kirim pesan kepada kami.',send:'Kirim e-mail',direct:'Atau kirim e-mail langsung ke',subject:'Pesan dari Wise Quotes World',soon:'Sedang disiapkan',followers:'pengikut / pelanggan'},
    tr:{sub:'Dönüp yeniden düşünmeye değer bilgelik.',read:'En son makalenin tamamını oku',readSmall:'Wise Quotes World’ün en yeni içeriği',latest:'Tüm alıntılar ve düşünceler',latestSmall:'Türkçe tüm yayınları görüntüle',channels:'Resmî kanallar',site:'Web sitesi',change:'Dili değiştir',foot:'Wise Quotes World — özenle seçilmiş zamansız sözler.',contact:'Bize ulaşın',contactText:'Bir sorunuz, öneriniz veya iş birliği fikriniz mi var? Bize yazın.',send:'E-posta gönder',direct:'Ya da doğrudan e-posta gönderin',subject:'Wise Quotes World mesajı',soon:'Hazırlanıyor',followers:'takipçi / abone'},
    ar:{sub:'حكمة تستحق أن نعود إليها.',read:'اقرأ أحدث مقال كاملًا',readSmall:'أحدث محتوى من Wise Quotes World',latest:'كل الاقتباسات والتأملات',latestSmall:'تصفّح جميع المنشورات بالعربية',channels:'القنوات الرسمية',site:'الموقع',change:'تغيير اللغة',foot:'Wise Quotes World — كلمات خالدة مختارة بعناية.',contact:'تواصل معنا',contactText:'لديك سؤال أو اقتراح أو فكرة للتعاون؟ راسلنا.',send:'إرسال بريد إلكتروني',direct:'أو راسلنا مباشرة على',subject:'رسالة من Wise Quotes World',soon:'قيد الإعداد',followers:'متابع / مشترك'}
  };
  const L={uk:'/uk/quotes/seneka-strazhdannia-v-uiavi/',ru:'/ru/quotes/seneka-stradanie-v-voobrazhenii/',pl:'/pl/quotes/seneka-cierpimy-w-wyobrazni/',en:'/en/quotes/seneca-suffer-in-imagination/',sv:'/sv/quotes/seneca-lider-i-fantasin/',de:'/de/quotes/seneca-leiden-in-der-vorstellung/',es:'/es/quotes/seneca-sufrimos-en-la-imaginacion/',fr:'/fr/quotes/seneque-souffrons-en-imagination/',it:'/it/quotes/seneca-soffriamo-piu-nell-immaginazione/',pt:'/pt/quotes/seneca-sofremos-mais-na-imaginacao/',id:'/id/quotes/seneca-kita-lebih-menderita-dalam-imajinasi/',tr:'/tr/quotes/seneca-hayalimizda-gercekten-daha-cok-acı-cekeriz/',ar:'/ar/quotes/سينيكا-نعاني-في-الخيال-أكثر-من-الواقع/'};
  const R={
    uk:{facebook:'https://www.facebook.com/878404672024804',instagram:'https://www.instagram.com/wisequotes.ua/',threads:'https://www.threads.com/@wisequotes.ua',tiktok:'https://www.tiktok.com/@wisequotes.ua',youtube:'https://www.youtube.com/channel/UCh1HcI0nmrm_ddAPfVvyCSg',pinterest:'https://www.pinterest.com/wisequotesworld/'},
    ru:{facebook:'https://www.facebook.com/840438055830136',instagram:'https://www.instagram.com/wisequotes.ru/',threads:'https://www.threads.com/@wisequotes.ru',tiktok:'https://www.tiktok.com/@wisequotes.ru',youtube:'https://www.youtube.com/channel/UCV7RTZl4bfpRal8yq4fWrww',pinterest:'https://www.pinterest.com/wisequotesworld/'},
    pl:{facebook:'https://www.facebook.com/1114233325116588',instagram:'https://www.instagram.com/wisequotes.pl/',threads:'https://www.threads.com/@wisequotes.pl',tiktok:'https://www.tiktok.com/@wisequotes.pl',youtube:'https://www.youtube.com/channel/UCQYOdpJO52DNZg3r8Rpnb2Q',pinterest:'https://www.pinterest.com/wisequotesworld/'},
    en:{facebook:'https://www.facebook.com/908076919052977',instagram:'https://www.instagram.com/wisequotes.en/',threads:'https://www.threads.com/@wisequotes.en',tiktok:'https://www.tiktok.com/@wisequotes.en',youtube:'https://www.youtube.com/channel/UCMwuq1k0jrz8dh2ocozUz1Q',pinterest:'https://www.pinterest.com/wisequotesworld/'},
    sv:{facebook:'https://www.facebook.com/929364273586587',instagram:'https://www.instagram.com/wisequotes.se/',threads:'https://www.threads.com/@wisequotes.se',tiktok:'https://www.tiktok.com/@wisequotes.se',youtube:'https://www.youtube.com/channel/UCHnu9TFYxibDvSEOEfQykhg',pinterest:'https://www.pinterest.com/wisequotesworld/'},
    de:{facebook:'https://www.facebook.com/1151007124763146',instagram:'https://www.instagram.com/wisequotes.de/',threads:'https://www.threads.com/@wisequotes.de',tiktok:'https://www.tiktok.com/@wisequotes.de',youtube:'https://www.youtube.com/channel/UCNy384R9H91PAIPWAHppvzw',pinterest:'https://www.pinterest.com/wisequotesworld/'},
    es:{facebook:'https://www.facebook.com/1064990903375476',instagram:'https://www.instagram.com/wisequotes.es/',threads:'https://www.threads.com/@wisequotes.es',tiktok:'https://www.tiktok.com/@wisequotes.es',youtube:'https://www.youtube.com/channel/UCnFTJvWS7lpYYC2zJYG925Q',pinterest:'https://www.pinterest.com/wisequotesworld/'},
    fr:{facebook:'https://www.facebook.com/1193265527213860',instagram:'https://www.instagram.com/wisequotes.fr',threads:'https://www.threads.com/@wisequotes.fr',tiktok:'https://www.tiktok.com/@wisequotes.fr',youtube:'https://www.youtube.com/channel/UCgjDE4kSf-THoL7OuxU-Kfw',pinterest:'https://www.pinterest.com/wisequotesworld/'},
    it:{pinterest:'https://www.pinterest.com/wisequotesworld/'},pt:{pinterest:'https://www.pinterest.com/wisequotesworld/'},id:{pinterest:'https://www.pinterest.com/wisequotesworld/'},tr:{pinterest:'https://www.pinterest.com/wisequotesworld/'},ar:{pinterest:'https://www.pinterest.com/wisequotesworld/'}
  };
  // Updated automatically by the existing daily Metricool follower-sync workflow.
  const S={
    uk:{facebook:10,instagram:941,threads:43,tiktok:56,youtube:38},ru:{facebook:7,instagram:44,threads:13,tiktok:92,youtube:104},pl:{facebook:17,instagram:17,threads:6,tiktok:40,youtube:37},en:{facebook:13,instagram:17,threads:10,tiktok:34,youtube:33},sv:{facebook:4,instagram:9,threads:6,tiktok:11,youtube:4},de:{facebook:19,instagram:105,threads:4,tiktok:68,youtube:24},es:{facebook:28,instagram:195,threads:3,tiktok:14,youtube:97},fr:{facebook:1,instagram:0,threads:0,tiktok:5,youtube:16}
  };
  const A=T[l]||T.en,links=R[l]||R.en,stats=S[l]||null,contactEmail='wisequotesofworld@gmail.com';
  const social=[['facebook','Facebook','📘'],['instagram','Instagram','📸'],['threads','Threads','🧵'],['tiktok','TikTok','🎵'],['youtube','YouTube','▶️'],['pinterest','Pinterest','📌']];
  const socialHtml=social.map(([key,name,icon])=>{
    if(!links[key]) return `<span class="btn disabled">${icon} ${name}<small>${A.soon}</small></span>`;
    const count=(key!=='pinterest'&&stats&&Number.isFinite(stats[key]))?`<small>${stats[key]} ${A.followers}</small>`:'';
    return `<a class="btn" href="${links[key]}" target="_blank" rel="noopener noreferrer">${icon} ${name}${count}</a>`;
  }).join('');
  document.getElementById('app').innerHTML=`<main class="wrap"><section class="card"><div class="top"><div class="logo">W</div><div><h1>Wise Quotes World</h1><p class="sub">${A.sub}</p></div></div><a class="btn primary" href="${L[l]||('/'+l+'/')}">📖 ${A.read}<small>${A.readSmall}</small></a><a class="btn" href="/${l}/">📚 ${A.latest}<small>${A.latestSmall}</small></a><div class="section"><h2>${A.channels}</h2><div class="grid"><a class="btn" href="/${l}/">🌐 ${A.site}</a>${socialHtml}</div></div><div class="section contact"><h2>${A.contact}</h2><p class="contact-intro">${A.contactText}</p><a class="btn primary contact-submit" href="mailto:${contactEmail}?subject=${encodeURIComponent(A.subject)}">✉️ ${A.send}</a><p class="direct-email">${A.direct}: <a href="mailto:${contactEmail}">${contactEmail}</a></p></div><a class="btn" href="/start/">🌍 ${A.change}</a><p class="foot">${A.foot}</p></section></main>`;
  const s=document.createElement('script');s.src='/start/newsletter.js?v=20260904-1528';document.body.appendChild(s);
})();