(()=>{
  const raw=(document.documentElement.lang||'en').toLowerCase();
  const l=raw.startsWith('pt')?'pt':raw.split('-')[0];
  const T={
    uk:{h:'Нові статті у вашій пошті',p:'Отримуйте нові цитати й роздуми українською. Не частіше одного листа на тиждень.',ph:'Ваш e-mail',b:'Підписатися',c:'Підписуючись, ви погоджуєтесь отримувати листи Wise Quotes World. Відписатися можна будь-коли.',ok:'Готово. Ваш e-mail додано до української розсилки.',bad:'Введіть коректну e-mail адресу.',err:'Не вдалося зберегти підписку. Спробуйте ще раз.'},
    ru:{h:'Новые статьи по почте',p:'Получайте новые цитаты и размышления на русском. Не чаще одного письма в неделю.',ph:'Ваш e-mail',b:'Подписаться',c:'Подписываясь, вы соглашаетесь получать письма Wise Quotes World. Отписаться можно в любое время.',ok:'Готово. Ваш e-mail добавлен в русскоязычную рассылку.',bad:'Введите корректный e-mail.',err:'Не удалось сохранить подписку. Попробуйте еще раз.'},
    pl:{h:'Nowe artykuły na Twój e-mail',p:'Otrzymuj nowe cytaty i refleksje po polsku. Nie częściej niż raz w tygodniu.',ph:'Twój e-mail',b:'Zapisz się',c:'Zapisując się, zgadzasz się na otrzymywanie wiadomości od Wise Quotes World. Możesz zrezygnować w każdej chwili.',ok:'Gotowe. Twój e-mail został dodany do polskiego newslettera.',bad:'Wpisz poprawny adres e-mail.',err:'Nie udało się zapisać subskrypcji. Spróbuj ponownie.'},
    en:{h:'New articles in your inbox',p:'Receive new quotes and reflections in English. No more than one e-mail per week.',ph:'Your e-mail',b:'Subscribe',c:'By subscribing, you agree to receive e-mails from Wise Quotes World. You can unsubscribe at any time.',ok:'Done. Your e-mail has been added to the English newsletter.',bad:'Enter a valid e-mail address.',err:'Could not save your subscription. Please try again.'},
    sv:{h:'Nya artiklar i din inkorg',p:'Få nya citat och reflektioner på svenska. Högst ett mejl i veckan.',ph:'Din e-post',b:'Prenumerera',c:'Genom att prenumerera samtycker du till att få e-post från Wise Quotes World. Du kan avsluta prenumerationen när som helst.',ok:'Klart. Din e-post har lagts till i den svenska prenumerationen.',bad:'Ange en giltig e-postadress.',err:'Det gick inte att spara prenumerationen. Försök igen.'},
    de:{h:'Neue Artikel per E-Mail',p:'Erhalten Sie neue Zitate und Reflexionen auf Deutsch. Höchstens eine E-Mail pro Woche.',ph:'Ihre E-Mail-Adresse',b:'Abonnieren',c:'Mit dem Abonnement stimmen Sie dem Erhalt von E-Mails von Wise Quotes World zu. Sie können sich jederzeit abmelden.',ok:'Fertig. Ihre E-Mail-Adresse wurde zum deutschen Newsletter hinzugefügt.',bad:'Bitte geben Sie eine gültige E-Mail-Adresse ein.',err:'Das Abonnement konnte nicht gespeichert werden. Bitte versuchen Sie es erneut.'},
    es:{h:'Nuevos artículos en tu correo',p:'Recibe nuevas citas y reflexiones en español. Como máximo un correo por semana.',ph:'Tu e-mail',b:'Suscribirme',c:'Al suscribirte, aceptas recibir correos de Wise Quotes World. Puedes darte de baja en cualquier momento.',ok:'Listo. Tu e-mail se ha añadido al boletín en español.',bad:'Introduce un e-mail válido.',err:'No se pudo guardar la suscripción. Inténtalo de nuevo.'},
    fr:{h:'Les nouveaux articles par e-mail',p:'Recevez de nouvelles citations et réflexions en français. Pas plus d’un e-mail par semaine.',ph:'Votre e-mail',b:'S’abonner',c:'En vous abonnant, vous acceptez de recevoir des e-mails de Wise Quotes World. Vous pouvez vous désabonner à tout moment.',ok:'C’est fait. Votre e-mail a été ajouté à la newsletter française.',bad:'Saisissez une adresse e-mail valide.',err:'Impossible d’enregistrer l’abonnement. Veuillez réessayer.'},
    it:{h:'Nuovi articoli via e-mail',p:'Ricevi nuove citazioni e riflessioni in italiano. Non più di un’e-mail a settimana.',ph:'La tua e-mail',b:'Iscriviti',c:'Iscrivendoti accetti di ricevere e-mail da Wise Quotes World. Puoi annullare l’iscrizione in qualsiasi momento.',ok:'Fatto. La tua e-mail è stata aggiunta alla newsletter italiana.',bad:'Inserisci un indirizzo e-mail valido.',err:'Non è stato possibile salvare l’iscrizione. Riprova.'},
    pt:{h:'Novos artigos no seu e-mail',p:'Receba novas citações e reflexões em português do Brasil. No máximo um e-mail por semana.',ph:'Seu e-mail',b:'Assinar',c:'Ao assinar, você concorda em receber e-mails do Wise Quotes World. É possível cancelar a assinatura a qualquer momento.',ok:'Pronto. Seu e-mail foi adicionado à newsletter em português do Brasil.',bad:'Digite um endereço de e-mail válido.',err:'Não foi possível salvar a assinatura. Tente novamente.'},
    id:{h:'Artikel baru lewat e-mail',p:'Dapatkan kutipan dan refleksi baru dalam Bahasa Indonesia. Maksimal satu e-mail per minggu.',ph:'E-mail Anda',b:'Berlangganan',c:'Dengan berlangganan, Anda setuju menerima e-mail dari Wise Quotes World. Anda dapat berhenti berlangganan kapan saja.',ok:'Selesai. E-mail Anda telah ditambahkan ke newsletter Bahasa Indonesia.',bad:'Masukkan alamat e-mail yang valid.',err:'Langganan tidak dapat disimpan. Silakan coba lagi.'},
    tr:{h:'Yeni yazılar e-postanıza gelsin',p:'Türkçe yeni alıntıları ve düşünceleri alın. Haftada en fazla bir e-posta.',ph:'E-posta adresiniz',b:'Abone ol',c:'Abone olarak Wise Quotes World’dan e-posta almayı kabul edersiniz. İstediğiniz zaman abonelikten çıkabilirsiniz.',ok:'Tamam. E-posta adresiniz Türkçe bültene eklendi.',bad:'Geçerli bir e-posta adresi girin.',err:'Abonelik kaydedilemedi. Lütfen tekrar deneyin.'},
    ar:{h:'مقالات جديدة في بريدك',p:'احصل على اقتباسات وتأملات جديدة بالعربية. بحد أقصى رسالة واحدة في الأسبوع.',ph:'بريدك الإلكتروني',b:'اشترك',c:'بالاشتراك، توافق على تلقي رسائل من Wise Quotes World. يمكنك إلغاء الاشتراك في أي وقت.',ok:'تم. أُضيف بريدك الإلكتروني إلى النشرة العربية.',bad:'أدخل عنوان بريد إلكتروني صحيحًا.',err:'تعذر حفظ الاشتراك. حاول مرة أخرى.'}
  };
  const A=T[l]||T.en, contact=document.querySelector('.section.contact');
  if(!contact||document.getElementById('newsletter-form'))return;
  const box=document.createElement('div');
  box.className='section newsletter-section';
  box.innerHTML=`<h2>${A.h}</h2><p class="contact-intro">${A.p}</p><form id="newsletter-form"><div class="newsletter-row"><input id="newsletter-email" type="email" autocomplete="email" inputmode="email" placeholder="${A.ph}" aria-label="${A.ph}" required><button class="btn primary" type="submit">✉️ ${A.b}</button></div><input id="newsletter-company" class="newsletter-hp" tabindex="-1" autocomplete="off" aria-hidden="true"><p class="newsletter-consent">${A.c}</p><p id="newsletter-status" class="newsletter-status" role="status" aria-live="polite"></p></form>`;
  contact.parentNode.insertBefore(box,contact);
  if(!document.getElementById('newsletter-shared-style')){const st=document.createElement('style');st.id='newsletter-shared-style';st.textContent='.newsletter-section{border:1px solid rgba(215,181,109,.3);border-radius:18px;padding:18px;margin-top:24px}.newsletter-section h2{margin-top:0}.newsletter-row{display:flex;gap:10px}.newsletter-row input{flex:1;min-width:0;border:1px solid var(--line);border-radius:12px;background:var(--panel);color:var(--text);padding:13px;font:inherit}.newsletter-row button{width:auto;min-width:145px;margin:0;cursor:pointer}.newsletter-consent{font-size:12px;color:var(--muted);line-height:1.45}.newsletter-status{font-size:13px;color:var(--gold2);min-height:18px}.newsletter-hp{position:absolute!important;left:-10000px!important;width:1px!important;height:1px!important;opacity:0!important}@media(max-width:560px){.newsletter-row{display:block}.newsletter-row button{width:100%;margin-top:10px}}';document.head.appendChild(st)}
  const f=document.getElementById('newsletter-form'),e=document.getElementById('newsletter-email'),s=document.getElementById('newsletter-status'),c=document.getElementById('newsletter-company');
  f.addEventListener('submit',async ev=>{ev.preventDefault();s.textContent='';if(!e.validity.valid){s.textContent=A.bad;return}const b=f.querySelector('button');b.disabled=true;try{const r=await fetch('/api/newsletter/subscribe',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:e.value,language:l,company:c.value})});const d=await r.json();if(!r.ok||!d.ok)throw new Error('subscribe');s.textContent=A.ok;e.value=''}catch(_){s.textContent=A.err}finally{b.disabled=false}});
})();